force-app/main/default/objects/EncryptedDataGDPR__c/EncryptedDataGDPR__c.object-meta.xml
<CustomObject>
    <description>Object used to encrypt data for the GDPR</description>
    <label>Encrypted Data GDPR</label>
    <nameField>
        <displayFormat>Encrypted Data-{00000}</displayFormat>
        <label>Encrypted Data GDPR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encrypted Datas GDPR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EncryptedDataGDPR__c/fields/MobilePhoneEncrypted__c.field-meta.xml
<CustomField>
    <fullName>MobilePhoneEncrypted__c</fullName>
    <description>Mobile phone from lead or Contact encrypted</description>
    <label>Mobile Phone Encrypted</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/REP_EncryptedDataGDPRTest.cls
/**
@author Guilherme Charro
@date    08/10/2021
@description Test class for DO_Contact
@TestClass         
Modification Log:
----------------------------------------------------------------------------------------------------
Developer                       Date                Description                           Coverage
----------------------------------------------------------------------------------------------------
Guilherme Charro                08/10/2021         Original Version                         100
*/
@isTest
private class REP_EncryptedDataGDPRTest {
    @isTest
    static void EncryptedDataGDPRTest() {
        List<EncryptedDataGDPR__c> encryptedDataList = FW_TestDataFactory.createEncryptedData(1, true);

        test.startTest();
        REP_EncryptedDataGDPR encryptedDataRepository = new REP_EncryptedDataGDPR();   
        List<EncryptedDataGDPR__c> encryptedDataReturnedList = encryptedDataRepository.getEncryptedData(new List<String>{encryptedDataList[0].MobilePhoneEncrypted__c});
        test.stopTest();
        System.assertEquals(1, encryptedDataList.size());
    }
}