force-app/main/default/objects/EncryptedDataGDPR__c/EncryptedDataGDPR__c.object-meta.xml
<CustomObject>
    <description>Object used to encrypt data for the GDPR</description>
    <label>Encrypted Data GDPR</label>
    <nameField>
        <displayFormat>Encrypted Data-{00000}</displayFormat>
        <label>Encrypted Data GDPR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encrypted Datas GDPR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EncryptedDataGDPR__c/fields/BusinessPhoneEncrypted__c.field-meta.xml
<CustomField>
    <fullName>BusinessPhoneEncrypted__c</fullName>
    <description>Business phone from lead or Contact encrypted</description>
    <label>Business Phone Encrypted</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EncryptedDataGDPR__c/fields/EmailEncrypted__c.field-meta.xml
<CustomField>
    <fullName>EmailEncrypted__c</fullName>
    <description>Email from lead or Contact encrypted</description>
    <label>Email Encrypted</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EncryptedDataGDPR__c/fields/MobilePhoneEncrypted__c.field-meta.xml
<CustomField>
    <fullName>MobilePhoneEncrypted__c</fullName>
    <description>Mobile phone from lead or Contact encrypted</description>
    <label>Mobile Phone Encrypted</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/REP_EncryptedDataGDPR.cls
/**
* @description   EncryptedDataGDPR__c Repository
* @testClass     REP_EncryptedDataGDPRTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro              28/09/2021         Created EncryptedDataGDPR__c Repository
* ------------------------------------------------------------------------------------ 
*/
public class REP_EncryptedDataGDPR extends FW_SobjectRep implements IREP_EncryptedDataGDPR{
    /**
    * @description method to search if there are any values of the newly inserted lead already in the EncryptedDataGDPR__c object
    * @author Guilherme Charro | 29-09-2021 
    * @param dataToSearchList list of strings that will be used to compare if these values are already in the database
    * @return List<REP_EncryptedDataGDPR> return the list of records returned
    **/
    public List<EncryptedDataGDPR__c> getEncryptedData(List<String> dataToSearchList){
        return [
            SELECT Id, BusinessPhoneEncrypted__c, EmailEncrypted__c, MobilePhoneEncrypted__c 
            FROM EncryptedDataGDPR__c 
            WHERE BusinessPhoneEncrypted__c IN :dataToSearchList 
            OR EmailEncrypted__c IN :dataToSearchList 
            OR MobilePhoneEncrypted__c IN :dataToSearchList
        ];
    }
}