force-app/main/default/objects/EncryptedDataGDPR__c/EncryptedDataGDPR__c.object-meta.xml
<CustomObject>
    <description>Object used to encrypt data for the GDPR</description>
    <label>Encrypted Data GDPR</label>
    <nameField>
        <displayFormat>Encrypted Data-{00000}</displayFormat>
        <label>Encrypted Data GDPR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encrypted Datas GDPR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/GeneralGDPR__c.field-meta.xml
<CustomField>
    <fullName>GeneralGDPR__c</fullName>
    <description>Field to register GDPR consent</description>
    <label>General GDPR</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TW_Lead_CheckGDPR.cls
/**
* @description   worker class to check if GDPR was accepted or not
* @testClass     TW_Lead_CheckGDPRTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro               28/09/2021          Created Lead Worker
* ------------------------------------------------------------------------------------ 
*/
public without sharing class TW_Lead_CheckGDPR {
    private IREP_EncryptedDataGDPR encryptedDataRepository;

    /**
    * @description constructor
    * @author Guilherme Charro | 29-09-2021 
    **/
    public TW_Lead_CheckGDPR(){
        this.encryptedDataRepository = new REP_EncryptedDataGDPR();
    }
   
    /**
    * @description constructor for test class
    * @author Guilherme Charro | 29-09-2021 
    **/
    @TestVisible
    private TW_Lead_CheckGDPR(IREP_EncryptedDataGDPR encryptedDataRepository){
        this.encryptedDataRepository = encryptedDataRepository;
    }

    /**
    * @description execute method
    * @author Guilherme Charro | 29-09-2021 
    **/
    public void execute(List<Lead> leadList, Map<Id,Lead> leadOldMap) {
        List<EncryptedDataGDPR__c> encryptedDataToInsertList = new List<EncryptedDataGDPR__c>();

        for (Lead leadUpdated : leadList) {
            if(leadUpdated.GeneralGDPR__c == DO_Lead.LEAD_GDPR_NO && leadUpdated.GeneralGDPR__c != leadOldMap.get(leadUpdated.Id).GeneralGDPR__c){
                EncryptedDataGDPR__c encrypedDataRecord = DO_EncryptedDataGDPR.createEncryptedData(
                    DO_EncryptedDataGDPR.encryptData(leadUpdated.MobilePhone),
                    DO_EncryptedDataGDPR.encryptData(leadUpdated.Phone),
                    DO_EncryptedDataGDPR.encryptData(leadUpdated.Email)
                );

                if (encrypedDataRecord!=null) {
                    encryptedDataToInsertList.add(encrypedDataRecord);
                }
            }
        }

        if (!encryptedDataToInsertList.isEmpty()) {
            encryptedDataRepository.insertSObjects(encryptedDataToInsertList);
        }
    }
}