force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Batch Definition</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Definition__c/fields/Batch_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Name__c</fullName>
    <description>It has the execution batch name, this is the value that will drive a specific execution of a batch (for example: TestBatch-Morning, TestBatch-Night or just TestBatch)</description>
    <externalId>true</externalId>
    <label>Batch Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Batch_Definition__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>It has the exact name of the dynamic batchable apex class</description>
    <label>Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Definition__c/fields/Job_Size__c.field-meta.xml
<CustomField>
    <fullName>Job_Size__c</fullName>
    <defaultValue>200</defaultValue>
    <description>To set the size of the batch. limit between 1 and 2000</description>
    <label>Job Size</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Definition__c/fields/SObject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_API_Name__c</fullName>
    <description>This represents SObject API name of the scope of the batch.</description>
    <label>SObject API Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEPSkipValidationRules__c/CEPSkipValidationRules__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to skip validation rules</description>
    <label>CEP Skip Validation Rules</label>
</CustomObject>

force-app/main/default/objects/Contact/fields/RelatedActivityDate__c.field-meta.xml
<CustomField>
    <fullName>RelatedActivityDate__c</fullName>
    <description>Field used to know when was the last related activity to this contact. Used for GDPR.</description>
    <label>Related Activity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FW_TriggerHandlerSettings__c/FW_TriggerHandlerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Determines if trigger handlers should be enabled or disabled (unchecked = enabled)</description>
    <label>Trigger Handler Settings</label>
</CustomObject>

force-app/main/default/objects/Job_Execution__c/Job_Execution__c.object-meta.xml
<CustomObject>
    <description>This object represents a new batch execution.</description>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000000000}</displayFormat>
        <label>Job Execution</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the batch which is required to be executed</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Size__c.field-meta.xml
<CustomField>
    <fullName>Job_Size__c</fullName>
    <defaultValue>200</defaultValue>
    <description>To set the size of the batch. Limit is between 1 and 2000</description>
    <label>Job Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Run_With_Defaults__c.field-meta.xml
<CustomField>
    <fullName>Run_With_Defaults__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this field is true the batch filter condition will be the same that we have on the batch definition object for the same Job name, this will call a trigger that will copy the filter logic and the filter condition records
Others: Default True</description>
    <label>Run With Defaults</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Parameters__c/Parameters__c.object-meta.xml
<CustomObject>
    <description>This object represents parameters that can be used by the batch to set default values, change filter conditions, actions etc.</description>
    <label>Parameter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parameters__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Batch link for which this parameter is valid</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to the Job Execution Object</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Defines the value of the parameter, can be a set of Ids, a status value, a constant etc</description>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Async_ContactInactiveTest.cls
/**
@author Guilherme Charro
@date    07/10/2021
@description Test class for Async_ContactInactive
@TestClass         
Modification Log:
----------------------------------------------------------------------------------------------------
Developer                       Date                Description                           Coverage
----------------------------------------------------------------------------------------------------
Guilherme Charro                   07/10/2021         Original Version                       100
*/
@isTest
private class Async_ContactInactiveTest {
    static fflib_ApexMocks mocks = new fflib_ApexMocks();

    @isTest
    static void contactInactiveTest() {
        IREP_Contact contactRepository = (REP_Contact)mocks.mock(REP_Contact.class);
        ISL_ChatterNotifications contactChatterNotification = (SL_ChatterNotifications)mocks.mock(SL_ChatterNotifications.class);
        FW_IREP_JobExecution jobExecutionRep = (FW_REP_JobExecution)mocks.mock(FW_REP_JobExecution.class);
        FW_IREP_Parameters parameterRep = (FW_REP_Parameters)mocks.mock(FW_REP_Parameters.class);
        IDO_Contact contactDomain = (DO_Contact)mocks.mock(DO_Contact.class);
        IREP_CEPSkipValidationRules cepSkipValidationRulesRepository = (REP_CEPSkipValidationRules)mocks.mock(REP_CEPSkipValidationRules.class);
        IREP_TriggerHandlerSettings triggerHandlerSettingsRepository = (REP_TriggerHandlerSettings)mocks.mock(REP_TriggerHandlerSettings.class);
            
        //Create Batch_Definition
        List<Batch_Definition__c> batchDefinitionList = new List<Batch_Definition__c>{
            new Batch_Definition__c(
                Id = fflib_IDGenerator.generate(Batch_Definition__c.sObjectType),
                Batch_Name__c = 'BatchTest',
                Class_Name__c = 'Async_ContactInactive',
                Job_Size__c = 200,
                SObject_API_Name__c = 'Contact'
            )
        };
        //Create Parameters
        List<Parameters__c> parametersList = new List<Parameters__c>{
            new Parameters__c(
                Id = fflib_IDGenerator.generate(Parameters__c.sObjectType),
                Name = FW_AsyncHandler.DEFAULT_PARAMETER
            ),
            new Parameters__c(
                Id = fflib_IDGenerator.generate(Parameters__c.sObjectType),
                Name = 'Years',
                Value__c='-3'
            ),
            new Parameters__c(
                Id = fflib_IDGenerator.generate(Parameters__c.sObjectType),
                Name = 'Days',
                Value__c='7'
            )     
        };

        //Create JobExecution
        List<Job_Execution__c> jobExecutionList = new List<Job_Execution__c>{
            new Job_Execution__c(
                Id = fflib_IDGenerator.generate(Job_Execution__c.sObjectType),
                Batch_Definition__c = batchDefinitionList.get(0).id,
                Run_With_Defaults__c = true              
            )
        };

        Date yearsAgo = DATE.TODAY().addYears(-3);
        Date daysAgo = yearsAgo.addDays(7);
            
        List<Contact> contactList = new List<Contact>{
            new Contact(
                Id = fflib_IDGenerator.generate(Contact.sObjectType),
                RelatedActivityDate__c = yearsAgo
            ),
            new Contact(
                Id = fflib_IDGenerator.generate(Contact.sObjectType),
                RelatedActivityDate__c = daysAgo.addDays(-1)
            )
        };

        mocks.startStubbing();
        mocks.when(contactDomain.createContact((Id)  fflib_match.anyObject())).thenReturn(contactList[0]);
        ((ISL_ChatterNotifications) mocks.doAnswer( new VoidAnswer(),contactChatterNotification)).persistChatterPosts();
        mocks.when(jobExecutionRep.getJobExecWithBatchDefinitionsByIdSet((Set<Id>)fflib_match.anyObject())).thenReturn(jobExecutionList);
        mocks.when(jobExecutionRep.getJobExecutionByAsyncApexJobIdSet((Id)fflib_match.anyObject())).thenReturn(jobExecutionList);
        mocks.when(parameterRep.getParametersByParentId((Set<Id>)fflib_match.anyObject())).thenReturn(parametersList);
        mocks.when(cepSkipValidationRulesRepository.updateSObjects((List<CEPSkipValidationRules__c>)  fflib_match.anyList())).thenReturn(new List<Database.SaveResult>());
        mocks.when(triggerHandlerSettingsRepository.updateSObjects((List<FW_TriggerHandlerSettings__c>)  fflib_match.anyList())).thenReturn(new List<Database.SaveResult>());
        mocks.stopStubbing();
           
 
        Async_ContactInactive newBatchRun = new Async_ContactInactive();
        newBatchRun = new Async_ContactInactive(contactRepository, jobExecutionRep, parameterRep, contactChatterNotification, contactDomain, cepSkipValidationRulesRepository, triggerHandlerSettingsRepository);

        Database.executeBatch(newBatchRun);
        newBatchRun.setAsyncApexJobId(null);
        newBatchRun.execute(null, contactList);
        
        ((FW_IREP_JobExecution)mocks.verify(jobExecutionRep, 1)).getJobExecWithBatchDefinitionsByIdSet((Set<Id>)fflib_match.anyObject());
        ((FW_IREP_Parameters)mocks.verify(parameterRep, 1)).getParametersByParentId((Set<Id>)fflib_match.anyObject());
        ((IDO_Contact)mocks.verify(contactDomain, 1)).createContact((Id) fflib_match.anyObject());
        ((IREP_CEPSkipValidationRules)mocks.verify(cepSkipValidationRulesRepository, 2)).updateSObjects((List<CEPSkipValidationRules__c>) fflib_match.anyList());
        ((IREP_TriggerHandlerSettings)mocks.verify(triggerHandlerSettingsRepository, 2)).updateSObjects((List<FW_TriggerHandlerSettings__c>) fflib_match.anyList());
    }

    class VoidAnswer implements fflib_Answer {
        public Object answer (fflib_InvocationOnMock invocation) {
            return null;
        }
    }
}