force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Batch Definition</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyCode__c/CompanyCode__c.object-meta.xml
<CustomObject>
    <description>This datatable is used for all business lines, to allow aggregating each Customer (Account) to the corresponding OMV subsidiary</description>
    <label>Company Code</label>
    <nameField>
        <label>Company Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Execution__c/Job_Execution__c.object-meta.xml
<CustomObject>
    <description>This object represents a new batch execution.</description>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000000000}</displayFormat>
        <label>Job Execution</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the batch which is required to be executed</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OMVEntityEmployee__c/OMVEntityEmployee__c.object-meta.xml
<CustomObject>
    <description>junction object created to maintain a relationship between the users and the omv Entities</description>
    <label>OMV Entity Employee</label>
    <nameField>
        <displayFormat>EE-{00000}</displayFormat>
        <label>Entity Employee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OMV Entity Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OMVEntityEmployee__c/fields/EmployeeUser__c.field-meta.xml
<CustomField>
    <fullName>EmployeeUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User related to the OMV Entity</description>
    <label>Employee User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CompanyCodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OMVEntityEmployee__c/fields/OMVEntity__c.field-meta.xml
<CustomField>
    <fullName>OMVEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OMV Entity related to the employee</description>
    <label>OMV Entity</label>
    <referenceTo>CompanyCode__c</referenceTo>
    <relationshipLabel>OMV Entity Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OMVEntityEmployee__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <description>Technical field created to prevent the association of an user to more than one OMV Entity</description>
    <externalId>true</externalId>
    <label>Unique Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parameters__c/Parameters__c.object-meta.xml
<CustomObject>
    <description>This object represents parameters that can be used by the batch to set default values, change filter conditions, actions etc.</description>
    <label>Parameter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parameters__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Batch link for which this parameter is valid</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to the Job Execution Object</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Defines the value of the parameter, can be a set of Ids, a status value, a constant etc</description>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TW_OMVEntityEmployee_UpdateUniqueID.cls
/**
* @description   worker class to update Unique Field and Show errors
* @testClass     TW_OMVEntityEmployee_UpdateUniqueIDTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Hugo Rodrigues               20/10/2021         Created the class
* Hugo Rodrigues               04/03/2021         updated to meet US39484 requirements
* ------------------------------------------------------------------------------------ 
*/
public with sharing class TW_OMVEntityEmployee_UpdateUniqueID {

    private IREP_OMVEntityEmployee oMVEntityRepository;
    private FW_IREP_BatchDefinition batchDefRep;
    private FW_IREP_JobExecution jobExecutionRep;
    private FW_IDO_JobExecution jobExecutionDO;
    private FW_IREP_Parameters parameterRep;

    public TW_OMVEntityEmployee_UpdateUniqueID(){
        this.oMVEntityRepository = new REP_OMVEntityEmployee();
        this.batchDefRep = new FW_REP_BatchDefinition();
        this.jobExecutionRep = new FW_REP_JobExecution();
        this.jobExecutionDO = new FW_DO_JobExecution();
        this.parameterRep = new FW_REP_Parameters();
        
    }
    
    @TestVisible
    private TW_OMVEntityEmployee_UpdateUniqueID(IREP_OMVEntityEmployee oMVEntityRepository,FW_IREP_BatchDefinition batchDefRep, FW_IREP_JobExecution jobExecutionRep, FW_IDO_JobExecution jobExecutionDO,FW_IREP_Parameters parameterRep){
        this.oMVEntityRepository = oMVEntityRepository;
        this.batchDefRep = batchDefRep;
        this.jobExecutionRep = jobExecutionRep;
        this.jobExecutionDO = jobExecutionDO;
        this.parameterRep = parameterRep;
    }
    
    public void execute(List<OMVEntityEmployee__c> oMVList, Map<Id,OMVEntityEmployee__c> oldOmvMap) {
        Set<ID> userIDSet = new Set<ID>();
        List<OMVEntityEmployee__c> omvEmployeeToUpdatedList = new List<OMVEntityEmployee__c>();
        List<OMVEntityEmployee__c> oMVEntityEmployeeList =new List<OMVEntityEmployee__c>();
        Map<String,OMVEntityEmployee__c> oMVEntityEmployeeMap = new Map<String,OMVEntityEmployee__c>();
        Set<ID> userBatchIDSet = new Set<ID>();
        if(oMVList==null){
            for(OMVEntityEmployee__c entityRecord :oldOmvMap.Values()){
                userBatchIDSet.add(entityRecord.EmployeeUser__c);
            }
        }
        else{
            for(OMVEntityEmployee__c entityRecord : oMVList){
                if(entityRecord.EmployeeUser__c ==null){
                    entityRecord.addError(Label.ApexOMVEntityEmptyError);
                }
                else if(oldOmvMap == null){
                        userIDSet.add(entityRecord.EmployeeUser__c);
                        omvEmployeeToUpdatedList.add(entityRecord);
                        userBatchIDSet.add(entityRecord.EmployeeUser__c);
                }
                else if(oldOmvMap != null && (entityRecord.UniqueKey__c != oldOmvMap.get(entityRecord.Id).UniqueKey__c || entityRecord.EmployeeUser__c != oldOmvMap.get(entityRecord.Id).EmployeeUser__c)){
                    entityRecord.addError(Label.ApexOMVEntityChangeError);
                }
                else if(oldOmvMap != null && entityRecord.OMVEntity__c != oldOmvMap.get(entityRecord.Id).OMVEntity__c ){
                    userBatchIDSet.add(entityRecord.EmployeeUser__c);
                }
            }
        }

        if(!userIDSet.isEmpty()){
             oMVEntityEmployeeList= oMVEntityRepository.getCompanyCodeByUserID(userIDSet);
        }

        for(OMVEntityEmployee__c omvEntity : oMVEntityEmployeeList){
            oMVEntityEmployeeMap.put(omvEntity.EmployeeUser__c,omvEntity);
        }

        if(!oMVEntityEmployeeMap.isEmpty()){
            for (OMVEntityEmployee__c entityRecord :omvEmployeeToUpdatedList){
                if(oMVEntityEmployeeMap.containsKey(entityRecord.EmployeeUser__c)){
                    entityRecord.addError(Label.ApexUserChangeError + ' ' + oMVEntityEmployeeMap.get(entityRecord.EmployeeUser__c).OMVEntity__r.Name + Label.ApexUserChangeError2);
                }
                else{
                    entityRecord.UniqueKey__c = entityRecord.EmployeeUser__c;
                }
            }
        }
        if(!userBatchIDSet.isEmpty()){
            List<Batch_Definition__c> bdList = batchDefRep.getBatchDefinitionByNameSet(new Set<String>{'EmployeeEntityUpdate'});

            
        if(bdList.isEmpty()){
            createErrorLog();
        }else{
            list<Parameters__c> parameterList = parameterRep.getParametersByBatchDefinitionIdAndName(new Set<ID>{bdList[0].id},new Set<String>{'OwnerIDFromLead'});
            for(Parameters__c parameter : parameterList){
                parameter.Value__c = string.valueof(userBatchIDSet).replace('{', '').replace('}', '');
            }
            if(!parameterList.isEmpty()){
                parameterRep.updateSObjects(parameterList);
            }
            
            jobExecutionRep.insertSObjects(new list<Job_Execution__c>{jobExecutionDO.createJobExecutionsFromBD(bdList[0].id)});
            
        }

       }
    }
    
    /**  
        *  @description:    Create an error log record
    **/ 
    private void createErrorLog(){
        FW_ErrorAndMonitoringLog errorLog = new FW_ErrorAndMonitoringLog.ErrorDetailsBuilder()
                            .setErrorMessage('Batch execution not found for EmployeeEntityUpdate at '+Datetime.now())
                            .setOrigin(String.valueOf(this))
                            .setCategory(FW_ErrorAndMonitoringLog.categoryType.Apex_Class)
                            .setActorId(UserInfo.getUserId())
                            .build();

        new FW_SystemNotificationPublr(errorLog);
    }

}