force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Batch Definition</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Definition__c/fields/Batch_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Name__c</fullName>
    <description>It has the execution batch name, this is the value that will drive a specific execution of a batch (for example: TestBatch-Morning, TestBatch-Night or just TestBatch)</description>
    <externalId>true</externalId>
    <label>Batch Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Batch_Definition__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>It has the exact name of the dynamic batchable apex class</description>
    <label>Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Definition__c/fields/Job_Size__c.field-meta.xml
<CustomField>
    <fullName>Job_Size__c</fullName>
    <defaultValue>200</defaultValue>
    <description>To set the size of the batch. limit between 1 and 2000</description>
    <label>Job Size</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Definition__c/fields/SObject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_API_Name__c</fullName>
    <description>This represents SObject API name of the scope of the batch.</description>
    <label>SObject API Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CompanyCode__c/CompanyCode__c.object-meta.xml
<CustomObject>
    <description>This datatable is used for all business lines, to allow aggregating each Customer (Account) to the corresponding OMV subsidiary</description>
    <label>Company Code</label>
    <nameField>
        <label>Company Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyCode__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Identification of default language for the OMV subsidiary customers</description>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerLanguage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Execution__c/Job_Execution__c.object-meta.xml
<CustomObject>
    <description>This object represents a new batch execution.</description>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000000000}</displayFormat>
        <label>Job Execution</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the batch which is required to be executed</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Size__c.field-meta.xml
<CustomField>
    <fullName>Job_Size__c</fullName>
    <defaultValue>200</defaultValue>
    <description>To set the size of the batch. Limit is between 1 and 2000</description>
    <label>Job Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Run_With_Defaults__c.field-meta.xml
<CustomField>
    <fullName>Run_With_Defaults__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this field is true the batch filter condition will be the same that we have on the batch definition object for the same Job name, this will call a trigger that will copy the filter logic and the filter condition records
Others: Default True</description>
    <label>Run With Defaults</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Finished_with_Errors</fullName>
                <label>Finished with Errors</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>field to register the company code of the lead</description>
    <label>OMV Entity</label>
    <referenceTo>CompanyCode__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OMVEntityEmployee__c/OMVEntityEmployee__c.object-meta.xml
<CustomObject>
    <description>junction object created to maintain a relationship between the users and the omv Entities</description>
    <label>OMV Entity Employee</label>
    <nameField>
        <displayFormat>EE-{00000}</displayFormat>
        <label>Entity Employee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OMV Entity Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OMVEntityEmployee__c/fields/EmployeeUser__c.field-meta.xml
<CustomField>
    <fullName>EmployeeUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User related to the OMV Entity</description>
    <label>Employee User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CompanyCodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OMVEntityEmployee__c/fields/OMVEntity__c.field-meta.xml
<CustomField>
    <fullName>OMVEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OMV Entity related to the employee</description>
    <label>OMV Entity</label>
    <referenceTo>CompanyCode__c</referenceTo>
    <relationshipLabel>OMV Entity Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/Parameters__c.object-meta.xml
<CustomObject>
    <description>This object represents parameters that can be used by the batch to set default values, change filter conditions, actions etc.</description>
    <label>Parameter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parameters__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Batch link for which this parameter is valid</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to the Job Execution Object</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Defines the value of the parameter, can be a set of Ids, a status value, a constant etc</description>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/CustomerLanguage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BG</fullName>
        <label>Bulgarian</label>
    </customValue>
    <customValue>
        <fullName>CS</fullName>
        <label>Czech</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <label>German</label>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
        <label>Hungarian</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <label>Romanian</label>
    </customValue>
    <customValue>
        <fullName>SR</fullName>
        <label>Serbian</label>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
        <label>Slovak</label>
    </customValue>
    <customValue>
        <fullName>SL</fullName>
        <label>Slovenian</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <label>Croatian</label>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
        <label>Bosnian</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Polish</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italian</label>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
        <label>Turkish</label>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
        <label>Russian</label>
    </customValue>
    <customValue>
        <fullName>ro_MD</fullName>
        <label>Moldovan</label>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
        <isActive>false</isActive>
        <label>Moldova</label>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
        <isActive>false</isActive>
        <label>Austria</label>
    </customValue>
    <masterLabel>Customer Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TW_OMVEntityEmployee_UpdateUniqueIDTest.cls
/**
@author Hugo Rodrigues  
@date   20/10/2021 
@description Test class for TW_OMVEntityEmployee_UpdateUniqueID
@TestClass         
Modification Log:
----------------------------------------------------------------------------------------------------
Developer                       Date                Description                           Coverage
----------------------------------------------------------------------------------------------------
Hugo Rodrigues               20/10/2021           Original Version                         100
*/
@isTest
public with sharing class TW_OMVEntityEmployee_UpdateUniqueIDTest {
    static fflib_ApexMocks mocks = new fflib_ApexMocks();
    
    @isTest
    private static void updateUniqueIDTest() {
        IREP_OMVEntityEmployee oMVEntityRepository = (REP_OMVEntityEmployee)mocks.mock(REP_OMVEntityEmployee.class);
        FW_IREP_BatchDefinition batchDefRep = (FW_REP_BatchDefinition)mocks.mock(FW_REP_BatchDefinition.class);
        FW_IREP_BatchDefinition batchDefRep2 = (FW_REP_BatchDefinition)mocks.mock(FW_REP_BatchDefinition.class);
        FW_IREP_JobExecution jobExecutionRep = (FW_REP_JobExecution)mocks.mock(FW_REP_JobExecution.class);
        FW_IDO_JobExecution jobExecutionDO = (FW_DO_JobExecution)mocks.mock(FW_DO_JobExecution.class);
        FW_IREP_Parameters parameterRep = (FW_REP_Parameters)mocks.mock(FW_REP_Parameters.class);

        List<CompanyCode__c> companyCodeList = new  List<CompanyCode__c>();
        Map<ID,OMVEntityEmployee__c> oMVEntityEmployeeMap = new Map<ID,OMVEntityEmployee__c>();
        
        Set<Id> omvEntityIdSet = new Set<Id>();
        //Create Batch_Definition
        List<Batch_Definition__c> batchDefinitionList = new List<Batch_Definition__c>{
            new Batch_Definition__c(
                Id = fflib_IDGenerator.generate(Batch_Definition__c.sObjectType),
                Batch_Name__c = 'EmployeeEntityUpdate', 
                Class_Name__c = 'Async_EmployeeEntityUpdate',
                Job_Size__c = 200, 
                SObject_API_Name__c = 'Lead'
            )
        };
        
        //Create Parameters 
        List<Parameters__c> parametersList = new List<Parameters__c>{
            new Parameters__c(
                Id = fflib_IDGenerator.generate(Parameters__c.sObjectType),
                Name = 'OwnerIDFromLead',
                Batch_Definition__c = batchDefinitionList.get(0).id,
                Value__c = String.valueOf(fflib_IDGenerator.generate(User.sObjectType))
            ),
            new Parameters__c(
                Id = fflib_IDGenerator.generate(Parameters__c.sObjectType),
                Name = 'Status',
                Batch_Definition__c = batchDefinitionList.get(0).id,
                Value__c = 'New,Working'
            )
        };


        //Create JobExecution
        List<Job_Execution__c> jobExecutionList = new List<Job_Execution__c>{
            new Job_Execution__c(
                Id = fflib_IDGenerator.generate(Job_Execution__c.sObjectType),
                Batch_Definition__c = batchDefinitionList.get(0).id,
                Run_With_Defaults__c = true,
                Status__c = FW_DO_JobExecution.JOB_EXEC_STATUS_NEW
            )
        };
        companyCodeList.add(new CompanyCode__c(
            Id = fflib_IDGenerator.generate(CompanyCode__c.sObjectType),
            Name = 'teste',
            Language__c = 'EN'
        ));
        List<OMVEntityEmployee__c> oMVEntityEmployeeList = new  List<OMVEntityEmployee__c>{
            new OMVEntityEmployee__c(
                Id = fflib_IDGenerator.generate(OMVEntityEmployee__c.sObjectType),
                EmployeeUser__c=null,
                OMVEntity__c=companyCodeList[0].Id
            ),
            new OMVEntityEmployee__c(
                Id = fflib_IDGenerator.generate(OMVEntityEmployee__c.sObjectType),
                EmployeeUser__c=fflib_IDGenerator.generate(User.sObjectType),
                OMVEntity__c=companyCodeList[0].Id
            ),
            new OMVEntityEmployee__c(
                Id = fflib_IDGenerator.generate(OMVEntityEmployee__c.sObjectType),
                EmployeeUser__c=fflib_IDGenerator.generate(User.sObjectType),
                OMVEntity__c=companyCodeList[0].Id
            )
        };
        List<OMVEntityEmployee__c> oMVEntityEmployeeList2 = new  List<OMVEntityEmployee__c>{
            new OMVEntityEmployee__c(
                Id = fflib_IDGenerator.generate(OMVEntityEmployee__c.sObjectType),
                EmployeeUser__c=oMVEntityEmployeeList[2].EmployeeUser__c,
                OMVEntity__c=companyCodeList[0].Id
            )
        };
        oMVEntityEmployeeMap.put(oMVEntityEmployeeList[1].Id,
             new OMVEntityEmployee__c(
                Id = oMVEntityEmployeeList[1].Id,
                EmployeeUser__c = oMVEntityEmployeeList[1].EmployeeUser__c
            )
        );
        oMVEntityEmployeeMap.put(oMVEntityEmployeeList[2].Id,
             new OMVEntityEmployee__c(
                Id = oMVEntityEmployeeList[2].Id,
                EmployeeUser__c = oMVEntityEmployeeList[2].EmployeeUser__c
            )
        );
        omvEntityIdSet.add(oMVEntityEmployeeList2[0].Id);
        mocks.startStubbing();
        mocks.when(oMVEntityRepository.getCompanyCodeByUserID((Set<Id>) fflib_match.anyObject())).thenReturn(oMVEntityEmployeeList2);
        mocks.when(batchDefRep.getBatchDefinitionByNameSet((Set<String>) fflib_match.anyObject())).thenReturn(batchDefinitionList); 
        mocks.when(jobExecutionDO.createJobExecutionsFromBD((ID) fflib_match.anyObject())).thenReturn(jobExecutionList[0]);
        mocks.when(parameterRep.getParametersByBatchDefinitionIdAndName((Set<Id>) fflib_match.anyObject(),(Set<String>) fflib_match.anyObject())).thenReturn(parametersList);
        mocks.when(parameterRep.updateSObjects((List<Parameters__c>)  fflib_match.anyList())).thenReturn(new List<Database.SaveResult>());
        mocks.when( jobExecutionRep.insertSObjects((List<Job_Execution__c>)  fflib_match.anyList())).thenReturn(new List<Database.SaveResult>());
        mocks.stopStubbing();
        TW_OMVEntityEmployee_UpdateUniqueID jobExecutionWorker = new TW_OMVEntityEmployee_UpdateUniqueID();
        jobExecutionWorker = new TW_OMVEntityEmployee_UpdateUniqueID(oMVEntityRepository,batchDefRep,jobExecutionRep,jobExecutionDO,parameterRep);
    
        jobExecutionWorker.execute(oMVEntityEmployeeList,null);
        jobExecutionWorker.execute(null,oMVEntityEmployeeMap);
        jobExecutionWorker.execute(oMVEntityEmployeeList,oMVEntityEmployeeMap);

        ((IREP_OMVEntityEmployee)mocks.verify(oMVEntityRepository, 1)).getCompanyCodeByUserID((Set<ID>)fflib_match.anyObject());
        ((FW_IREP_BatchDefinition)mocks.verify(batchDefRep, 3)).getBatchDefinitionByNameSet((Set<String>)fflib_match.anyObject());
        ((FW_IDO_JobExecution)mocks.verify(jobExecutionDO, 3)).createJobExecutionsFromBD((ID)fflib_match.anyObject());
        ((FW_IREP_JobExecution)mocks.verify(jobExecutionRep, 3)).insertSObjects((List<Job_Execution__c>) fflib_match.eq(jobExecutionList));
        ((FW_IREP_Parameters)mocks.verify(parameterRep, 3)).updateSObjects((List<Parameters__c>) fflib_match.eq(parametersList));
        System.assertEquals(oMVEntityEmployeeList[1], oMVEntityEmployeeList[1]);

    }
    
    @isTest
    private static void updateUniqueIDTestNOkTest(){
        IREP_OMVEntityEmployee oMVEntityRepository = (REP_OMVEntityEmployee)mocks.mock(REP_OMVEntityEmployee.class);
        FW_IREP_BatchDefinition batchDefRep = (FW_REP_BatchDefinition)mocks.mock(FW_REP_BatchDefinition.class);
        FW_IREP_JobExecution jobExecutionRep = (FW_REP_JobExecution)mocks.mock(FW_REP_JobExecution.class);
        FW_IDO_JobExecution jobExecutionDO = (FW_DO_JobExecution)mocks.mock(FW_DO_JobExecution.class);
        FW_IREP_Parameters parameterRep = (FW_REP_Parameters)mocks.mock(FW_REP_Parameters.class);
        List<Batch_Definition__c> batchDefinitionList = new List<Batch_Definition__c>();
        List<CompanyCode__c> companyCodeList = new  List<CompanyCode__c>();
        Map<ID,OMVEntityEmployee__c> oMVEntityEmployeeMap = new Map<ID,OMVEntityEmployee__c>();

        companyCodeList.add(new CompanyCode__c(
            Id = fflib_IDGenerator.generate(CompanyCode__c.sObjectType),
            Name = 'teste',
            Language__c = 'EN'
        ));
        List<OMVEntityEmployee__c> oMVEntityEmployeeList = new  List<OMVEntityEmployee__c>{
            new OMVEntityEmployee__c(
                Id = fflib_IDGenerator.generate(OMVEntityEmployee__c.sObjectType),
                EmployeeUser__c=null,
                OMVEntity__c=companyCodeList[0].Id
            ),
            new OMVEntityEmployee__c(
                Id = fflib_IDGenerator.generate(OMVEntityEmployee__c.sObjectType),
                EmployeeUser__c=fflib_IDGenerator.generate(User.sObjectType),
                OMVEntity__c=companyCodeList[0].Id
            ),
            new OMVEntityEmployee__c(
                Id = fflib_IDGenerator.generate(OMVEntityEmployee__c.sObjectType),
                EmployeeUser__c=fflib_IDGenerator.generate(User.sObjectType),
                OMVEntity__c=companyCodeList[0].Id
            )
        };
        oMVEntityEmployeeMap.put(oMVEntityEmployeeList[1].Id,
             new OMVEntityEmployee__c(
                Id = oMVEntityEmployeeList[1].Id,
                EmployeeUser__c = oMVEntityEmployeeList[1].EmployeeUser__c
            )
        );
        oMVEntityEmployeeMap.put(oMVEntityEmployeeList[2].Id,
             new OMVEntityEmployee__c(
                Id = oMVEntityEmployeeList[2].Id,
                EmployeeUser__c = oMVEntityEmployeeList[2].EmployeeUser__c
            )
        );
        mocks.startStubbing();
        mocks.when(oMVEntityRepository.getCompanyCodeByUserID((Set<Id>) fflib_match.anyObject())).thenReturn(oMVEntityEmployeeList);
        mocks.when(batchDefRep.getBatchDefinitionByNameSet((Set<String>) fflib_match.anyObject())).thenReturn(batchDefinitionList); 
        mocks.stopStubbing();

        TW_OMVEntityEmployee_UpdateUniqueID jobExecutionWorker = new TW_OMVEntityEmployee_UpdateUniqueID();
        jobExecutionWorker = new TW_OMVEntityEmployee_UpdateUniqueID(oMVEntityRepository,batchDefRep, jobExecutionRep, jobExecutionDO,parameterRep);
        jobExecutionWorker.execute(oMVEntityEmployeeList,oMVEntityEmployeeMap);
        
    }
}