force-app/main/default/objects/CompanyCode__c/CompanyCode__c.object-meta.xml
<CustomObject>
    <description>This datatable is used for all business lines, to allow aggregating each Customer (Account) to the corresponding OMV subsidiary</description>
    <label>Company Code</label>
    <nameField>
        <label>Company Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyCode__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Identification of OMV subsidiary country</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerCountry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>field to register the company code of the lead</description>
    <label>OMV Entity</label>
    <referenceTo>CompanyCode__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CompanyCodeCountry__c.field-meta.xml
<CustomField>
    <fullName>CompanyCodeCountry__c</fullName>
    <description>field used for sharing rules</description>
    <label>Company Code Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerCountry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OMVEntityEmployee__c/OMVEntityEmployee__c.object-meta.xml
<CustomObject>
    <description>junction object created to maintain a relationship between the users and the omv Entities</description>
    <label>OMV Entity Employee</label>
    <nameField>
        <displayFormat>EE-{00000}</displayFormat>
        <label>Entity Employee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OMV Entity Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OMVEntityEmployee__c/fields/EmployeeUser__c.field-meta.xml
<CustomField>
    <fullName>EmployeeUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User related to the OMV Entity</description>
    <label>Employee User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CompanyCodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OMVEntityEmployee__c/fields/OMVEntity__c.field-meta.xml
<CustomField>
    <fullName>OMVEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OMV Entity related to the employee</description>
    <label>OMV Entity</label>
    <referenceTo>CompanyCode__c</referenceTo>
    <relationshipLabel>OMV Entity Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/CustomerCountry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CZ</fullName>
        <label>Czech Republic</label>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
        <label>Hungary</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
        <label>Slovakia</label>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
        <label>Bulgaria</label>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
        <label>Austria</label>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
        <label>Moldova</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <label>Romania</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <label>Croatia</label>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
        <label>Bosnia</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Poland</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
        <label>Turkey</label>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
        <label>Russia</label>
    </customValue>
    <customValue>
        <fullName>SH</fullName>
        <label>Serbia</label>
    </customValue>
    <customValue>
        <fullName>SL</fullName>
        <label>Slovenia</label>
    </customValue>
    <customValue>
        <fullName>Hungarian</fullName>
        <isActive>false</isActive>
        <label>Hungarian</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
        <isActive>false</isActive>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>Slovak</fullName>
        <isActive>false</isActive>
        <label>Slovak</label>
    </customValue>
    <customValue>
        <fullName>Romanian</fullName>
        <isActive>false</isActive>
        <label>Romanian</label>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
        <isActive>false</isActive>
        <label>Bulgarian</label>
    </customValue>
    <customValue>
        <fullName>German</fullName>
        <isActive>false</isActive>
        <label>German</label>
    </customValue>
    <description>Global value set to store working languages for OMV CEP business lines. Available languages should match the activated languages in the Translation Language Settings.</description>
    <masterLabel>Customer Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TW_Lead_FillComplementaryFields.cls
/**
@description    worker class to automatically fill needed fields
@testClass      TW_Lead_FillComplementaryFieldsTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description  
* Guilherme Charro                08/09/2021          Created the class
* Hugo Rodrigues                  20/10/2021         updated to meet US39484 description
* ------------------------------------------------------------------------------------        
*/
public with sharing class TW_Lead_FillComplementaryFields {
    private IREP_CompanyCode companyCodeRepository;
    private IREP_OMVEntityEmployee oMVEntityRepository;

    public TW_Lead_FillComplementaryFields(){
        this.companyCodeRepository = new REP_CompanyCode();
        this.oMVEntityRepository = new REP_OMVEntityEmployee();
        
    }
    
    @TestVisible
    private TW_Lead_FillComplementaryFields(IREP_CompanyCode companyCodeRepository,IREP_OMVEntityEmployee oMVEntityRepository){
        this.companyCodeRepository = companyCodeRepository;
        this.oMVEntityRepository = oMVEntityRepository;
    }

    public void execute(List<Lead> leadList, Map<Id,Lead> oldLeadMap) {
        Set<Id> companyCodeIdsSet = new Set<Id>();
        Set<Id> userIdsSet = new Set<Id>();
        for (Lead leadInserted : leadList) {
            if(leadInserted.OwnerID.getsobjecttype()==User.sobjecttype && (oldLeadMap==null|| (oldLeadMap!=null && leadInserted.OwnerID != oldLeadMap.get(leadInserted.Id).OwnerID))){
                userIdsSet.add(leadInserted.OwnerID);
                companyCodeIdsSet.add(leadInserted.CompanyCode__c);
            }
            else if (leadInserted.OwnerID.getsobjecttype()!=User.sobjecttype) {
                leadInserted.CompanyCodeCountry__c = null;
                leadInserted.CompanyCode__c = null;
            }
        }

        List<OMVEntityEmployee__c> oMVEntityEmployeeList =new List<OMVEntityEmployee__c>();
        Map<String,OMVEntityEmployee__c> oMVEntityEmployeeMap = new Map<String,OMVEntityEmployee__c>();

        if(!userIdsSet.isEmpty()){
           
            oMVEntityEmployeeList= oMVEntityRepository.getCompanyCodeByUserID(userIdsSet);
        }
        
        for(OMVEntityEmployee__c omvEntity : oMVEntityEmployeeList){
            oMVEntityEmployeeMap.put(omvEntity.EmployeeUser__c,omvEntity);
        }

        Map<Id,CompanyCode__c> companyCodeMap = new Map<Id,CompanyCode__c>();

        if (!companyCodeIdsSet.isEmpty()) {
            companyCodeMap = new Map<Id,CompanyCode__c>(companyCodeRepository.getCompanyCodeInfo(companyCodeIdsSet));
        }        

        for (Lead leadInserted : leadList) {
            if(oMVEntityEmployeeMap.containsKey(leadInserted.OwnerID)){
                leadInserted.CompanyCode__c = oMVEntityEmployeeMap.get(leadInserted.OwnerID).OMVEntity__c;
            }
            if (companyCodeMap.containsKey(leadInserted.CompanyCode__c) && DO_Lead.LEAD_RECORDTYPE_CARDSLIST.contains(leadInserted.RecordTypeId) && !String.isBlank(leadInserted.CompanyCode__c) 
            && (oldLeadMap == null || (oldLeadMap != null && leadInserted.CompanyCode__c != oldLeadMap.get(leadInserted.Id).CompanyCode__c))) {
                leadInserted.CompanyCodeCountry__c = companyCodeMap.get(leadInserted.CompanyCode__c).Country__c;
            }
            else if (!oMVEntityEmployeeMap.containsKey(leadInserted.OwnerID) &&(oldLeadMap==null || (leadInserted.OwnerID != oldLeadMap.get(leadInserted.Id).OwnerID))){
                leadInserted.CompanyCode__c =null;
            }           
        }        
    }
}