force-app/main/default/objects/CompanyCode__c/CompanyCode__c.object-meta.xml
<CustomObject>
    <description>This datatable is used for all business lines, to allow aggregating each Customer (Account) to the corresponding OMV subsidiary</description>
    <label>Company Code</label>
    <nameField>
        <label>Company Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OMVEntityEmployee__c/OMVEntityEmployee__c.object-meta.xml
<CustomObject>
    <description>junction object created to maintain a relationship between the users and the omv Entities</description>
    <label>OMV Entity Employee</label>
    <nameField>
        <displayFormat>EE-{00000}</displayFormat>
        <label>Entity Employee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OMV Entity Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OMVEntityEmployee__c/fields/EmployeeUser__c.field-meta.xml
<CustomField>
    <fullName>EmployeeUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User related to the OMV Entity</description>
    <label>Employee User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CompanyCodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OMVEntityEmployee__c/fields/OMVEntity__c.field-meta.xml
<CustomField>
    <fullName>OMVEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OMV Entity related to the employee</description>
    <label>OMV Entity</label>
    <referenceTo>CompanyCode__c</referenceTo>
    <relationshipLabel>OMV Entity Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/REP_OMVEntityEmployeeTest.cls
/**
@author Hugo Rodrigues  
@date   20/10/2021 
@description Test class for REP_OMVEntityEmployee
@TestClass         
Modification Log:
----------------------------------------------------------------------------------------------------
Developer                       Date                Description                           Coverage
----------------------------------------------------------------------------------------------------
Hugo Rodrigues               20/10/2021           Original Version                         100
*/
@isTest
public class REP_OMVEntityEmployeeTest {
	@isTest
    static void OMVEntityEmployeeTest(){
        List<User> runningUserList = FW_TestDataFactory.createUsers(3, true, 'System Administrator', null);
        System.runAs(runningUserList[0]){  
            List<CompanyCode__c> companyCodeList = FW_TestDataFactory.createCompanyCode(1, true);
            List<OMVEntityEmployee__c> oMVEntityEmployeeList = new  List<OMVEntityEmployee__c>{
                new OMVEntityEmployee__c(
                    EmployeeUser__c=runningUserList[0].Id,
                    OMVEntity__c=companyCodeList[0].Id
                ),
                new OMVEntityEmployee__c(
                    EmployeeUser__c=runningUserList[1].Id,
                    OMVEntity__c=companyCodeList[0].Id
                ),
                new OMVEntityEmployee__c(
                    EmployeeUser__c=runningUserList[2].Id,
                    OMVEntity__c=companyCodeList[0].Id
                )
            };
            insert oMVEntityEmployeeList;
            Set<ID> userIdSet = new Set<ID>{
                runningUserList[0].Id,
                runningUserList[1].Id,
                runningUserList[2].Id
            };
            test.startTest();
            REP_OMVEntityEmployee oMVEntityEmployeeRepository = new REP_OMVEntityEmployee();
                List<OMVEntityEmployee__c> OMVEntityEmployeeReturned = oMVEntityEmployeeRepository.getCompanyCodeByUserID(userIdSet);
            test.stopTest();
            System.assertEquals(3, OMVEntityEmployeeReturned.size());
        }
    }
}