force-app/main/default/objects/CompanyCode__c/CompanyCode__c.object-meta.xml
<CustomObject>
    <description>This datatable is used for all business lines, to allow aggregating each Customer (Account) to the corresponding OMV subsidiary</description>
    <label>Company Code</label>
    <nameField>
        <label>Company Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FW_TriggerHandlerSettings__c/FW_TriggerHandlerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Determines if trigger handlers should be enabled or disabled (unchecked = enabled)</description>
    <label>Trigger Handler Settings</label>
</CustomObject>

force-app/main/default/objects/FW_TriggerHandlerSettings__c/fields/All__c.field-meta.xml
<CustomField>
    <fullName>All__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag for all trigger, if true all triggers will be skipped</description>
    <label>Skip All</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>field to register the company code of the lead</description>
    <label>OMV Entity</label>
    <referenceTo>CompanyCode__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OMVEntityEmployee__c/OMVEntityEmployee__c.object-meta.xml
<CustomObject>
    <description>junction object created to maintain a relationship between the users and the omv Entities</description>
    <label>OMV Entity Employee</label>
    <nameField>
        <displayFormat>EE-{00000}</displayFormat>
        <label>Entity Employee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OMV Entity Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OMVEntityEmployee__c/fields/EmployeeUser__c.field-meta.xml
<CustomField>
    <fullName>EmployeeUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User related to the OMV Entity</description>
    <label>Employee User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CompanyCodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OMVEntityEmployee__c/fields/OMVEntity__c.field-meta.xml
<CustomField>
    <fullName>OMVEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OMV Entity related to the employee</description>
    <label>OMV Entity</label>
    <referenceTo>CompanyCode__c</referenceTo>
    <relationshipLabel>OMV Entity Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Async_EmployeeEntityUpdate.cls
/**
* @description   BactJob to update OMV Entity on Lead object
* @testClass     Async_EmployeeEntityUpdateTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Hugo Rodrigues                03/11/2021          BactJob to update OMV Entity on Lead object
* ------------------------------------------------------------------------------------ 
*/
global class Async_EmployeeEntityUpdate extends FW_AsyncHandler implements Database.Batchable<sObject>, Database.stateful{
   
    private IREP_OMVEntityEmployee oMVEntityRepository;
    private IREP_Lead leadRepository;
    private static final String STATUS = 'Status';
    private static final String OWNERIDFROMLEAD = 'OwnerIDFromLead';
    global Async_EmployeeEntityUpdate() {

        oMVEntityRepository = new REP_OMVEntityEmployee();
        leadRepository = new REP_Lead();

    }

    @testVisible
    private Async_EmployeeEntityUpdate(IREP_OMVEntityEmployee oMVEntityRepository,FW_IREP_JobExecution jobExecutionRep, FW_IREP_Parameters parameterRep, IREP_Lead leadRepository) {

        this.oMVEntityRepository = oMVEntityRepository;
        this.jobExecutionRep = jobExecutionRep;
        this.parameterRep = parameterRep;
        this.leadRepository = leadRepository;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        setAsyncApexJobId(bc.getJobId());
        List<String> statusList = getParameterValue(STATUS).split(',');
        List<String> userIdList = getParameterValue(OWNERIDFROMLEAD).split(',');
        FW_QueryBuilder query = new FW_QueryBuilder(Lead.SObjectType)
        .selectFields(REP_Lead.LEAD_FIELDS)
        .whereIn('Status',statusList)
        .whereIn('OwnerID',userIdList);
        return executeQuery(query);
    }

    global void execute(Database.BatchableContext bc, List<Lead> leadList) {
        
        Map<String,OMVEntityEmployee__c> oMVEntityEmployeeMap = new Map<String,OMVEntityEmployee__c>();
        List<Lead> leadToUpdateList = new List<Lead> ();
        Set<Id> ownerIdSet = new Set<Id>();
        
        for (Lead leadRecord : leadList) {
            ownerIdSet.add(leadRecord.OwnerId);    
        }

        for(OMVEntityEmployee__c omvEntity : oMVEntityRepository.getCompanyCodeByUserID( ownerIdSet ) ){
            oMVEntityEmployeeMap.put(omvEntity.EmployeeUser__c,omvEntity);
        }
        for(Lead leadRecord : leadList){  
            if(oMVEntityEmployeeMap.containsKey(leadRecord.OwnerID)){
                leadRecord.CompanyCode__c = oMVEntityEmployeeMap.get(leadRecord.OwnerID).OMVEntity__c;
                leadToUpdateList.add(leadRecord);
            }
            else{
                leadRecord.CompanyCode__c = null;
                leadToUpdateList.add(leadRecord);
            }
        }

        if(!leadToUpdateList.isEmpty()){
            FW_TriggerHandlerSettings__c skipTriggerLogic = FW_TriggerHandlerSettings__c.getInstance();
            skipTriggerLogic.All__c = true;
            upsert skipTriggerLogic;
            leadRepository.updateSObjects(leadToUpdateList);
            skipTriggerLogic.All__c = false;
            upsert skipTriggerLogic;
        }
    
    }

    global void finish(Database.BatchableContext bc) {
        finishBatch(bc.getJobId());
    }
}