force-app/main/default/objects/CompanyCode__c/CompanyCode__c.object-meta.xml
<CustomObject>
    <description>This datatable is used for all business lines, to allow aggregating each Customer (Account) to the corresponding OMV subsidiary</description>
    <label>Company Code</label>
    <nameField>
        <label>Company Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>field to register the company code of the lead</description>
    <label>OMV Entity</label>
    <referenceTo>CompanyCode__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/GeneralGDPR__c.field-meta.xml
<CustomField>
    <fullName>GeneralGDPR__c</fullName>
    <description>Field to register GDPR consent</description>
    <label>General GDPR</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/REP_Lead.cls
/**
* @description   Lead Repository
* @testClass     REP_LeadTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro              28/09/2021         Created Lead Repository
* Hugo Rodrigues                04/11/2021         added getLeadByUserID
* ------------------------------------------------------------------------------------ 
*/
public class REP_Lead extends FW_SobjectRep implements IREP_Lead{
    public static final List<SObjectField> LEAD_FIELDS = new SObjectField[] {
        Lead.Id,
        Lead.Name,
        Lead.GeneralGDPR__c,
        Lead.CompanyCode__c,
        Lead.isConverted,
        Lead.OwnerID,
        Lead.Status

    };

    public List<Lead> getLeadNotConvertedByUserID(Set<ID> userID) {

        return [SELECT Id, OwnerId,CompanyCode__c,isConverted FROM Lead Where OwnerId =: userID And isConverted = false];
    }
    public String getLeadsByOwnerIdAndStatuses(Set<Id> userIds, List<String> leadStatuses){
        return 'Select Id, CompanyCode__c, OwnerId From Lead Where OwnerId =: userIds AND Status IN:leadStatuses ';
    }
}