force-app/main/default/objects/CompanyCode__c/CompanyCode__c.object-meta.xml
<CustomObject>
    <description>This datatable is used for all business lines, to allow aggregating each Customer (Account) to the corresponding OMV subsidiary</description>
    <label>Company Code</label>
    <nameField>
        <label>Company Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OMVEntityEmployee__c/OMVEntityEmployee__c.object-meta.xml
<CustomObject>
    <description>junction object created to maintain a relationship between the users and the omv Entities</description>
    <label>OMV Entity Employee</label>
    <nameField>
        <displayFormat>EE-{00000}</displayFormat>
        <label>Entity Employee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OMV Entity Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OMVEntityEmployee__c/fields/EmployeeUser__c.field-meta.xml
<CustomField>
    <fullName>EmployeeUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User related to the OMV Entity</description>
    <label>Employee User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CompanyCodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OMVEntityEmployee__c/fields/OMVEntity__c.field-meta.xml
<CustomField>
    <fullName>OMVEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OMV Entity related to the employee</description>
    <label>OMV Entity</label>
    <referenceTo>CompanyCode__c</referenceTo>
    <relationshipLabel>OMV Entity Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OMVEntityEmployee__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <description>Technical field created to prevent the association of an user to more than one OMV Entity</description>
    <externalId>true</externalId>
    <label>Unique Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/REP_OMVEntityEmployee.cls
/**
* @description   OMV Entity Employee Repository
* @testClass     REP_OMVEntityEmployeeTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Hugo Rodrigues               20/10/2021         Created OMV Entity Employee Repository
* ------------------------------------------------------------------------------------ 
*/
public with sharing class REP_OMVEntityEmployee extends FW_SobjectRep implements IREP_OMVEntityEmployee{

    public List<OMVEntityEmployee__c> getCompanyCodeByUserID(Set<ID> userID) {

        return [SELECT Id, EmployeeUser__c, UniqueKey__c,OMVEntity__c, OMVEntity__r.Name FROM OMVEntityEmployee__c Where EmployeeUser__c IN: userID];
    }
}