force-app/main/default/objects/CompanyCode__c/CompanyCode__c.object-meta.xml
<CustomObject>
    <description>This datatable is used for all business lines, to allow aggregating each Customer (Account) to the corresponding OMV subsidiary</description>
    <label>Company Code</label>
    <nameField>
        <label>Company Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyCode__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Identification of OMV subsidiary country</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerCountry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>field to register the company code of the lead</description>
    <label>OMV Entity</label>
    <referenceTo>CompanyCode__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OMVEntityEmployee__c/OMVEntityEmployee__c.object-meta.xml
<CustomObject>
    <description>junction object created to maintain a relationship between the users and the omv Entities</description>
    <label>OMV Entity Employee</label>
    <nameField>
        <displayFormat>EE-{00000}</displayFormat>
        <label>Entity Employee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OMV Entity Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OMVEntityEmployee__c/fields/EmployeeUser__c.field-meta.xml
<CustomField>
    <fullName>EmployeeUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User related to the OMV Entity</description>
    <label>Employee User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CompanyCodes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OMVEntityEmployee__c/fields/OMVEntity__c.field-meta.xml
<CustomField>
    <fullName>OMVEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>OMV Entity related to the employee</description>
    <label>OMV Entity</label>
    <referenceTo>CompanyCode__c</referenceTo>
    <relationshipLabel>OMV Entity Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/CustomerCountry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CZ</fullName>
        <label>Czech Republic</label>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
        <label>Hungary</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
        <label>Slovakia</label>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
        <label>Bulgaria</label>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
        <label>Austria</label>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
        <label>Moldova</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <label>Romania</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <label>Croatia</label>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
        <label>Bosnia</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Poland</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
        <label>Turkey</label>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
        <label>Russia</label>
    </customValue>
    <customValue>
        <fullName>SH</fullName>
        <label>Serbia</label>
    </customValue>
    <customValue>
        <fullName>SL</fullName>
        <label>Slovenia</label>
    </customValue>
    <customValue>
        <fullName>Hungarian</fullName>
        <isActive>false</isActive>
        <label>Hungarian</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
        <isActive>false</isActive>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>Slovak</fullName>
        <isActive>false</isActive>
        <label>Slovak</label>
    </customValue>
    <customValue>
        <fullName>Romanian</fullName>
        <isActive>false</isActive>
        <label>Romanian</label>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
        <isActive>false</isActive>
        <label>Bulgarian</label>
    </customValue>
    <customValue>
        <fullName>German</fullName>
        <isActive>false</isActive>
        <label>German</label>
    </customValue>
    <description>Global value set to store working languages for OMV CEP business lines. Available languages should match the activated languages in the Translation Language Settings.</description>
    <masterLabel>Customer Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TW_Lead_FillComplementaryFieldsTest.cls
/**
@author Guilherme Charro 
@date   08/09/2021 
@description Test class for TW_OMVEntityEmployee_UpdateUniqueID
@TestClass         
Modification Log:
----------------------------------------------------------------------------------------------------
Developer                       Date                Description                           Coverage
----------------------------------------------------------------------------------------------------
Guilherme Charro              08/09/2021            Original Version                         100
Hugo Rodrigues                20/10/2021            US39484 update                           100
Hugo Rodrigues                27/10/2021            Added new Lead with Owner Group          100

*/
@isTest
public with sharing class TW_Lead_FillComplementaryFieldsTest {
    static fflib_ApexMocks mocks = new fflib_ApexMocks();

    @isTest
    static void fillComplementaryFieldsTest() {
        IREP_CompanyCode companyCodeRepository = (REP_CompanyCode)mocks.mock(REP_CompanyCode.class);
        IREP_OMVEntityEmployee oMVEntityRepository = (REP_OMVEntityEmployee)mocks.mock(REP_OMVEntityEmployee.class);
        List<OMVEntityEmployee__c> oMVEntityEmployeeList = new  List<OMVEntityEmployee__c>();
       
        List<CompanyCode__c> companyCodeList = new List<CompanyCode__c>{
            new CompanyCode__c(
                Id = fflib_IDGenerator.generate(CompanyCode__c.sObjectType),
                Country__c = 'RO'
            ),
            new CompanyCode__c(
                Id = fflib_IDGenerator.generate(CompanyCode__c.sObjectType),
                Country__c = 'AT'
            )
        };
        oMVEntityEmployeeList.add(
            new OMVEntityEmployee__c(
                Id = fflib_IDGenerator.generate(OMVEntityEmployee__c.sObjectType),
                EmployeeUser__c=fflib_IDGenerator.generate(User.sObjectType),
                OMVEntity__c=companyCodeList[0].Id
            )
        );
        List<Lead> leadList = new List<Lead>{
            new Lead(
                Id = fflib_IDGenerator.generate(Lead.sObjectType),
                CompanyCode__c = companyCodeList[0].Id,
                OwnerId=oMVEntityEmployeeList[0].EmployeeUser__c
            ),
            new Lead(
                Id = fflib_IDGenerator.generate(Lead.sObjectType),
                CompanyCode__c = companyCodeList[1].Id,
                OwnerId=fflib_IDGenerator.generate(User.sObjectType)
            ),
            new Lead(
                Id = fflib_IDGenerator.generate(Lead.sObjectType),
                OwnerId=fflib_IDGenerator.generate(User.sObjectType)
            ),
            new Lead(
                Id = fflib_IDGenerator.generate(Lead.sObjectType),
                OwnerId=fflib_IDGenerator.generate(Group.sObjectType)
            )       
        };

        leadList[0] = (Lead)fflib_ApexMocksUtils.setReadOnlyFields(
            leadList[0],
            Lead.class,
            new Map<SObjectField, Object> {Lead.RecordTypeId => DO_Lead.LEAD_RECORDTYPEID_CEPCARDS}
        );
        leadList[0] = (Lead)fflib_ApexMocksUtils.setReadOnlyFields(
            leadList[0],
            Lead.class,
            new Map<SObjectField, Object> {Lead.RecordTypeId => DO_Lead.LEAD_RECORDTYPEID_CEPCARDS}
        );

        Map<Id,Lead> oldLeadMap = new Map<Id,Lead>();
        oldLeadMap.put(leadList[0].Id, leadList[1]);
        oldLeadMap.put(leadList[1].Id, leadList[0]);
        oldLeadMap.put(leadList[2].Id, leadList[2]);
        oldLeadMap.put(leadList[3].Id, leadList[3]);

        mocks.startStubbing();
        mocks.when(companyCodeRepository.getCompanyCodeInfo((Set<Id>) fflib_match.anyObject())).thenReturn(companyCodeList);
        mocks.when(oMVEntityRepository.getCompanyCodeByUserID((Set<Id>) fflib_match.anyObject())).thenReturn(oMVEntityEmployeeList);
        mocks.stopStubbing();

        TW_Lead_FillComplementaryFields jobExecutionWorker = new TW_Lead_FillComplementaryFields();
        jobExecutionWorker = new TW_Lead_FillComplementaryFields(companyCodeRepository,oMVEntityRepository);
        
        jobExecutionWorker.execute(leadList, null);
        jobExecutionWorker.execute(leadList, oldLeadMap);

        ((IREP_CompanyCode)mocks.verify(companyCodeRepository, 2)).getCompanyCodeInfo((Set<Id>) fflib_match.anyObject());
        ((IREP_OMVEntityEmployee)mocks.verify(oMVEntityRepository, 2)).getCompanyCodeByUserID((Set<Id>) fflib_match.anyObject());
    }
}