force-app/main/default/objects/FPS_Bor_Workday__c/FPS_Bor_Workday__c.object-meta.xml
<CustomObject>
    <description>Borealis/FPS POC custom object</description>
    <label>Workday</label>
    <nameField>
        <displayFormat>WD - {00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workdays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FPS_Bor_Workday__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerCountry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPS_Bor_Workday__c/fields/Is_current_month__c.field-meta.xml
<CustomField>
    <fullName>Is_current_month__c</fullName>
    <formula>AND(TEXT(Month__c) = TEXT(MONTH(TODAY())), YEAR(Today()) = Year__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is current month?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Workday__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>03</fullName>
                <isActive>false</isActive>
                <label>03</label>
            </value>
            <value>
                <fullName>04</fullName>
                <isActive>false</isActive>
                <label>04</label>
            </value>
            <value>
                <fullName>05</fullName>
                <isActive>false</isActive>
                <label>05</label>
            </value>
            <value>
                <fullName>06</fullName>
                <isActive>false</isActive>
                <label>06</label>
            </value>
            <value>
                <fullName>07</fullName>
                <isActive>false</isActive>
                <label>07</label>
            </value>
            <value>
                <fullName>08</fullName>
                <isActive>false</isActive>
                <label>08</label>
            </value>
            <value>
                <fullName>09</fullName>
                <isActive>false</isActive>
                <label>09</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPS_Bor_Workday__c/fields/Number_of_working_days_current_month__c.field-meta.xml
<CustomField>
    <fullName>Number_of_working_days_current_month__c</fullName>
    <label>Number of working days current month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Workday__c/fields/Number_of_working_days_till_today__c.field-meta.xml
<CustomField>
    <fullName>Number_of_working_days_till_today__c</fullName>
    <label>Number of working days till today</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Workday__c/fields/Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Name__c</fullName>
    <externalId>true</externalId>
    <label>Unique Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/CustomerCountry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CZ</fullName>
        <label>Czech Republic</label>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
        <label>Hungary</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
        <label>Slovakia</label>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
        <label>Bulgaria</label>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
        <label>Austria</label>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
        <label>Moldova</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <label>Romania</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <label>Croatia</label>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
        <label>Bosnia</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Poland</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
        <label>Turkey</label>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
        <label>Russia</label>
    </customValue>
    <customValue>
        <fullName>SH</fullName>
        <label>Serbia</label>
    </customValue>
    <customValue>
        <fullName>SL</fullName>
        <label>Slovenia</label>
    </customValue>
    <customValue>
        <fullName>Hungarian</fullName>
        <isActive>false</isActive>
        <label>Hungarian</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
        <isActive>false</isActive>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>Slovak</fullName>
        <isActive>false</isActive>
        <label>Slovak</label>
    </customValue>
    <customValue>
        <fullName>Romanian</fullName>
        <isActive>false</isActive>
        <label>Romanian</label>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
        <isActive>false</isActive>
        <label>Bulgarian</label>
    </customValue>
    <customValue>
        <fullName>German</fullName>
        <isActive>false</isActive>
        <label>German</label>
    </customValue>
    <description>Global value set to store working languages for OMV CEP business lines. Available languages should match the activated languages in the Translation Language Settings.</description>
    <masterLabel>Customer Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UpdateWorkdayRecords.cls
/**
 * Created by mateuszbednarek on 11/02/2021.
 * Edit by Joana Neto (Capgemini) on 01/06/2021 with custom object API name change
 */

public with sharing class UpdateWorkdayRecords {

    static List<FPS_Bor_Workday__c> workdaysToUpsert = new List<FPS_Bor_Workday__c>();
    static Map<String, FPS_Bor_Workday__c> uniqueNameToWorkday = getExistingWorkdays();

    public static void updateWorkdayRecords(){
        ExceptionHandler.errorLogList.clear();

        for(String code: Util.countryNameToCode.values()){
            FPS_Bor_Workday__c wd = createBaseRecord(code);
            getWorkingDaysForAMonth(wd);
            getWorkingDaysUntilToday(wd);
            if(wd.Number_of_working_days_current_month__c != null){
                workdaysToUpsert.add(wd);
            }
        }

        finish();
    }

    private static void finish(){
        upsert workdaysToUpsert Unique_Name__c;
        insertErrorLogs();
        Database.executeBatch(new UpdateServiceContractWorkingDayBatch(), 200);
    }

    private static void insertErrorLogs(){
        if(!ExceptionHandler.errorLogList.isEmpty()){
            insert ExceptionHandler.errorLogList;
        }
    }

    private static FPS_Bor_Workday__c createBaseRecord(String code){
        FPS_Bor_Workday__c wd = new FPS_Bor_Workday__c();
        wd.Country__c = code;
        wd.Month__c = String.valueOf(Date.today().month());
        wd.Year__c = Date.today().year();
        wd.Unique_Name__c = wd.Country__c+'_'+wd.Month__c+'_'+wd.Year__c;
        return wd;
    }

    private static void getWorkingDaysForAMonth(FPS_Bor_Workday__c wd){
        if(uniqueNameToWorkday.containsKey(wd.Unique_Name__c)){
            wd.Number_of_working_days_current_month__c = uniqueNameToWorkday.get(wd.Unique_Name__c)
                    .Number_of_working_days_current_month__c;
        }else{
            HolidayAPIRestCallout api = new HolidayAPIRestCallout(wd.Country__c);
            wd.Number_of_working_days_current_month__c = api.getNumberOfWorkingDays();
        }
    }

    private static void getWorkingDaysUntilToday(FPS_Bor_Workday__c wd){
        HolidayAPIRestCallout api = new HolidayAPIRestCallout(wd.Country__c, Date.today());
        wd.Number_of_working_days_till_today__c = api.getNumberOfWorkingDays();
    }

    private static Map<String, FPS_Bor_Workday__c> getExistingWorkdays(){
        Map<String, FPS_Bor_Workday__c> uniqueNameToWorkday = new Map<String, FPS_Bor_Workday__c>();
        for(FPS_Bor_Workday__c wd: [SELECT Id, Number_of_working_days_current_month__c,Unique_Name__c FROM FPS_Bor_Workday__c WHERE
                Is_current_month__c = TRUE]){
            uniqueNameToWorkday.put(wd.Unique_Name__c, wd);
        }
        return uniqueNameToWorkday;
    }
}