force-app/main/default/objects/FPS_Bor_Workday__c/FPS_Bor_Workday__c.object-meta.xml
<CustomObject>
    <description>Borealis/FPS POC custom object</description>
    <label>Workday</label>
    <nameField>
        <displayFormat>WD - {00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workdays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FPS_Bor_Workday__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerCountry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPS_Bor_Workday__c/fields/Is_current_month__c.field-meta.xml
<CustomField>
    <fullName>Is_current_month__c</fullName>
    <formula>AND(TEXT(Month__c) = TEXT(MONTH(TODAY())), YEAR(Today()) = Year__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is current month?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Workday__c/fields/Number_of_working_days_current_month__c.field-meta.xml
<CustomField>
    <fullName>Number_of_working_days_current_month__c</fullName>
    <label>Number of working days current month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Workday__c/fields/Number_of_working_days_till_today__c.field-meta.xml
<CustomField>
    <fullName>Number_of_working_days_till_today__c</fullName>
    <label>Number of working days till today</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Is_current_month__c.field-meta.xml
<CustomField>
    <fullName>Is_current_month__c</fullName>
    <formula>AND(MONTH(Posting_Period__c) = MONTH(TODAY()), YEAR(Posting_Period__c) = YEAR(TODAY()))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is current month?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Work_Days_Excl_Holiday_This_Month__c.field-meta.xml
<CustomField>
    <fullName>Work_Days_Excl_Holiday_This_Month__c</fullName>
    <label>Work Days Excl Holiday This Month</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Work_Days_Excl_Holiday_Till_Today__c.field-meta.xml
<CustomField>
    <fullName>Work_Days_Excl_Holiday_Till_Today__c</fullName>
    <label>Work Days Excl Holiday Till Today</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/CustomerCountry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CZ</fullName>
        <label>Czech Republic</label>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
        <label>Hungary</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
        <label>Slovakia</label>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
        <label>Bulgaria</label>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
        <label>Austria</label>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
        <label>Moldova</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <label>Romania</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <label>Croatia</label>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
        <label>Bosnia</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Poland</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
        <label>Turkey</label>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
        <label>Russia</label>
    </customValue>
    <customValue>
        <fullName>SH</fullName>
        <label>Serbia</label>
    </customValue>
    <customValue>
        <fullName>SL</fullName>
        <label>Slovenia</label>
    </customValue>
    <customValue>
        <fullName>Hungarian</fullName>
        <isActive>false</isActive>
        <label>Hungarian</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
        <isActive>false</isActive>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>Slovak</fullName>
        <isActive>false</isActive>
        <label>Slovak</label>
    </customValue>
    <customValue>
        <fullName>Romanian</fullName>
        <isActive>false</isActive>
        <label>Romanian</label>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
        <isActive>false</isActive>
        <label>Bulgarian</label>
    </customValue>
    <customValue>
        <fullName>German</fullName>
        <isActive>false</isActive>
        <label>German</label>
    </customValue>
    <description>Global value set to store working languages for OMV CEP business lines. Available languages should match the activated languages in the Translation Language Settings.</description>
    <masterLabel>Customer Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UpdateServiceContractWorkingDays.cls
/**
 * Created by mateuszbednarek on 11/02/2021.
 * Edit by Joana Neto (Capgemini) on 01/06/2021 with custom object API name change
 */

public with sharing class UpdateServiceContractWorkingDays {

    Map<String, List<ServiceContract>> childrenContractsByCountry;
    Map<String, FPS_Bor_Workday__c> workdaysGroupedByCountries = groupWorkdays();

    private void groupServiceContracts(List<ServiceContract> scope) {
        Map<String, List<ServiceContract>> countryToContract = new Map<String, List<ServiceContract>>();

        for(ServiceContract contract: scope){

            if(countryToContract.containsKey(contract.ParentServiceContract.Account.BillingCountry)){
                countryToContract.get(contract.ParentServiceContract.Account.BillingCountry).add(contract);
            }else{
                countryToContract.put(contract.ParentServiceContract.Account.BillingCountry, new List<ServiceContract>{contract});
            }
        }

        childrenContractsByCountry = countryToContract;
    }

    private Map<String,FPS_Bor_Workday__c> groupWorkdays() {
        Map<String, FPS_Bor_Workday__c> countryToWorkday = new Map<String, FPS_Bor_Workday__c>();

        for(FPS_Bor_Workday__c wd: [SELECT Id, Number_of_working_days_current_month__c, Number_of_working_days_till_today__c,
                Country__c
        FROM FPS_Bor_Workday__c WHERE Is_current_month__c = TRUE]){
            countryToWorkday.put(wd.Country__c, wd);
        }

        return countryToWorkday;
    }

    public void updateServiceContracts(List<ServiceContract> scope){
        List<ServiceContract> toUpdate = new List<ServiceContract>();
        groupServiceContracts(scope);

        for(String country: childrenContractsByCountry.keySet()){
            for(ServiceContract contract : childrenContractsByCountry.get(country)){
                contract.Work_Days_Excl_Holiday_This_Month__c = workdaysGroupedByCountries.get(Util.countryNameToCode
                        .get(country)).Number_of_working_days_current_month__c;
                contract.Work_Days_Excl_Holiday_Till_Today__c = workdaysGroupedByCountries.get(Util.countryNameToCode
                        .get(country)).Number_of_working_days_till_today__c;

                toUpdate.add(contract);
            }
        }

        update toUpdate;
    }
}