force-app/main/default/objects/Case/fields/Case_Language__c.field-meta.xml
<CustomField>
    <fullName>Case_Language__c</fullName>
    <description>Case Languages picklist</description>
    <label>Inbox Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerLanguage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer - Representative</fullName>
            </value>
            <value>
                <fullName>Customer - Driver</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Filling Station</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Customer - Driver Internal</fullName>
                <isActive>false</isActive>
                <label>Customer - Driver Internal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case Support Process</businessProcess>
    <label>CEP Cards Case</label>
</RecordType>

force-app/main/default/objects/EmailMessage/fields/parentCase__c.field-meta.xml
<CustomField>
    <fullName>parentCase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Email Messages</relationshipLabel>
    <relationshipName>Email_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InboxLanguage__mdt/InboxLanguage__mdt.object-meta.xml
<CustomObject>
    <description>This metadata shows for each inbox that is configured as an email to case the correspondent language that will be the default one used in the automatic email communications</description>
    <label>Inbox Language</label>
    <pluralLabel>Inbox Languages</pluralLabel>
</CustomObject>

force-app/main/default/objects/InboxLanguage__mdt/fields/InboxAddress__c.field-meta.xml
<CustomField>
    <fullName>InboxAddress__c</fullName>
    <description>field to store the address of each inbox</description>
    <label>Inbox Address</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InboxLanguage__mdt/fields/LanguageCode__c.field-meta.xml
<CustomField>
    <fullName>LanguageCode__c</fullName>
    <label>Language code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/CustomerLanguage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BG</fullName>
        <label>Bulgarian</label>
    </customValue>
    <customValue>
        <fullName>CS</fullName>
        <label>Czech</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <label>German</label>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
        <label>Hungarian</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <label>Romanian</label>
    </customValue>
    <customValue>
        <fullName>SR</fullName>
        <label>Serbian</label>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
        <label>Slovak</label>
    </customValue>
    <customValue>
        <fullName>SL</fullName>
        <label>Slovenian</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <label>Croatian</label>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
        <label>Bosnian</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Polish</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italian</label>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
        <label>Turkish</label>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
        <label>Russian</label>
    </customValue>
    <customValue>
        <fullName>ro_MD</fullName>
        <label>Moldovan</label>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
        <isActive>false</isActive>
        <label>Moldova</label>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
        <isActive>false</isActive>
        <label>Austria</label>
    </customValue>
    <masterLabel>Customer Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TW_EmailMessage_CheckCaseEmails.cls
/**
@description    worker class to notify when a closed case receives an email
@testClass      TW_EmailMessage_CheckCaseEmailsTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description  
* Guilherme Charro                07/07/2021          Created the class
* Guilherme Charro                22/09/2021          added logic to update Case Language according to the inbox (US 32695)
* ------------------------------------------------------------------------------------        
*/
public with sharing class TW_EmailMessage_CheckCaseEmails {
    private IREP_Case caseRepository;
    private ISL_ChatterNotifications emailMessageChatterNotifications;
    private IREP_EmailMessage emailMessageRepository;
    
    public TW_EmailMessage_CheckCaseEmails(){
        this.emailMessageChatterNotifications = new SL_ChatterNotifications();
        this.caseRepository = new REP_Case();
        this.emailMessageRepository = new REP_EmailMessage();
    }
    
    @TestVisible
    private TW_EmailMessage_CheckCaseEmails(ISL_ChatterNotifications emailMessageChatterNotifications, IREP_Case caseRepository, IREP_EmailMessage emailMessageRepository){
        this.emailMessageChatterNotifications = emailMessageChatterNotifications;
        this.caseRepository = caseRepository;
        this.emailMessageRepository = emailMessageRepository;
    }

    public void execute(List<EmailMessage> emailMessageList) {
        
        Set<Id> caseIds = new Set<Id>();
        List<Id> emailMessagesIdList = new List<Id>();
        for (EmailMessage emailReceived : emailMessageList) {
            if (emailReceived.Incoming && !String.isBlank(emailReceived.RelatedToId) && Schema.Case.SObjectType == emailReceived.RelatedToId.getSobjectType()){
                caseIds.add(emailReceived.RelatedToId);
                emailMessagesIdList.add( emailReceived.Id );
            }else if (!String.isBlank(emailReceived.RelatedToId) && Schema.Case.SObjectType == emailReceived.RelatedToId.getSobjectType()) {
                emailMessagesIdList.add( emailReceived.Id );
            }
        }
        List<Case> casesInfoList = new List<Case>();
        List<Case> casesToUpdate = new List<Case>();

        if (!caseIds.isEmpty()) {
            casesInfoList = caseRepository.getCasesById(caseIds);
        }

        Map<String, InboxLanguage__mdt> inboxLanguagesMap = new Map<String, InboxLanguage__mdt>();
        for( InboxLanguage__mdt mdtLanguage : InboxLanguage__mdt.getAll().values() ){
            inboxLanguagesMap.put(mdtLanguage.InboxAddress__c, mdtLanguage);
        }

        for (Case caseInfo : casesInfoList) {
            if (caseInfo.IsClosed) {
                SL_ChatterNotifications emailMessageChatterNotificationPost = new SL_ChatterNotifications.chatterBuilder()
                .setPosText(' '+System.Label.EmailMessageCaseClosedTrigger1+' '+caseInfo.CaseNumber+'. '+System.Label.EmailMessageCaseClosedTrigger2)
                .setMentionIds(new List<String>{caseInfo.OwnerId})
                .setSubjectId(caseInfo.Id)
                .build();

                emailMessageChatterNotifications.addFeedItemInputList( emailMessageChatterNotificationPost.getFeedItemInputList() );
            }else if (caseInfo.Status == DO_Case.CASE_STATUS_RESOLUTIONCUSTOMER) {
                if (!String.isBlank(caseInfo.Source__c)) {
                    caseInfo.Status = DO_Case.CASE_STATUS_CUSTOMERFEEDBACK;
                    casesToUpdate.add(caseInfo);
                }

                SL_ChatterNotifications emailMessageChatterNotificationPost = new SL_ChatterNotifications.chatterBuilder()
                .setPosText(' '+System.Label.EmailMessageCaseClosedTrigger1+' '+caseInfo.CaseNumber+'. '+System.Label.EmailMessageCaseTrigger3)
                .setMentionIds(new List<String>{caseInfo.OwnerId})
                .setSubjectId(caseInfo.Id)
                .build();

                emailMessageChatterNotifications.addFeedItemInputList( emailMessageChatterNotificationPost.getFeedItemInputList() );
            }else if(caseInfo.Status != DO_Case.CASE_STATUS_NEW){
                if (!String.isBlank(caseInfo.Source__c)) {
                    caseInfo.Status = DO_Case.CASE_STATUS_INFORMATIONRECEIVED;
                    casesToUpdate.add(caseInfo);
                }

                SL_ChatterNotifications emailMessageChatterNotificationPost = new SL_ChatterNotifications.chatterBuilder()
                .setPosText(' '+System.Label.EmailMessageCaseClosedTrigger1+' '+caseInfo.CaseNumber+'. '+System.Label.EmailMessageCaseTrigger4)
                .setMentionIds(new List<String>{caseInfo.OwnerId})
                .setSubjectId(caseInfo.Id)
                .build();

                emailMessageChatterNotifications.addFeedItemInputList( emailMessageChatterNotificationPost.getFeedItemInputList() );
            }else if (caseInfo.Status == DO_Case.CASE_STATUS_NEW && (String.isBlank(caseInfo.AccountId) || caseInfo.AccountId == null)) {
                for (EmailMessage emailReceived : emailMessageList) {
                    if (emailReceived.RelatedToId == caseInfo.Id) {
                    	if (inboxLanguagesMap.containsKey( emailReceived.ToAddress )) {
                        	caseInfo.Case_Language__c = inboxLanguagesMap.get( emailReceived.ToAddress ).LanguageCode__c;
                            casesToUpdate.add(caseInfo);
                            break;
                        }    
                    }
                }
            }
        }

        if (!emailMessagesIdList.isEmpty()) {
            // emailMessageRepository.updateSObjects(emailsToUpdateList);
            async_updateEmailMessage( emailMessagesIdList );
            emailMessageChatterNotifications.persistChatterPosts();  
        }

        if (!casesToUpdate.isEmpty()) {
            caseRepository.updateSObjects(casesToUpdate);
        }
    }

    @testVisible
    @future
    private static void async_updateEmailMessage(List<Id> emailMessagesIdList){

        IREP_EmailMessage emailMessageRepository = new REP_EmailMessage();
        List<EmailMessage> emailMessagesToUpdateList = emailMessageRepository.getEmailMessagesById( emailMessagesIdList );
        for( EmailMessage emailRecord : emailMessagesToUpdateList ){

            emailRecord.parentCase__c = emailRecord.relatedToId;
            
        }

        if( !emailMessagesToUpdateList.isEmpty() ){
            emailMessageRepository.updateSObjects(emailMessagesToUpdateList);
        }
    }
}