force-app/main/default/objects/Case/fields/CategoryT1__c.field-meta.xml
<CustomField>
    <fullName>CategoryT1__c</fullName>
    <description>Field to register the T1 category of the Case</description>
    <label>Category T1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Credit Management</fullName>
            </value>
            <value>
                <fullName>Customer invoicing</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Vouchers</fullName>
            </value>
            <value>
                <fullName>VAS</fullName>
            </value>
            <value>
                <fullName>FS acceptance support</fullName>
            </value>
            <value>
                <fullName>FS operation</fullName>
            </value>
            <value>
                <fullName>Fleet Online</fullName>
            </value>
            <value>
                <fullName>Contracting process</fullName>
            </value>
            <value>
                <fullName>Request for offer</fullName>
            </value>
            <value>
                <fullName>Authority request</fullName>
            </value>
            <value>
                <fullName>Spam</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Petrom CC (RO)</fullName>
            </value>
            <value>
                <fullName>Fuel quality</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Behavior</fullName>
            </value>
            <value>
                <fullName>Case Category 1</fullName>
                <isActive>false</isActive>
                <label>Case Category 1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer - Representative</fullName>
            </value>
            <value>
                <fullName>Customer - Driver</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Filling Station</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Customer - Driver Internal</fullName>
                <isActive>false</isActive>
                <label>Customer - Driver Internal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case Support Process</businessProcess>
    <label>CEP Cards Case</label>
</RecordType>

force-app/main/default/classes/TW_Case_CloseChildCasesTest.cls
/**
@author Guilherme Charro 
@date   16/06/2021
@description Test class for TW_Case_CloseChildCases
@TestClass         
Modification Log:
----------------------------------------------------------------------------------------------------
Developer                       Date                Description                           Coverage
----------------------------------------------------------------------------------------------------
Guilherme Charro              16/06/2021          Original Version                         unknown
Hugo Rodrigues                15/09/2021            updated class                           97
*/
@isTest
public class TW_Case_CloseChildCasesTest {
    static fflib_ApexMocks mocks = new fflib_ApexMocks();

    @isTest
    private static void CaseCloseChildCasesTest(){
        IREP_Case caseRepository = (REP_Case)mocks.mock(REP_Case.class);
        ISL_ChatterNotifications caseChatterNotification = (SL_ChatterNotifications)mocks.mock(SL_ChatterNotifications.class);
        User testUser = new User(Id = fflib_IDGenerator.generate(User.sObjectType));
        List<Case> listCase = new List<Case>();
        List<Case> listCaseFinal = new List<Case>();
        Set<ID> caseIDSet = new Set<Id>();
        listCase.add(
            new Case(
                Id = fflib_IDGenerator.generate(Case.sObjectType),
                Status = DO_Case.CASE_STATUS_CLOSED,
                OwnerId = testUser.Id,
                Source__c = Do_Case.CASE_SOURCE_OTHER,
                CategoryT1__c = Do_Case.CASE_CATEGORY1_SPAM,
                RecordTypeID= Do_Case.CASE_RECORDTYPEID_CASE
            )  
        );
        listCase.add(
            new Case(
                Id = fflib_IDGenerator.generate(Case.sObjectType),
                Status = DO_Case.CASE_STATUS_COMPLETED,
                OwnerId = testUser.Id,
                Source__c = Do_Case.CASE_SOURCE_OTHER,
                CategoryT1__c = Do_Case.CASE_CATEGORY1_SPAM,
                RecordTypeID= Do_Case.CASE_RECORDTYPEID_CLAIM
            )  
        );
        
        listCase[0] = (Case)fflib_ApexMocksUtils.setReadOnlyFields(
            listCase[0],
            Case.class,
            new Map<SObjectField, Object> {Case.IsClosed => true}
        );
        listCase[1] = (Case)fflib_ApexMocksUtils.setReadOnlyFields(
            listCase[1],
            Case.class,
            new Map<SObjectField, Object> {Case.IsClosed => true}
        );
        
        Map<Id, Case> mapOldCases = new Map<Id, Case>();
        mapOldCases.put(listCase[0].Id, new Case(
            Id = fflib_IDGenerator.generate(Case.sObjectType),
            Status = Do_Case.CASE_STATUS_NEW,
            RecordTypeID= Do_Case.CASE_RECORDTYPEID_CASE
        ));
        mapOldCases.put(listCase[1].Id, new Case(
            Id = fflib_IDGenerator.generate(Case.sObjectType),
            Status = Do_Case.CASE_STATUS_NEW,
            RecordTypeID= Do_Case.CASE_RECORDTYPEID_CASE
        ));
        
        User runningUser = new User(Id = fflib_IDGenerator.generate(User.sObjectType));
        
        List<Case> listChildCases = new List<Case>();
        listChildCases.add(
            new Case(
                Id = fflib_IDGenerator.generate(Case.sObjectType),
                ParentId = listCase[0].Id,
                Parent= listCase[0],
                OwnerId = runningUser.Id,
                Source__c = Do_Case.CASE_SOURCE_OTHER,
                CategoryT1__c = Do_Case.CASE_CATEGORY1_SPAM,
                RecordTypeID= Do_Case.CASE_RECORDTYPEID_CASE
            )  
        );
        listChildCases.add(
            new Case(
                Id = fflib_IDGenerator.generate(Case.sObjectType),
                ParentId = listCase[1].Id,
                Parent= listCase[1],
                OwnerId = runningUser.Id,
                Source__c = Do_Case.CASE_SOURCE_OTHER,
                CategoryT1__c = Do_Case.CASE_CATEGORY1_SPAM,
                RecordTypeID= Do_Case.CASE_RECORDTYPEID_CLAIM
            )  
        );

        listCaseFinal.add(new Case(
            Id = listCase[0].Id,
            Status = DO_Case.CASE_STATUS_CLOSED,
            OwnerId = testUser.Id,
            Source__c = Do_Case.CASE_SOURCE_OTHER,
            CategoryT1__c = Do_Case.CASE_CATEGORY1_SPAM,
            RecordTypeID= Do_Case.CASE_RECORDTYPEID_CASE
            )  
        );
        listCaseFinal.add(new Case(
            Id = listCase[1].Id,
            Status = DO_Case.CASE_STATUS_COMPLETED,
            OwnerId = testUser.Id,
            Source__c = Do_Case.CASE_SOURCE_OTHER,
            CategoryT1__c = Do_Case.CASE_CATEGORY1_SPAM,
            RecordTypeID= Do_Case.CASE_RECORDTYPEID_CLAIM
            )  
        );
        listCaseFinal[0] = (Case)fflib_ApexMocksUtils.setReadOnlyFields(
            listCaseFinal[0],
            Case.class,
            new Map<SObjectField, Object> {Case.IsClosed => true}
        );
        listCaseFinal[1] = (Case)fflib_ApexMocksUtils.setReadOnlyFields(
            listCaseFinal[1],
            Case.class,
            new Map<SObjectField, Object> {Case.IsClosed => true}
        );
        caseIDSet.add(listCaseFinal[0].Id);
        caseIDSet.add(listCaseFinal[1].Id);
        mocks.startStubbing();
        mocks.when(caseRepository.getChildCases((Set<Id>) fflib_match.anyObject())).thenReturn(listCase);
        mocks.when(caseRepository.updateSObjects(listCase)).thenReturn(new List<Database.SaveResult>());
        ((ISL_ChatterNotifications) mocks.doAnswer( new VoidAnswer(),caseChatterNotification)).persistChatterPosts();
        mocks.stopStubbing();
        
        TW_Case_CloseChildCases jobExecutionWorker = new TW_Case_CloseChildCases();
        jobExecutionWorker = new TW_Case_CloseChildCases(caseRepository, caseChatterNotification);
        
        jobExecutionWorker.execute(listCase, mapOldCases);
        
        ((IREP_Case)mocks.verify(caseRepository, 1)).getChildCases((Set<Id>) fflib_match.eq(caseIDSet));
        ((IREP_Case)mocks.verify(caseRepository, 1)).updateSObjects((List<Case>)fflib_match.eq(listCaseFinal));

    }

    class VoidAnswer implements fflib_Answer {
        public Object answer (fflib_InvocationOnMock invocation) {
            return null;
        }
    }
}