force-app/main/default/objects/Case/fields/CategoryT1__c.field-meta.xml
<CustomField>
    <fullName>CategoryT1__c</fullName>
    <description>Field to register the T1 category of the Case</description>
    <label>Category T1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card</fullName>
            </value>
            <value>
                <fullName>Credit Management</fullName>
            </value>
            <value>
                <fullName>Customer invoicing</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Vouchers</fullName>
            </value>
            <value>
                <fullName>VAS</fullName>
            </value>
            <value>
                <fullName>FS acceptance support</fullName>
            </value>
            <value>
                <fullName>FS operation</fullName>
            </value>
            <value>
                <fullName>Fleet Online</fullName>
            </value>
            <value>
                <fullName>Contracting process</fullName>
            </value>
            <value>
                <fullName>Request for offer</fullName>
            </value>
            <value>
                <fullName>Authority request</fullName>
            </value>
            <value>
                <fullName>Spam</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Petrom CC (RO)</fullName>
            </value>
            <value>
                <fullName>Fuel quality</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Behavior</fullName>
            </value>
            <value>
                <fullName>Case Category 1</fullName>
                <isActive>false</isActive>
                <label>Case Category 1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CategoryT2__c.field-meta.xml
<CustomField>
    <fullName>CategoryT2__c</fullName>
    <description>Field to define the T2 Category of the Case</description>
    <label>Category T2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CategoryT1__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card support</fullName>
            </value>
            <value>
                <fullName>Card operation</fullName>
            </value>
            <value>
                <fullName>Credit management support</fullName>
            </value>
            <value>
                <fullName>Credit management operation</fullName>
            </value>
            <value>
                <fullName>Invoicing support</fullName>
            </value>
            <value>
                <fullName>Invoicing operation</fullName>
            </value>
            <value>
                <fullName>Customer data and Conditions (New customer)</fullName>
            </value>
            <value>
                <fullName>Master-data operation (Existing customer)</fullName>
            </value>
            <value>
                <fullName>DocuSign</fullName>
            </value>
            <value>
                <fullName>Systems operation</fullName>
            </value>
            <value>
                <fullName>Voucher general support</fullName>
            </value>
            <value>
                <fullName>Voucher order support</fullName>
            </value>
            <value>
                <fullName>Voucher order creation</fullName>
            </value>
            <value>
                <fullName>Voucher general operation</fullName>
            </value>
            <value>
                <fullName>Toll support</fullName>
            </value>
            <value>
                <fullName>Toll operation</fullName>
            </value>
            <value>
                <fullName>VAT refund</fullName>
            </value>
            <value>
                <fullName>CO2</fullName>
            </value>
            <value>
                <fullName>FS details &amp; network</fullName>
            </value>
            <value>
                <fullName>Technical Problems</fullName>
            </value>
            <value>
                <fullName>Card User Problems</fullName>
            </value>
            <value>
                <fullName>FS status</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>FS requests</fullName>
            </value>
            <value>
                <fullName>FOS support</fullName>
            </value>
            <value>
                <fullName>FOS account</fullName>
            </value>
            <value>
                <fullName>FOS operation</fullName>
            </value>
            <value>
                <fullName>New Contract (New Customer)</fullName>
            </value>
            <value>
                <fullName>Contract Amendment</fullName>
            </value>
            <value>
                <fullName>Announcement of Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CategoryT3__c.field-meta.xml
<CustomField>
    <fullName>CategoryT3__c</fullName>
    <description>Field to define the T3 Category of the Case</description>
    <label>Category T3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CategoryT2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Card status</fullName>
            </value>
            <value>
                <fullName>Order support</fullName>
            </value>
            <value>
                <fullName>Card Limit availability</fullName>
            </value>
            <value>
                <fullName>PIN support</fullName>
            </value>
            <value>
                <fullName>Acceptance/Usage questions</fullName>
            </value>
            <value>
                <fullName>Card delivery status</fullName>
            </value>
            <value>
                <fullName>Lock/Unlock</fullName>
            </value>
            <value>
                <fullName>Card activation</fullName>
            </value>
            <value>
                <fullName>Card fees</fullName>
            </value>
            <value>
                <fullName>Cost center</fullName>
            </value>
            <value>
                <fullName>CCTV registration</fullName>
            </value>
            <value>
                <fullName>Other card support</fullName>
            </value>
            <value>
                <fullName>PIN reset</fullName>
            </value>
            <value>
                <fullName>Lock</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Change card limit</fullName>
            </value>
            <value>
                <fullName>PUK request</fullName>
            </value>
            <value>
                <fullName>PIN change</fullName>
            </value>
            <value>
                <fullName>Unlock</fullName>
            </value>
            <value>
                <fullName>Card replacement</fullName>
            </value>
            <value>
                <fullName>Reports</fullName>
            </value>
            <value>
                <fullName>Toll activation/deactivation</fullName>
            </value>
            <value>
                <fullName>Vehicle/Cost center change</fullName>
            </value>
            <value>
                <fullName>CCTV registration (RO)</fullName>
            </value>
            <value>
                <fullName>Credit limit details</fullName>
            </value>
            <value>
                <fullName>Payment details</fullName>
            </value>
            <value>
                <fullName>Customer block information</fullName>
            </value>
            <value>
                <fullName>Other credit management support</fullName>
            </value>
            <value>
                <fullName>Change account limit</fullName>
            </value>
            <value>
                <fullName>MEX update/uplift</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer - Representative</fullName>
            </value>
            <value>
                <fullName>Customer - Driver</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Filling Station</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Customer - Driver Internal</fullName>
                <isActive>false</isActive>
                <label>Customer - Driver Internal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case Support Process</businessProcess>
    <label>CEP Cards Case</label>
</RecordType>

force-app/main/default/classes/TW_Case_CloseChildCases.cls
/**
@description    worker class to copy default parameter to the job execution record
@testClass      TW_Case_CloseChildCasesTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description  
* Guilherme Charro                26/05/2021          Created the class
* Hugo Rodrigues                  15/09/2021            updated class
* ------------------------------------------------------------------------------------        
*/
public class TW_Case_CloseChildCases {
    
    private IREP_Case caseRepository;
    private ISL_ChatterNotifications caseChatterNotifications;
    
    public TW_Case_CloseChildCases(){
        this.caseRepository = new REP_Case();
        this.caseChatterNotifications = new SL_ChatterNotifications();
    }
    
    @TestVisible
    private TW_Case_CloseChildCases(IREP_Case caseRepository, ISL_ChatterNotifications caseChatterNotifications){
        this.caseRepository = caseRepository;
        this.caseChatterNotifications = caseChatterNotifications;
    }
    
    public void execute(List<Case> caseList, Map<Id,Case> oldCaseMap) {
        Map<Id,Case> casesClosedMap = new Map<Id,Case>();
        Set<Id> closedCasesIdSet = new Set<Id>();
        ID caseRecordTypeCase = DO_Case.CASE_RECORDTYPEID_CASE;
        ID caseRecordTypeClaim = DO_Case.CASE_RECORDTYPEID_CLAIM;
        ID caseRecordTypeComplaint = DO_Case.CASE_RECORDTYPEID_COMPLAINT;
        for(Case caseUpdated : caseList){
            if(caseUpdated.Status != oldCaseMap.get(caseUpdated.Id).Status && caseUpdated.IsClosed == true){
                closedCasesIdSet.add(caseUpdated.Id);
                casesClosedMap.put(caseUpdated.Id, caseUpdated);
            }
        }
        if(!closedCasesIdSet.isEmpty()){
            List<Case> casesToUpdateList = caseRepository.getChildCases(closedCasesIdSet);
            
            for(Case caseToClose: casesToUpdateList){
            
                if (String.isBlank(caseToClose.Source__c) || String.isBlank(caseToClose.CategoryT1__c) || 
                (caseToClose.CategoryT1__c != DO_Case.CASE_CATEGORY1_SPAM && (String.isBlank(caseToClose.CategoryT2__c) || String.isBlank(caseToClose.CategoryT3__c)))) {
                    casesClosedMap.get(caseToClose.ParentId).addError(Label.CloseChildCasesTriggerErrorMessage);
                }else{
                    if (caseToClose.RecordTypeID == caseRecordTypeCase) {
                        caseToClose.Status = DO_Case.CASE_STATUS_CLOSED;
                    }else if (caseToClose.RecordTypeID== caseRecordTypeClaim || caseToClose.RecordTypeID == caseRecordTypeComplaint) {
                        caseToClose.Status = DO_Case.CASE_STATUS_COMPLETED;
                    }
                    
                    if(caseToClose.Parent.OwnerId != caseToClose.OwnerId){
                        //validar traduções
                        SL_ChatterNotifications caseChatterNotificationPost = new SL_ChatterNotifications.chatterBuilder()
                        .setPreText(System.Label.CloseCaseText + ' ')
                        .setPosText(System.Label.CloseCaseText2 + ' ' + caseToClose.CaseNumber +System.Label.CloseCaseText3 + ' ' + caseToClose.Parent.CaseNumber + ' ' + System.Label.CloseCaseText4 + ' ' +caseToClose.Parent.Owner.Name)
                        .setMentionIds(new List<String>{caseToClose.OwnerId})
                        .setSubjectId(caseToClose.Id)
                        .build();
    
                        caseChatterNotifications.addFeedItemInputList( caseChatterNotificationPost.getFeedItemInputList() );
                    }
                }   
            } 
         
            if(!casesToUpdateList.isEmpty()){
                caseRepository.updateSObjects(casesToUpdateList);
                caseChatterNotifications.persistChatterPosts();            
            }
        }
    }
}