force-app/main/default/objects/Case/fields/CompanyCodeCountry__c.field-meta.xml
<CustomField>
    <fullName>CompanyCodeCountry__c</fullName>
    <description>field used for sharing rules</description>
    <label>Company Code Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerCountry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case Support Process</businessProcess>
    <label>CEP Cards Case</label>
</RecordType>

force-app/main/default/objects/PrivacyPolicyCountry__mdt/PrivacyPolicyCountry__mdt.object-meta.xml
<CustomObject>
    <description>Configuration of Privacy Policy on per country basis with title text and body text on native language and translation to international English language.</description>
    <label>Privacy Policy Country</label>
    <pluralLabel>Privacy Policy Countries</pluralLabel>
</CustomObject>

force-app/main/default/objects/PrivacyPolicyCountry__mdt/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PrivacyPolicyCountry__mdt/fields/Body_English__c.field-meta.xml
<CustomField>
    <fullName>Body_English__c</fullName>
    <label>Body_English</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PrivacyPolicyCountry__mdt/fields/CountryIsoCode__c.field-meta.xml
<CustomField>
    <fullName>CountryIsoCode__c</fullName>
    <label>Country Iso Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrivacyPolicyCountry__mdt/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <label>Time Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrivacyPolicyCountry__mdt/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PrivacyPolicyCountry__mdt/fields/Title_English__c.field-meta.xml
<CustomField>
    <fullName>Title_English__c</fullName>
    <label>Title_English</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/CustomerCountry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CZ</fullName>
        <label>Czech Republic</label>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
        <label>Hungary</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
        <label>Slovakia</label>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
        <label>Bulgaria</label>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
        <label>Austria</label>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
        <label>Moldova</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <label>Romania</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <label>Croatia</label>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
        <label>Bosnia</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Poland</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
        <label>Turkey</label>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
        <label>Russia</label>
    </customValue>
    <customValue>
        <fullName>SH</fullName>
        <label>Serbia</label>
    </customValue>
    <customValue>
        <fullName>SL</fullName>
        <label>Slovenia</label>
    </customValue>
    <customValue>
        <fullName>Hungarian</fullName>
        <isActive>false</isActive>
        <label>Hungarian</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
        <isActive>false</isActive>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>Slovak</fullName>
        <isActive>false</isActive>
        <label>Slovak</label>
    </customValue>
    <customValue>
        <fullName>Romanian</fullName>
        <isActive>false</isActive>
        <label>Romanian</label>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
        <isActive>false</isActive>
        <label>Bulgarian</label>
    </customValue>
    <customValue>
        <fullName>German</fullName>
        <isActive>false</isActive>
        <label>German</label>
    </customValue>
    <description>Global value set to store working languages for OMV CEP business lines. Available languages should match the activated languages in the Translation Language Settings.</description>
    <masterLabel>Customer Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/communityPrivacyPolicyController.cls
/**
* @description   Apex controller of the lwc communityPrivacyPolicy
* @testClass     communityPrivacyPolicyController
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Carolina Resende             22/09/2021           Created Class
* António Santos               28/09/2021           Improvements
* ------------------------------------------------------------------------------------ 
*/
public with sharing class communityPrivacyPolicyController {
    private static final String DEFAULT_COUNTRY_CODE = 'EN';    // English

    private static final String DEFAULT_TIMEZONE_KEY = 'DEFAULT';

    static Map<String,String> timeZoneCountryMap;
    static Map<String,PrivacyPolicyCountry__mdt> privacyPolicyCountryMap;

    public class BodyText {
        @AuraEnabled
        public String key { get; set; }

        @AuraEnabled
        public String text { get; set; }
    }

    public class PrivacyPolicy {
        @AuraEnabled
        public String title { get; set; }

/*
        @AuraEnabled
        public List<BodyText> bodyTextList { get; set; }
*/
        @AuraEnabled
        public String bodyText { get; set; }
    }

    public class PrivacyPolicyResult {
        @AuraEnabled
        public PrivacyPolicy countryPrivacyPolicy { get; set; }

        @AuraEnabled
        public PrivacyPolicy globalPrivacyPolicy { get; set; }
    }

    @AuraEnabled (cacheable=false)
    public static PrivacyPolicyResult getPrivacyPolicy(String browserTimeZone) {
        Id userId = UserInfo.getUserId();
        // International Scope is for countries outside of OMV domain of countries
        // In that case, the Privacy Policy will be the Austrian one translated to english
        // as setup in the Custom Metadata Type PrivacyPolicyCountries__mdt where TimeZone__c is NULL
        Boolean isInternationalScope = false;
        String userCountryCode;
        String identifiedCountryCode;
        String countryCode;

        initPrivacyPolicyCountryMaps();

        userCountryCode = getPortalUserCountryCode(userId);


        if (String.isNotBlank(browserTimeZone)) {
            String timeZoneKey = timeZoneCountryMap.containsKey(browserTimeZone) ? browserTimeZone : DEFAULT_TIMEZONE_KEY;

            identifiedCountryCode = timeZoneCountryMap.get(timeZoneKey);
        }

        if (String.isBlank(userCountryCode) && String.isBlank(identifiedCountryCode)) {
            // Site Guest User or User without Country Code
            // and
            // Could not identify country code from browser timezone
            isInternationalScope = true;
            countryCode = DEFAULT_COUNTRY_CODE;

        } else {
            if (String.isNotBlank(userCountryCode) && !privacyPolicyCountryMap.containsKey(userCountryCode)) {
                // User has country but is an unknown country for privacy policy
                isInternationalScope = true;
                countryCode = DEFAULT_COUNTRY_CODE;

            } else if (String.isNotBlank(userCountryCode) && privacyPolicyCountryMap.containsKey(userCountryCode)) {
                // User has country and it's a known country for privacy policy
                isInternationalScope = false;
                countryCode = userCountryCode;

            } else if (String.isNotBlank(identifiedCountryCode) && privacyPolicyCountryMap.containsKey(identifiedCountryCode)) {
                // User doesnt have a country but has been identified country by time zone and its a known country for privacy policy
                // e.g: user without country code or site guest user in an identified timezone
                isInternationalScope = false;
                countryCode = identifiedCountryCode;

            } else if (String.isNotBlank(identifiedCountryCode) && !privacyPolicyCountryMap.containsKey(identifiedCountryCode)) {
                // User doesnt have a country but has been identified country by time zone and its a non-known country code for privacy policy
                isInternationalScope = false;
                countryCode = DEFAULT_COUNTRY_CODE;

            }
        }

        return getPrivacyPolicyFor(countryCode);
    }

    public static PrivacyPolicyResult getPrivacyPolicyFor(String countryCode) {
        PrivacyPolicyResult result = new PrivacyPolicyResult();

        result.countryPrivacyPolicy = getPrivacyPolicyOfCountry(countryCode);
        result.globalPrivacyPolicy = getGlobalPrivacyPolicyOfCountry(countryCode);

        return result;
    }

    public static PrivacyPolicy getPrivacyPolicyOfCountry(String countryCode) {
        PrivacyPolicy result;

        if (String.isNotBlank(privacyPolicyCountryMap.get(countryCode).Title__c)) {
            result = new PrivacyPolicy();
            
            result.title = privacyPolicyCountryMap.get(countryCode).Title__c;
            result.bodyText = privacyPolicyCountryMap.get(countryCode).Body__c;
        }

        return result;
    }

    public static PrivacyPolicy getGlobalPrivacyPolicyOfCountry(String countryCode) {
        PrivacyPolicy result;

        if (String.isNotBlank(privacyPolicyCountryMap.get(countryCode).Title_English__c)) {
            result = new PrivacyPolicy();

            result.title = privacyPolicyCountryMap.get(countryCode).Title_English__c;
            result.bodyText = privacyPolicyCountryMap.get(countryCode).Body_English__c;
        }

        return result;
    }

    public static void initPrivacyPolicyCountryMaps() {
        Boolean isInit = false;

        if (privacyPolicyCountryMap == null) {
            privacyPolicyCountryMap = new Map<String,PrivacyPolicyCountry__mdt>();
            isInit = true;
        }

        if (timeZoneCountryMap == null) {
            timeZoneCountryMap = new Map<String,String>();
            isInit = true;
        }

        if (isInit) {
            REP_PrivacyPolicyCountry privacyPolicyCountryRepository = new REP_PrivacyPolicyCountry();

            timeZoneCountryMap = new Map<String,String>();

            for (PrivacyPolicyCountry__mdt privacyPolicyCountry : privacyPolicyCountryRepository.getPrivacyPolicyCountries()) {
                String timeZoneKey = privacyPolicyCountry.TimeZone__c != null ? privacyPolicyCountry.TimeZone__c : DEFAULT_TIMEZONE_KEY;

                timeZoneCountryMap.put(timeZoneKey, privacyPolicyCountry.CountryIsoCode__c);
                privacyPolicyCountryMap.put(privacyPolicyCountry.CountryIsoCode__c, privacyPolicyCountry);
            }
        }
    }

    public static String getPortalUserCountryCode(Id portalUserId) {
        REP_User userRepository = new REP_User();
        List<User> userList = userRepository.getPortalUserAndCompanyCode(new Set<Id> { portalUserId });
        String countryCode;

        if (!userList.isEmpty()) {
            countryCode = userList[0]?.Contact?.Account?.CompanyCodeCountry__c;
        }

        return countryCode;
    }    
}