force-app/main/default/objects/Case/fields/CompanyCodeCountry__c.field-meta.xml
<CustomField>
    <fullName>CompanyCodeCountry__c</fullName>
    <description>field used for sharing rules</description>
    <label>Company Code Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerCountry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ReopenedInFlow__c.field-meta.xml
<CustomField>
    <fullName>ReopenedInFlow__c</fullName>
    <defaultValue>false</defaultValue>
    <description>field created to be used only in the reopen case flow to avoid the validation rule</description>
    <label>Reopened in Flow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer - Representative</fullName>
            </value>
            <value>
                <fullName>Customer - Driver</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Filling Station</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Customer - Driver Internal</fullName>
                <isActive>false</isActive>
                <label>Customer - Driver Internal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case Support Process</businessProcess>
    <label>CEP Cards Case</label>
</RecordType>

force-app/main/default/objects/CEP_Configuration__c/CEP_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>custom setting for diverse configuration</description>
    <label>CEP Configuration</label>
</CustomObject>

force-app/main/default/objects/CEP_Configuration__c/fields/OMVEmailDomains__c.field-meta.xml
<CustomField>
    <fullName>OMVEmailDomains__c</fullName>
    <description>list of email domains that belongs to omv.</description>
    <label>OMV Email Domains</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/CustomerCountry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CZ</fullName>
        <label>Czech Republic</label>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
        <label>Hungary</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
        <label>Slovakia</label>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
        <label>Bulgaria</label>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
        <label>Austria</label>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
        <label>Moldova</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <label>Romania</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <label>Croatia</label>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
        <label>Bosnia</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Poland</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
        <label>Turkey</label>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
        <label>Russia</label>
    </customValue>
    <customValue>
        <fullName>SH</fullName>
        <label>Serbia</label>
    </customValue>
    <customValue>
        <fullName>SL</fullName>
        <label>Slovenia</label>
    </customValue>
    <customValue>
        <fullName>Hungarian</fullName>
        <isActive>false</isActive>
        <label>Hungarian</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
        <isActive>false</isActive>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>Slovak</fullName>
        <isActive>false</isActive>
        <label>Slovak</label>
    </customValue>
    <customValue>
        <fullName>Romanian</fullName>
        <isActive>false</isActive>
        <label>Romanian</label>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
        <isActive>false</isActive>
        <label>Bulgarian</label>
    </customValue>
    <customValue>
        <fullName>German</fullName>
        <isActive>false</isActive>
        <label>German</label>
    </customValue>
    <description>Global value set to store working languages for OMV CEP business lines. Available languages should match the activated languages in the Translation Language Settings.</description>
    <masterLabel>Customer Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TW_Case_FillComplementaryFields.cls
/**
@description    worker class to automatically fill Case Source
@testClass      TW_Case_FillComplementaryFieldsTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description  
* Guilherme Charro                22/06/2021          Created the class
* ------------------------------------------------------------------------------------        
*/
public with sharing class TW_Case_FillComplementaryFields {    
    private ISL_CountryDefinitionFromParent countryDefinition;

    public TW_Case_FillComplementaryFields(){
        this.countryDefinition = new SL_CountryDefinitionFromParent();
    }
    
    @TestVisible
    private TW_Case_FillComplementaryFields(ISL_CountryDefinitionFromParent countryDefinition){
        this.countryDefinition = countryDefinition;
    }

    public void execute(List<Case> caseList, Map<Id,Case> oldCaseMap) {
        CEP_Configuration__c orgDefaults = CEP_Configuration__c.getOrgDefaults();
        List<String> allDomains = orgDefaults.OMVEmailDomains__c.split(',');
        List<Case> casesToFillCountryList = new List<Case>();

        for (Case caseInserted : caseList) {
            if (oldCaseMap == null) {
                if (!String.isBlank(caseInserted.ContactId)) {
                    caseInserted.Source__c = DO_Case.CASE_SOURCE_CUSTOMER_REPRESENTATIVE;
                }else{
                    if (caseInserted.Origin == DO_Case.CASE_ORIGIN_EMAIL && !String.isBlank(caseInserted.SuppliedEmail) && allDomains.contains(caseInserted.SuppliedEmail.substringAfter('@'))) {
                        caseInserted.Source__c = DO_Case.CASE_SOURCE_INTERNAL;
                    }
                }

                if (DO_Case.CASE_CARDS_RECORDTYPESIDS.contains(caseInserted.RecordTypeId) && 
                    !String.isBlank(caseInserted.AccountId)) {
                    casesToFillCountryList.add(caseInserted);
                }
            }else{
                if (DO_Case.CASE_CARDS_RECORDTYPESIDS.contains(caseInserted.RecordTypeId) && caseInserted.AccountId != oldCaseMap.get(caseInserted.Id).AccountId) {
                    casesToFillCountryList.add(caseInserted);
                }
                if( caseInserted.Status == DO_Case.CASE_STATUS_COMPLETED || caseInserted.Status == DO_Case.CASE_STATUS_CLOSED){
                    caseInserted.ReopenedInFlow__c = false;
                }
            }   
        }

        if (!casesToFillCountryList.isEmpty()) {
            countryDefinition.setCountryField(casesToFillCountryList, 'CompanyCodeCountry__c', 'AccountId');
        }        
    }
}