force-app/main/default/objects/PrivacyPolicyCountry__mdt/PrivacyPolicyCountry__mdt.object-meta.xml
<CustomObject>
    <description>Configuration of Privacy Policy on per country basis with title text and body text on native language and translation to international English language.</description>
    <label>Privacy Policy Country</label>
    <pluralLabel>Privacy Policy Countries</pluralLabel>
</CustomObject>

force-app/main/default/objects/PrivacyPolicyCountry__mdt/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PrivacyPolicyCountry__mdt/fields/Body_English__c.field-meta.xml
<CustomField>
    <fullName>Body_English__c</fullName>
    <label>Body_English</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PrivacyPolicyCountry__mdt/fields/CountryIsoCode__c.field-meta.xml
<CustomField>
    <fullName>CountryIsoCode__c</fullName>
    <label>Country Iso Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrivacyPolicyCountry__mdt/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <label>Time Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PrivacyPolicyCountry__mdt/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PrivacyPolicyCountry__mdt/fields/Title_English__c.field-meta.xml
<CustomField>
    <fullName>Title_English__c</fullName>
    <label>Title_English</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/REP_PrivacyPolicyCountry.cls
/**
* @description   Privacy Policy Country 
* @testClass     REP_PrivacyPolicyCountry
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* António Santos               28/09/2021           Created Privacy Policy Country Repository
* ------------------------------------------------------------------------------------ 
*/
public with sharing class REP_PrivacyPolicyCountry extends FW_SobjectRep implements IREP_PrivacyPolicyCountry {
    public List<PrivacyPolicyCountry__mdt> getPrivacyPolicyCountries() {
        return [
            SELECT
                Id,
                MasterLabel,
                CountryIsoCode__c,
                TimeZone__c,
                Title__c,
                Body__c,
                Title_English__c,
                Body_English__c
            FROM
                PrivacyPolicyCountry__mdt
        ];
    }
}