force-app/main/default/objects/ProductDiscount__c/ProductDiscount__c.object-meta.xml
<CustomObject>
    <description>This datatable is used for the Cards business line, to allow discount mapping for each Product</description>
    <label>Product Discount</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Discount</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductDiscount__c/fields/DiscountUnit__c.field-meta.xml
<CustomField>
    <fullName>DiscountUnit__c</fullName>
    <description>Unit of measure of this discount</description>
    <label>Discount Unit</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductDiscount__c/fields/DiscountValue__c.field-meta.xml
<CustomField>
    <fullName>DiscountValue__c</fullName>
    <description>Value of this discount (5% for example)</description>
    <label>Discount Value</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductDiscount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product in which this discount will be applied</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products Discount</relationshipLabel>
    <relationshipName>ProductsDiscount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductDiscount__c/fields/QuantityOfCriteria__c.field-meta.xml
<CustomField>
    <fullName>QuantityOfCriteria__c</fullName>
    <description>Quantity of active criterias that need to be met in order to apply this discount to a product</description>
    <label>Quantity of Criteria</label>
    <summaryFilterItems>
        <field>ProductDiscountCriteria__c.IsActive__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>ProductDiscountCriteria__c.ProductDiscount__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/ProductDiscountCriteria__c/ProductDiscountCriteria__c.object-meta.xml
<CustomObject>
    <description>Datatable used to allow several different matching criteria for each applicable Product Discount</description>
    <label>Product Discount Criteria</label>
    <nameField>
        <label>Field API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Discount Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductDiscountCriteria__c/fields/ProductDiscount__c.field-meta.xml
<CustomField>
    <fullName>ProductDiscount__c</fullName>
    <description>Discount to apply this criteria</description>
    <label>Product Discount</label>
    <referenceTo>ProductDiscount__c</referenceTo>
    <relationshipLabel>Products Discount Criteria</relationshipLabel>
    <relationshipName>ProductsDiscountCriteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DiscountUnit__c.field-meta.xml
<CustomField>
    <fullName>DiscountUnit__c</fullName>
    <description>field to store the discount unit to be used</description>
    <label>Discount Unit</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DiscountValue__c.field-meta.xml
<CustomField>
    <fullName>DiscountValue__c</fullName>
    <description>Field to save the discount value of the Quote Line Item</description>
    <label>Discount Value</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TW_QuoteLineItem_AddDiscounts.cls
/**
* @description   worker class to add discounts to the quote
* @testClass     TW_QuoteLineItem_AddDiscountsTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro               28/07/2021          Created QuoteLineItem Worker
* ------------------------------------------------------------------------------------ 
*/
public with sharing class TW_QuoteLineItem_AddDiscounts {

    private IREP_ProductDiscount productDiscountRepository;
    private IREP_Quote quoteRepository;
    private IREP_PricebookEntry pricebookEntryRepository;
    private IDO_QuoteLineItem quoteLineItemDomain;
    
    //constructor
     public TW_QuoteLineItem_AddDiscounts(){
         this.productDiscountRepository = new REP_ProductDiscount();
         this.quoteRepository = new REP_Quote();
         this.pricebookEntryRepository = new REP_PricebookEntry();
         this.quoteLineItemDomain = new DO_QuoteLineItem();
    }
    
    //to use on test
    @TestVisible
    private TW_QuoteLineItem_AddDiscounts(IREP_ProductDiscount productDiscountRepository, IREP_Quote quoteRepository, IREP_PricebookEntry pricebookEntryRepository, IDO_QuoteLineItem quoteLineItemDomain){
        this.productDiscountRepository = productDiscountRepository;
        this.quoteRepository = quoteRepository;
        this.pricebookEntryRepository = pricebookEntryRepository;
        this.quoteLineItemDomain = quoteLineItemDomain;
    }

    public void execute(List<QuoteLineItem> quoteLineItemList){
        Set<Id> quoteToQueryIDSet = new Set<Id>();
        Set<Id> pricebookEntryToQueryIdSet = new Set<Id>(); 
        for (QuoteLineItem quoteLineItemInserted : quoteLineItemList) {
            quoteToQueryIDSet.add(quoteLineItemInserted.QuoteId);
            pricebookEntryToQueryIdSet.add(quoteLineItemInserted.PricebookEntryId);
        }

        Map<Id,PricebookEntry> pricebookEntryMap = new Map<Id,PricebookEntry>();

        if (!pricebookEntryToQueryIdSet.isEmpty()) {
            pricebookEntryMap = new Map<Id,PricebookEntry>(pricebookEntryRepository.getPricebookEntryInformation(pricebookEntryToQueryIdSet));
        }
        
        Set<Id> productToQueryIdSet = new Set<Id>();
        for (PricebookEntry entries : pricebookEntryMap.values()) {
            productToQueryIdSet.add(entries.Product2Id);
        }

        Map<id,Quote> cardQuoteMap = New Map<id,Quote>();

        if (!quoteToQueryIDSet.isEmpty()) {
            cardQuoteMap = New Map<id,Quote>(quoteRepository.getCardsQuotes(quoteToQueryIDSet));
        }
        
        //Key = Product ID, Value = List Product Discount
        Map<Id,List<ProductDiscount__c>> discountsMap = new Map<Id,List<ProductDiscount__c>>();
        for(ProductDiscount__c prodDiscount : productDiscountRepository.getProductDiscountsCriteria(productToQueryIdSet)) {
            if(discountsMap.containsKey(prodDiscount.Product__c)){
                discountsMap.get(prodDiscount.Product__c).add(prodDiscount);
            } else {
                discountsMap.put(prodDiscount.Product__c, new List<ProductDiscount__c>{prodDiscount});
            }
        }

        for (QuoteLineItem quoteLineItem : quoteLineItemList) {
            if(cardQuoteMap.containsKey(quoteLineItem.QuoteId)
                && discountsMap.containsKey(pricebookEntryMap.get(quoteLineItem.PricebookEntryId).Product2Id)){
                for (ProductDiscount__c discount : discountsMap.get(pricebookEntryMap.get(quoteLineItem.PricebookEntryId).Product2Id)) {
                    
                        if (quoteLineItemDomain.isToApplyDiscountToQuoteItem(cardQuoteMap.get(quoteLineItem.QuoteId), discount.ProductsDiscountCriteria__r, (Integer)discount.QuantityOfCriteria__c)) {
                            quoteLineItem.DiscountValue__c = discount.DiscountValue__c;
                            quoteLineItem.DiscountUnit__c = discount.DiscountUnit__c;
                        }
                    
                }
            }
        }
    }
}