force-app/main/default/objects/ProductDiscount__c/ProductDiscount__c.object-meta.xml
<CustomObject>
    <description>This datatable is used for the Cards business line, to allow discount mapping for each Product</description>
    <label>Product Discount</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Discount</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductDiscount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product in which this discount will be applied</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products Discount</relationshipLabel>
    <relationshipName>ProductsDiscount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/REP_ProductDiscountTest.cls
@isTest
public with sharing class REP_ProductDiscountTest {
    @isTest
    static void ProductDiscountTest() {
        User runningUser = FW_TestDataFactory.createUsers(1, true, 'System Administrator', null).get(0);
        System.runAs(runningUser){  
            List<Product2> productList = FW_TestDataFactory.createProduct(1, true);
            Set<Id> productsId = new Set<Id>();
            productsId.add(productList[0].Id);

            List<ProductDiscount__c> productDiscountList = FW_TestDataFactory.createProductDiscount(1, false);
            productDiscountList[0].Product__c = productList[0].Id;
            insert productDiscountList;

            test.startTest();
            REP_ProductDiscount productDiscountRepository = new REP_ProductDiscount();
            List<ProductDiscount__c> productDiscountReturned = productDiscountRepository.getProductDiscountsCriteria(productsId);
            test.stopTest();
            System.assertEquals(1, productDiscountReturned.size());
        }
    }
}