force-app/main/default/objects/ProductDiscount__c/ProductDiscount__c.object-meta.xml
<CustomObject>
    <description>This datatable is used for the Cards business line, to allow discount mapping for each Product</description>
    <label>Product Discount</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Discount</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductDiscount__c/fields/DiscountUnit__c.field-meta.xml
<CustomField>
    <fullName>DiscountUnit__c</fullName>
    <description>Unit of measure of this discount</description>
    <label>Discount Unit</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductDiscount__c/fields/DiscountValue__c.field-meta.xml
<CustomField>
    <fullName>DiscountValue__c</fullName>
    <description>Value of this discount (5% for example)</description>
    <label>Discount Value</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductDiscount__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field determines if this discount is active or not</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProductDiscount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product in which this discount will be applied</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products Discount</relationshipLabel>
    <relationshipName>ProductsDiscount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductDiscount__c/fields/QuantityOfCriteria__c.field-meta.xml
<CustomField>
    <fullName>QuantityOfCriteria__c</fullName>
    <description>Quantity of active criterias that need to be met in order to apply this discount to a product</description>
    <label>Quantity of Criteria</label>
    <summaryFilterItems>
        <field>ProductDiscountCriteria__c.IsActive__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>ProductDiscountCriteria__c.ProductDiscount__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/ProductDiscountCriteria__c/ProductDiscountCriteria__c.object-meta.xml
<CustomObject>
    <description>Datatable used to allow several different matching criteria for each applicable Product Discount</description>
    <label>Product Discount Criteria</label>
    <nameField>
        <label>Field API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Discount Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductDiscountCriteria__c/fields/FieldValue__c.field-meta.xml
<CustomField>
    <fullName>FieldValue__c</fullName>
    <description>Value that needs to be equal on the quote field</description>
    <label>Field Value</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductDiscountCriteria__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if this criteria is active or not</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProductDiscountCriteria__c/fields/ProductDiscount__c.field-meta.xml
<CustomField>
    <fullName>ProductDiscount__c</fullName>
    <description>Discount to apply this criteria</description>
    <label>Product Discount</label>
    <referenceTo>ProductDiscount__c</referenceTo>
    <relationshipLabel>Products Discount Criteria</relationshipLabel>
    <relationshipName>ProductsDiscountCriteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/REP_ProductDiscount.cls
/**
* @description   ProductDiscount Repository
* @testClass     REP_ProductDiscountTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro                28/07/2021          Created ProductDiscount Repository
* ------------------------------------------------------------------------------------ 
*/
public class REP_ProductDiscount extends FW_SobjectRep implements IREP_ProductDiscount{
    public List<ProductDiscount__c> getProductDiscountsCriteria(Set<Id> productIdSet){
        return [SELECT Id, QuantityOfCriteria__c, DiscountUnit__c, DiscountValue__c, Product__c, 
                (SELECT Name, FieldValue__c FROM ProductsDiscountCriteria__r WHERE IsActive__c = true) 
                FROM ProductDiscount__c 
                WHERE IsActive__c = true 
                AND Product__c IN :productIdSet];
    }
}