force-app/main/default/objects/ProductDiscount__c/ProductDiscount__c.object-meta.xml
<CustomObject>
    <description>This datatable is used for the Cards business line, to allow discount mapping for each Product</description>
    <label>Product Discount</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Discount</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductDiscountCriteria__c/ProductDiscountCriteria__c.object-meta.xml
<CustomObject>
    <description>Datatable used to allow several different matching criteria for each applicable Product Discount</description>
    <label>Product Discount Criteria</label>
    <nameField>
        <label>Field API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Discount Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductDiscountCriteria__c/fields/FieldValue__c.field-meta.xml
<CustomField>
    <fullName>FieldValue__c</fullName>
    <description>Value that needs to be equal on the quote field</description>
    <label>Field Value</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductDiscountCriteria__c/fields/ProductDiscount__c.field-meta.xml
<CustomField>
    <fullName>ProductDiscount__c</fullName>
    <description>Discount to apply this criteria</description>
    <label>Product Discount</label>
    <referenceTo>ProductDiscount__c</referenceTo>
    <relationshipLabel>Products Discount Criteria</relationshipLabel>
    <relationshipName>ProductsDiscountCriteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QuoteType__c.field-meta.xml
<CustomField>
    <fullName>QuoteType__c</fullName>
    <description>This field presents the quote type that will define the mandatory product for each type and the price type associated</description>
    <label>Quote Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuoteTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/QuoteTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fleet PP</fullName>
        <default>true</default>
        <label>Fleet PP</label>
    </customValue>
    <customValue>
        <fullName>Fleet LP</fullName>
    </customValue>
    <customValue>
        <fullName>Int CRT LP</fullName>
    </customValue>
    <customValue>
        <fullName>Nat CRT LP</fullName>
    </customValue>
    <customValue>
        <fullName>Int Agents LP</fullName>
    </customValue>
    <customValue>
        <fullName>E-Mobility</fullName>
    </customValue>
    <customValue>
        <fullName>Smatrics</fullName>
        <isActive>false</isActive>
        <label>Smatrics</label>
    </customValue>
    <masterLabel>Quote Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DO_QuoteLineItemTest.cls
@isTest
public with sharing class DO_QuoteLineItemTest {
    @isTest
    static void DO_QuoteLineItemTest() {
            List<Quote> listQuote = new List<Quote>();
            listQuote.add(
                new Quote(
                    Id = fflib_IDGenerator.generate(Quote.sObjectType),
                    QuoteType__c = 'Fleet PP'
                )  
            );

            List<ProductDiscount__c> listProductDiscount = new List<ProductDiscount__c>();
            listProductDiscount.add(
                new ProductDiscount__c(
                    Id = fflib_IDGenerator.generate(ProductDiscount__c.sObjectType)
                )  
            );

            List<ProductDiscountCriteria__c> listProductDiscountCriteria = new List<ProductDiscountCriteria__c>();
            listProductDiscountCriteria.add(
                new ProductDiscountCriteria__c(
                    Id = fflib_IDGenerator.generate(ProductDiscountCriteria__c.sObjectType),
                    ProductDiscount__c = listProductDiscount[0].Id,
                    ProductDiscount__r = listProductDiscount[0],
                    Name = 'QuoteType__c',
                    FieldValue__c = 'Fleet PP'
                )
            );

            List<ProductDiscountCriteria__c> listProductDiscountCriteria2 = new List<ProductDiscountCriteria__c>();
            listProductDiscountCriteria.add(
                new ProductDiscountCriteria__c(
                    Id = fflib_IDGenerator.generate(ProductDiscountCriteria__c.sObjectType),
                    ProductDiscount__c = listProductDiscount[0].Id,
                    ProductDiscount__r = listProductDiscount[0],
                    Name = 'QuoteType__c',
                    FieldValue__c = 'Fleet LP'
                )
            );

            test.startTest();
            DO_QuoteLineItem quoteLineItemDomain = new DO_QuoteLineItem();
            Boolean isToApplyDiscountToQuoteItem = quoteLineItemDomain.isToApplyDiscountToQuoteItem(listQuote[0], listProductDiscountCriteria, 1);
            Boolean isToApplyDiscountToQuoteItem2 = quoteLineItemDomain.isToApplyDiscountToQuoteItem(listQuote[0], listProductDiscountCriteria2, 1);
            test.stopTest();
            System.assertEquals(true, isToApplyDiscountToQuoteItem);
            System.assertEquals(false, isToApplyDiscountToQuoteItem2);
    }
}