force-app/main/default/objects/ProductDiscount__c/ProductDiscount__c.object-meta.xml
<CustomObject>
    <description>This datatable is used for the Cards business line, to allow discount mapping for each Product</description>
    <label>Product Discount</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Discount</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductDiscountCriteria__c/ProductDiscountCriteria__c.object-meta.xml
<CustomObject>
    <description>Datatable used to allow several different matching criteria for each applicable Product Discount</description>
    <label>Product Discount Criteria</label>
    <nameField>
        <label>Field API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Discount Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductDiscountCriteria__c/fields/ProductDiscount__c.field-meta.xml
<CustomField>
    <fullName>ProductDiscount__c</fullName>
    <description>Discount to apply this criteria</description>
    <label>Product Discount</label>
    <referenceTo>ProductDiscount__c</referenceTo>
    <relationshipLabel>Products Discount Criteria</relationshipLabel>
    <relationshipName>ProductsDiscountCriteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TH_ProductDiscountCriteriaTest.cls
@isTest
public with sharing class TH_ProductDiscountCriteriaTest {
    @isTest
    static void TH_ProductDiscountCriteriaTest() {
        User runningUser = FW_TestDataFactory.createUsers(1, true, 'System Administrator', null).get(0);
        List<ProductDiscount__c> productDiscountList = FW_TestDataFactory.createProductDiscount(1, true);

        System.runAs(runningUser){
            test.startTest();
            List<ProductDiscountCriteria__c> productDiscountCriteriaList = FW_TestDataFactory.createProductDiscountCriteria(1, true, productDiscountList[0], 'QuoteType__c', 'teste'); 
            test.stopTest();
            System.assertNotEquals(null, productDiscountCriteriaList[0].Id);
        }
    }
}