force-app/main/default/objects/ProductDiscount__c/ProductDiscount__c.object-meta.xml
<CustomObject>
    <description>This datatable is used for the Cards business line, to allow discount mapping for each Product</description>
    <label>Product Discount</label>
    <nameField>
        <displayFormat>PD-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Discount</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductDiscount__c/fields/DiscountUnit__c.field-meta.xml
<CustomField>
    <fullName>DiscountUnit__c</fullName>
    <description>Unit of measure of this discount</description>
    <label>Discount Unit</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductDiscount__c/fields/DiscountValue__c.field-meta.xml
<CustomField>
    <fullName>DiscountValue__c</fullName>
    <description>Value of this discount (5% for example)</description>
    <label>Discount Value</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductDiscount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product in which this discount will be applied</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products Discount</relationshipLabel>
    <relationshipName>ProductsDiscount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductDiscount__c/fields/QuantityOfCriteria__c.field-meta.xml
<CustomField>
    <fullName>QuantityOfCriteria__c</fullName>
    <description>Quantity of active criterias that need to be met in order to apply this discount to a product</description>
    <label>Quantity of Criteria</label>
    <summaryFilterItems>
        <field>ProductDiscountCriteria__c.IsActive__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>ProductDiscountCriteria__c.ProductDiscount__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/ProductDiscountCriteria__c/ProductDiscountCriteria__c.object-meta.xml
<CustomObject>
    <description>Datatable used to allow several different matching criteria for each applicable Product Discount</description>
    <label>Product Discount Criteria</label>
    <nameField>
        <label>Field API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Discount Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductDiscountCriteria__c/fields/FieldValue__c.field-meta.xml
<CustomField>
    <fullName>FieldValue__c</fullName>
    <description>Value that needs to be equal on the quote field</description>
    <label>Field Value</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductDiscountCriteria__c/fields/ProductDiscount__c.field-meta.xml
<CustomField>
    <fullName>ProductDiscount__c</fullName>
    <description>Discount to apply this criteria</description>
    <label>Product Discount</label>
    <referenceTo>ProductDiscount__c</referenceTo>
    <relationshipLabel>Products Discount Criteria</relationshipLabel>
    <relationshipName>ProductsDiscountCriteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QuoteType__c.field-meta.xml
<CustomField>
    <fullName>QuoteType__c</fullName>
    <description>This field presents the quote type that will define the mandatory product for each type and the price type associated</description>
    <label>Quote Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuoteTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DiscountUnit__c.field-meta.xml
<CustomField>
    <fullName>DiscountUnit__c</fullName>
    <description>field to store the discount unit to be used</description>
    <label>Discount Unit</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DiscountValue__c.field-meta.xml
<CustomField>
    <fullName>DiscountValue__c</fullName>
    <description>Field to save the discount value of the Quote Line Item</description>
    <label>Discount Value</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/QuoteTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fleet PP</fullName>
        <default>true</default>
        <label>Fleet PP</label>
    </customValue>
    <customValue>
        <fullName>Fleet LP</fullName>
    </customValue>
    <customValue>
        <fullName>Int CRT LP</fullName>
    </customValue>
    <customValue>
        <fullName>Nat CRT LP</fullName>
    </customValue>
    <customValue>
        <fullName>Int Agents LP</fullName>
    </customValue>
    <customValue>
        <fullName>E-Mobility</fullName>
    </customValue>
    <customValue>
        <fullName>Smatrics</fullName>
        <isActive>false</isActive>
        <label>Smatrics</label>
    </customValue>
    <masterLabel>Quote Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TW_QuoteDiscountChangeTest.cls
/**
@author Hugo Rodrigues
@date    05/08/2021
@description Test class for TW_QuoteDiscountChange
@TestClass         
Modification Log:
----------------------------------------------------------------------------------------------------
Developer                       Date                Description                           Coverage
----------------------------------------------------------------------------------------------------
Hugo Rodrigues                   05/08/2021         Original Version                         98
Hugo Rodrigues                   28/08/2021          Adjustment on class for best pratices   98
*/
@isTest
public with sharing class TW_QuoteDiscountChangeTest {
    static fflib_ApexMocks mocks = new fflib_ApexMocks();

    @isTest
    private static void TW_QuoteDiscountChangeTest() {
        IREP_ProductDiscount productDiscountRepository = (REP_ProductDiscount)mocks.mock(REP_ProductDiscount.class);
        IREP_Quote quoteRepository = (REP_Quote)mocks.mock(REP_Quote.class);
        IREP_PricebookEntry pricebookEntryRepository = (REP_PricebookEntry)mocks.mock(REP_PricebookEntry.class);
        IDO_QuoteLineItem quoteLineItemDomain = (DO_QuoteLineItem)mocks.mock(DO_QuoteLineItem.class);
        IREP_QuoteLineItem quoteLineItemRepository = (REP_QuoteLineItem)mocks.mock(REP_QuoteLineItem.class);
        Set<ID> pricebookEntryIDSet = new Set<ID>();
        Set<ID> quoteIDSet = new Set<ID>();
        
        List<Product2> listProduct = new List<Product2>();
        listProduct.add(
            new Product2(
                Id = fflib_IDGenerator.generate(Product2.sObjectType)
            )
        );
        listProduct.add(
           
            new Product2(
                Id = fflib_IDGenerator.generate(Product2.sObjectType)
            )  
        );

        List<PricebookEntry> listPricebookEntry = new List<PricebookEntry>();
        listPricebookEntry.add(
            new PricebookEntry(
                Id = fflib_IDGenerator.generate(PricebookEntry.sObjectType),
                Product2 = listProduct[0]
            )
        );
        listPricebookEntry.add(
            
            new PricebookEntry(
                Id = fflib_IDGenerator.generate(PricebookEntry.sObjectType),
                Product2 = listProduct[1]
            )    
        );
        pricebookEntryIDSet.add(listPricebookEntry[0].ID);
        pricebookEntryIDSet.add(listPricebookEntry[1].ID);
        List<Quote> listQuote = new List<Quote>();
        listQuote.add(
            new Quote(
                Id = fflib_IDGenerator.generate(Quote.sObjectType),
                QuoteType__c = Do_Quote.QUOTE_TYPE_FLEET_PP,
                RecordTypeId = DO_Quote.QUOTE_CARDS_RECORDTYPE_ID
            )  
        );
        Map<Id, Quote> oldQuoteMap = new Map<Id, Quote>();
        oldQuoteMap.put(listQuote[0].Id, new Quote(Id = listQuote[0].Id, 
        QuoteType__c = Do_Quote.QUOTE_TYPE_FLEET_LP));

        listQuote[0].QuoteType__c = Do_Quote.QUOTE_TYPE_FLEET_PP;

        List<QuoteLineItem> listQuoteLineItem = new List<QuoteLineItem>();
        listQuoteLineItem.add(
            new QuoteLineItem(
                Id = fflib_IDGenerator.generate(QuoteLineItem.sObjectType),
                QuoteId = listQuote[0].Id,
                PricebookEntryId = listPricebookEntry[0].Id
            )
        ); 
        listQuoteLineItem.add(
            new QuoteLineItem(
                Id = fflib_IDGenerator.generate(QuoteLineItem.sObjectType),
                QuoteId = listQuote[0].Id,
                PricebookEntryId = listPricebookEntry[1].Id
            )  
        ); 

        
        
        List<Quote> newlistQuote = (List<Quote>)fflib_ApexMocksUtils.makeRelationship(
                List<Quote>.class,
                listQuote,
                QuoteLineItem.QuoteId,
            	new List<List<QuoteLineItem>> {listQuoteLineItem}
        );

        List<ProductDiscount__c> listProductDiscount = new List<ProductDiscount__c>();
        listProductDiscount.add(
            new ProductDiscount__c(
                Id = fflib_IDGenerator.generate(ProductDiscount__c.sObjectType),
                Product__r = listProduct[0],
                DiscountValue__c = 10,
                DiscountUnit__c = '€'
            )
        );
        
        
        listProductDiscount[0] = (ProductDiscount__c)fflib_ApexMocksUtils.setReadOnlyFields(
                listProductDiscount[0],
                ProductDiscount__c.class,
                new Map<SObjectField, Object> {ProductDiscount__c.QuantityOfCriteria__c => 1}
        );
        


        List<ProductDiscountCriteria__c> listProductDiscountCriteria = new List<ProductDiscountCriteria__c>();
        listProductDiscountCriteria.add(
            new ProductDiscountCriteria__c(
                Id = fflib_IDGenerator.generate(ProductDiscountCriteria__c.sObjectType),
                ProductDiscount__c = listProductDiscount[0].Id,
                ProductDiscount__r = listProductDiscount[0],
                Name = 'QuoteType__c',
                FieldValue__c = Do_Quote.QUOTE_TYPE_FLEET_PP
            )  
        );
        
        List<ProductDiscount__c> listaProductDiscount = (List<ProductDiscount__c>)fflib_ApexMocksUtils.makeRelationship(
                List<ProductDiscount__c>.class,
                listProductDiscount,
                ProductDiscountCriteria__c.ProductDiscount__c,
            	new List<List<ProductDiscountCriteria__c>> {listProductDiscountCriteria}
        );
        quoteIDSet.add(newlistQuote[0].Id);
        mocks.startStubbing();
        mocks.when(pricebookEntryRepository.getPricebookEntryInformation((Set<Id>) fflib_match.anyObject())).thenReturn(listPricebookEntry);
        mocks.when(quoteRepository.getQuoteWithItemsById((Set<Id>) fflib_match.anyObject())).thenReturn(newlistQuote);
        mocks.when(productDiscountRepository.getProductDiscountsCriteria((Set<Id>) fflib_match.anyObject())).thenReturn(listaProductDiscount);
        mocks.when(quoteLineItemDomain.isToApplyDiscountToQuoteItem((Quote) fflib_match.anyObject(), (List<ProductDiscountCriteria__c>) fflib_match.anyList(), (Integer) fflib_Match.eq(1))).thenReturn(true);
        mocks.when(quoteLineItemRepository.updateSObjects((List<QuoteLineItem>)  fflib_match.anyList())).thenReturn(new List<Database.SaveResult>());
        mocks.stopStubbing();

        TW_QuoteDiscountChange jobExecutionWorker = new TW_QuoteDiscountChange();
        jobExecutionWorker = new TW_QuoteDiscountChange(productDiscountRepository,quoteRepository, pricebookEntryRepository, quoteLineItemDomain, quoteLineItemRepository);
        
        jobExecutionWorker.execute(listQuote,oldQuoteMap);
        
        ((IREP_PricebookEntry)mocks.verify(pricebookEntryRepository, 1)).getPricebookEntryInformation((Set<Id>) fflib_match.eq(pricebookEntryIDSet));
        ((IREP_Quote)mocks.verify(quoteRepository, 1)).getQuoteWithItemsById((Set<Id>) fflib_match.eq(quoteIDSet));
        ((IREP_ProductDiscount)mocks.verify(productDiscountRepository, 1)).getProductDiscountsCriteria((Set<Id>) fflib_match.anyObject());
        ((IDO_QuoteLineItem)mocks.verify(quoteLineItemDomain, 2)).isToApplyDiscountToQuoteItem((Quote) fflib_match.anyObject(), (List<ProductDiscountCriteria__c>) fflib_match.anyList(), (Integer) fflib_Match.eq(1));
    	((IREP_QuoteLineItem)mocks.verify(quoteLineItemRepository, 1)).updateSObjects((List<QuoteLineItem>) fflib_match.anyList());

        mocks.startStubbing();
        mocks.when(quoteLineItemDomain.isToApplyDiscountToQuoteItem((Quote) fflib_match.anyObject(), (List<ProductDiscountCriteria__c>) fflib_match.anyList(), (Integer) fflib_Match.eq(1))).thenReturn(false);
        mocks.stopStubbing();

        TW_QuoteDiscountChange jobExecutionWorker2 = new TW_QuoteDiscountChange();
        jobExecutionWorker2 = new TW_QuoteDiscountChange(productDiscountRepository,quoteRepository, pricebookEntryRepository, quoteLineItemDomain, quoteLineItemRepository);
        
        jobExecutionWorker2.execute(listQuote,oldQuoteMap);
        
        ((IREP_PricebookEntry)mocks.verify(pricebookEntryRepository, 2)).getPricebookEntryInformation((Set<Id>) fflib_match.eq(pricebookEntryIDSet));
        ((IREP_Quote)mocks.verify(quoteRepository, 2)).getQuoteWithItemsById((Set<Id>) fflib_match.eq(quoteIDSet));
        ((IREP_ProductDiscount)mocks.verify(productDiscountRepository, 2)).getProductDiscountsCriteria((Set<Id>) fflib_match.anyObject());
        ((IDO_QuoteLineItem)mocks.verify(quoteLineItemDomain, 4)).isToApplyDiscountToQuoteItem((Quote) fflib_match.anyObject(), (List<ProductDiscountCriteria__c>) fflib_match.anyList(), (Integer) fflib_Match.eq(1));
    	((IREP_QuoteLineItem)mocks.verify(quoteLineItemRepository, 2)).updateSObjects((List<QuoteLineItem>) fflib_match.anyList());

    }
}