force-app/main/default/objects/CEP_ApiCredential__mdt/CEP_ApiCredential__mdt.object-meta.xml
<CustomObject>
    <description>Manage the association between a credential defined in the context of the API Framework, logical environment where it can be used and the target Named Credential.</description>
    <label>CEP API Credential</label>
    <pluralLabel>CEP API Credentials</pluralLabel>
</CustomObject>

force-app/main/default/objects/CEP_ApiHttpHeader__mdt/CEP_ApiHttpHeader__mdt.object-meta.xml
<CustomObject>
    <description>The list of Http Headers that are send when invoking the API method. The Header Value is a merge field that can be merged at runtime using the relatedObject or inputFieldMap parameters of the call() API method.</description>
    <label>CEP API Http Header</label>
    <pluralLabel>CEP API Http Headers</pluralLabel>
</CustomObject>

force-app/main/default/objects/CEP_ApiHttpHeader__mdt/fields/HeaderName__c.field-meta.xml
<CustomField>
    <fullName>HeaderName__c</fullName>
    <label>Header Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEP_ApiHttpHeader__mdt/fields/HeaderValue__c.field-meta.xml
<CustomField>
    <fullName>HeaderValue__c</fullName>
    <inlineHelpText>Merge field values use the syntax {!fieldName}.</inlineHelpText>
    <label>Header Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEP_ApiMethod__mdt/CEP_ApiMethod__mdt.object-meta.xml
<CustomObject>
    <description>An API method that is called from the API framework. In this entity it is defined the associated path, http method, input message template (using merge fields), mock output message and output deserializable apex class.</description>
    <label>CEP API Method</label>
    <pluralLabel>CEP API Methods</pluralLabel>
</CustomObject>

force-app/main/default/objects/CEP_ApiMethod__mdt/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>application/json</fullName>
                <default>true</default>
                <label>application/json</label>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>text/plain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEP_ApiMethod__mdt/fields/HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>HttpMethod__c</fullName>
    <label>Http Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>OPTIONS</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEP_ApiMethod__mdt/fields/Input__c.field-meta.xml
<CustomField>
    <fullName>Input__c</fullName>
    <inlineHelpText>Merge field values use the syntax {!fieldName}.</inlineHelpText>
    <label>Input</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CEP_ApiMethod__mdt/fields/MockOutput__c.field-meta.xml
<CustomField>
    <fullName>MockOutput__c</fullName>
    <label>Mock Output</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CEP_ApiMethod__mdt/fields/OutputDeserializeClassName__c.field-meta.xml
<CustomField>
    <fullName>OutputDeserializeClassName__c</fullName>
    <label>Output Deserialize Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEP_ApiMethod__mdt/fields/SubPath__c.field-meta.xml
<CustomField>
    <fullName>SubPath__c</fullName>
    <inlineHelpText>Merge field values use the syntax {!fieldName}.</inlineHelpText>
    <label>Sub-Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEP_ApiMethod__mdt/fields/TimeoutOverride__c.field-meta.xml
<CustomField>
    <fullName>TimeoutOverride__c</fullName>
    <inlineHelpText>Override timeout (in seconds) for this method.</inlineHelpText>
    <label>Timeout Override</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CEP_ApiPath__mdt/CEP_ApiPath__mdt.object-meta.xml
<CustomObject>
    <description>A Path is a grouping of several Methods that share a common base path in the endpoint URL.</description>
    <label>CEP API Path</label>
    <pluralLabel>CEP API Paths</pluralLabel>
</CustomObject>

force-app/main/default/objects/CEP_ApiPath__mdt/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <inlineHelpText>Merge field values use the syntax {!fieldName}.</inlineHelpText>
    <label>Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FW_ApiMethod.cls
/**
* @description   Framework Api Method Wrapper
* @testClass     
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Antonio Santos                23/08/2021          Created Framework Api Method Wrapper.
* ------------------------------------------------------------------------------------ 
*/
public class FW_ApiMethod {
	public String namedCredential;
	public String path;
	public String subPath;
	public String httpMethod;
	public String contentType;
	public String inputTemplate;
    public String mockOutput;
	public String outputClass;
	public Map<String,List<String>> httpHeaderMap;

    public Integer timeout; // seconds

	public FW_ApiMethod(CEP_ApiCredential__mdt credential, CEP_ApiPath__mdt path, CEP_ApiMethod__mdt method, List<CEP_ApiHttpHeader__mdt> headerList) {
		this.httpHeaderMap = new Map<String,List<String>>();

        this.namedCredential = credential.NamedCredential__c;
        this.path = path.Path__c;

        this.subPath = method.SubPath__c;
        this.httpMethod = method.HttpMethod__c;
        this.contentType = method.ContentType__c;
        this.inputTemplate = method.Input__c;
        this.mockOutput = method.MockOutput__c;
        this.outputClass = method.OutputDeserializeClassName__c;

        if (method.TimeoutOverride__c != null) {
            this.timeout = Integer.valueOf(method.TimeoutOverride__c);
        }

        if (headerList != null) {
            for (CEP_ApiHttpHeader__mdt httpHeader : headerList) {
                if (!this.httpHeaderMap.containsKey(httpHeader.HeaderName__c)) {
                    this.httpHeaderMap.put(httpHeader.HeaderName__c, new List<String>());
                }

                this.httpHeaderMap.get(httpHeader.HeaderName__c).add(httpHeader.HeaderValue__c);
            }
        }
	}
}