force-app/main/default/objects/CEP_ApiCredential__mdt/CEP_ApiCredential__mdt.object-meta.xml
<CustomObject>
    <description>Manage the association between a credential defined in the context of the API Framework, logical environment where it can be used and the target Named Credential.</description>
    <label>CEP API Credential</label>
    <pluralLabel>CEP API Credentials</pluralLabel>
</CustomObject>

force-app/main/default/objects/CEP_ApiCredential__mdt/fields/ApiPath__c.field-meta.xml
<CustomField>
    <fullName>ApiPath__c</fullName>
    <label>API Path</label>
    <referenceTo>CEP_ApiPath__mdt</referenceTo>
    <relationshipLabel>API Credentials</relationshipLabel>
    <relationshipName>ApiCredentials</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/CEP_ApiHttpHeader__mdt/CEP_ApiHttpHeader__mdt.object-meta.xml
<CustomObject>
    <description>The list of Http Headers that are send when invoking the API method. The Header Value is a merge field that can be merged at runtime using the relatedObject or inputFieldMap parameters of the call() API method.</description>
    <label>CEP API Http Header</label>
    <pluralLabel>CEP API Http Headers</pluralLabel>
</CustomObject>

force-app/main/default/objects/CEP_ApiLogicalEnvironment__mdt/CEP_ApiLogicalEnvironment__mdt.object-meta.xml
<CustomObject>
    <description>Definition of a logical environment. In CEP API Setting hierarchy custom setting it is set the target logical environment for the API calls.</description>
    <label>CEP API Logical Environment</label>
    <pluralLabel>CEP API Logical Environments</pluralLabel>
</CustomObject>

force-app/main/default/objects/CEP_ApiMethod__mdt/CEP_ApiMethod__mdt.object-meta.xml
<CustomObject>
    <description>An API method that is called from the API framework. In this entity it is defined the associated path, http method, input message template (using merge fields), mock output message and output deserializable apex class.</description>
    <label>CEP API Method</label>
    <pluralLabel>CEP API Methods</pluralLabel>
</CustomObject>

force-app/main/default/objects/CEP_ApiMethod__mdt/fields/ApiPath__c.field-meta.xml
<CustomField>
    <fullName>ApiPath__c</fullName>
    <label>API Path</label>
    <referenceTo>CEP_ApiPath__mdt</referenceTo>
    <relationshipLabel>API Methods</relationshipLabel>
    <relationshipName>ApiMethods</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/CEP_ApiPath__mdt/CEP_ApiPath__mdt.object-meta.xml
<CustomObject>
    <description>A Path is a grouping of several Methods that share a common base path in the endpoint URL.</description>
    <label>CEP API Path</label>
    <pluralLabel>CEP API Paths</pluralLabel>
</CustomObject>

force-app/main/default/objects/CEP_ApiSetting__c/CEP_ApiSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CEP API Settings</label>
</CustomObject>

force-app/main/default/classes/REP_CEP_ApiTest.cls
/**
* @description    CEP Api Repository Test
* @testClass     
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Antonio Santos                23/08/2021          Created CEP Api Repository Test
* ------------------------------------------------------------------------------------ 
*/
@isTest
public class REP_CEP_ApiTest {
    @isTest
    static void apiTest() {
        User runningUser = FW_TestDataFactory.createUsers(1, true, 'System Administrator', null).get(0);
        
        System.runAs(runningUser) {
            Test.startTest();

            REP_CEP_Api apiRepository = REP_CEP_Api.getInstance();

            CEP_ApiMethod__mdt method = apiRepository.getMethodByDeveloperName('TEST');
            CEP_ApiLogicalEnvironment__mdt logicalEnvironment = apiRepository.getLogicalEnvironmentByDeveloperName('Test');

            CEP_ApiPath__mdt path = apiRepository.getPathById(method.ApiPath__c);

            CEP_ApiCredential__mdt credential = apiRepository.getCredentialByEnvIdPathId(logicalEnvironment.Id, path.Id);
            
            List<CEP_ApiHttpHeader__mdt> httpHeaderList = apiRepository.getHttpHeaderByMethodId(method.Id);

            CEP_ApiSetting__c setting = apiRepository.getSetting();

            System.assert(method != null);
            System.assert(logicalEnvironment != null);
            System.assert(credential != null);
            System.assert(path != null);
            System.assert(httpHeaderList != null && !httpHeaderList.isEmpty());
            System.assert(setting != null);

            Test.stopTest();
        }
    }
}