force-app/main/default/objects/CEP_ApiCredential__mdt/CEP_ApiCredential__mdt.object-meta.xml
<CustomObject>
    <description>Manage the association between a credential defined in the context of the API Framework, logical environment where it can be used and the target Named Credential.</description>
    <label>CEP API Credential</label>
    <pluralLabel>CEP API Credentials</pluralLabel>
</CustomObject>

force-app/main/default/objects/CEP_ApiCredential__mdt/fields/ApiLogicalEnvironment__c.field-meta.xml
<CustomField>
    <fullName>ApiLogicalEnvironment__c</fullName>
    <label>API Logical Environment</label>
    <referenceTo>CEP_ApiLogicalEnvironment__mdt</referenceTo>
    <relationshipLabel>API Credentials</relationshipLabel>
    <relationshipName>ApiCredentials</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/CEP_ApiCredential__mdt/fields/ApiPath__c.field-meta.xml
<CustomField>
    <fullName>ApiPath__c</fullName>
    <label>API Path</label>
    <referenceTo>CEP_ApiPath__mdt</referenceTo>
    <relationshipLabel>API Credentials</relationshipLabel>
    <relationshipName>ApiCredentials</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/CEP_ApiHttpHeader__mdt/CEP_ApiHttpHeader__mdt.object-meta.xml
<CustomObject>
    <description>The list of Http Headers that are send when invoking the API method. The Header Value is a merge field that can be merged at runtime using the relatedObject or inputFieldMap parameters of the call() API method.</description>
    <label>CEP API Http Header</label>
    <pluralLabel>CEP API Http Headers</pluralLabel>
</CustomObject>

force-app/main/default/objects/CEP_ApiHttpHeader__mdt/fields/ApiMethod__c.field-meta.xml
<CustomField>
    <fullName>ApiMethod__c</fullName>
    <label>API Method</label>
    <referenceTo>CEP_ApiMethod__mdt</referenceTo>
    <relationshipLabel>API Http Headers</relationshipLabel>
    <relationshipName>ApiHttpHeaders</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/CEP_ApiHttpHeader__mdt/fields/HeaderName__c.field-meta.xml
<CustomField>
    <fullName>HeaderName__c</fullName>
    <label>Header Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEP_ApiHttpHeader__mdt/fields/HeaderValue__c.field-meta.xml
<CustomField>
    <fullName>HeaderValue__c</fullName>
    <inlineHelpText>Merge field values use the syntax {!fieldName}.</inlineHelpText>
    <label>Header Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEP_ApiLogicalEnvironment__mdt/CEP_ApiLogicalEnvironment__mdt.object-meta.xml
<CustomObject>
    <description>Definition of a logical environment. In CEP API Setting hierarchy custom setting it is set the target logical environment for the API calls.</description>
    <label>CEP API Logical Environment</label>
    <pluralLabel>CEP API Logical Environments</pluralLabel>
</CustomObject>

force-app/main/default/objects/CEP_ApiMethod__mdt/CEP_ApiMethod__mdt.object-meta.xml
<CustomObject>
    <description>An API method that is called from the API framework. In this entity it is defined the associated path, http method, input message template (using merge fields), mock output message and output deserializable apex class.</description>
    <label>CEP API Method</label>
    <pluralLabel>CEP API Methods</pluralLabel>
</CustomObject>

force-app/main/default/objects/CEP_ApiMethod__mdt/fields/ApiPath__c.field-meta.xml
<CustomField>
    <fullName>ApiPath__c</fullName>
    <label>API Path</label>
    <referenceTo>CEP_ApiPath__mdt</referenceTo>
    <relationshipLabel>API Methods</relationshipLabel>
    <relationshipName>ApiMethods</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/CEP_ApiMethod__mdt/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>application/json</fullName>
                <default>true</default>
                <label>application/json</label>
            </value>
            <value>
                <fullName>application/xml</fullName>
            </value>
            <value>
                <fullName>text/plain</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEP_ApiMethod__mdt/fields/HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>HttpMethod__c</fullName>
    <label>Http Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>HEAD</fullName>
            </value>
            <value>
                <fullName>OPTIONS</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEP_ApiMethod__mdt/fields/Input__c.field-meta.xml
<CustomField>
    <fullName>Input__c</fullName>
    <inlineHelpText>Merge field values use the syntax {!fieldName}.</inlineHelpText>
    <label>Input</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CEP_ApiMethod__mdt/fields/MockOutput__c.field-meta.xml
<CustomField>
    <fullName>MockOutput__c</fullName>
    <label>Mock Output</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CEP_ApiMethod__mdt/fields/OutputDeserializeClassName__c.field-meta.xml
<CustomField>
    <fullName>OutputDeserializeClassName__c</fullName>
    <label>Output Deserialize Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEP_ApiMethod__mdt/fields/SubPath__c.field-meta.xml
<CustomField>
    <fullName>SubPath__c</fullName>
    <inlineHelpText>Merge field values use the syntax {!fieldName}.</inlineHelpText>
    <label>Sub-Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEP_ApiMethod__mdt/fields/TimeoutOverride__c.field-meta.xml
<CustomField>
    <fullName>TimeoutOverride__c</fullName>
    <inlineHelpText>Override timeout (in seconds) for this method.</inlineHelpText>
    <label>Timeout Override</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CEP_ApiPath__mdt/CEP_ApiPath__mdt.object-meta.xml
<CustomObject>
    <description>A Path is a grouping of several Methods that share a common base path in the endpoint URL.</description>
    <label>CEP API Path</label>
    <pluralLabel>CEP API Paths</pluralLabel>
</CustomObject>

force-app/main/default/objects/CEP_ApiPath__mdt/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <inlineHelpText>Merge field values use the syntax {!fieldName}.</inlineHelpText>
    <label>Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEP_ApiSetting__c/CEP_ApiSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CEP API Settings</label>
</CustomObject>

force-app/main/default/classes/REP_CEP_Api.cls
/**
* @description    CEP Api Repository
* @testClass     
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Antonio Santos                23/08/2021          Created CEP Api Repository
* ------------------------------------------------------------------------------------ 
*/
public class REP_CEP_Api extends FW_SobjectRep implements IREP_CEP_Api {
    public static Map<Id,CEP_ApiLogicalEnvironment__mdt> logicalEnvironmentMap;
    public static Map<String,Id> logicalEnvironmentDevNameMap;

    public static Map<Id,CEP_ApiCredential__mdt> credentialMap;
    public static Map<String,Id> credentialEnvIdPathIdMap;

    public static Map<Id,CEP_ApiPath__mdt> pathMap;
    public static Map<Id,CEP_ApiMethod__mdt> methodMap;

    public static Map<String,Id> methodDevNameMap;

    public static Map<Id,CEP_ApiHttpHeader__mdt> httpHeaderMap;
    public static Map<Id,List<Id>> httpHeaderMethodIdMap;

    public static REP_CEP_Api repositoryInstance;

    public static CEP_ApiSetting__c apiSetting;

    public static REP_CEP_Api getInstance() {
        if (repositoryInstance == null) {
            repositoryInstance = new REP_CEP_Api();

            logicalEnvironmentMap = new Map<Id,CEP_ApiLogicalEnvironment__mdt>(
                [
                    SELECT Id, Label, DeveloperName FROM CEP_ApiLogicalEnvironment__mdt
                ]
            );

            logicalEnvironmentDevNameMap = new Map<String,Id>();

            for (CEP_ApiLogicalEnvironment__mdt logicalEnvironment : logicalEnvironmentMap.values()) {
                logicalEnvironmentDevNameMap.put(logicalEnvironment.DeveloperName, logicalEnvironment.Id);
            }

            credentialMap = new Map<Id,CEP_ApiCredential__mdt>(
                [
                    SELECT Id, ApiLogicalEnvironment__c, ApiPath__c, NamedCredential__c FROM CEP_ApiCredential__mdt
                ]
            );
            credentialEnvIdPathIdMap = new Map<String,Id>();

            for (CEP_ApiCredential__mdt credential : credentialMap.values()) {
                credentialEnvIdPathIdMap.put(credential.ApiLogicalEnvironment__c + ';' + credential.ApiPath__c, credential.Id);
            }

            pathMap = new Map<Id,CEP_ApiPath__mdt>(
                [
                    SELECT Id, Label, Path__c FROM CEP_ApiPath__mdt
                ]
            );

            methodMap = new Map<Id,CEP_ApiMethod__mdt>(
                [
                    SELECT Id, Label, DeveloperName, ApiPath__c, ContentType__c, HttpMethod__c, Input__c, MockOutput__c, OutputDeserializeClassName__c, SubPath__c, TimeoutOverride__c FROM CEP_ApiMethod__mdt
                ]
            );

            methodDevNameMap = new Map<String,Id>();

            for (CEP_ApiMethod__mdt method : methodMap.values()) {
                methodDevNameMap.put(method.DeveloperName, method.Id);
            }

            httpHeaderMap = new Map<Id,CEP_ApiHttpHeader__mdt>(
                [
                    SELECT Id, ApiMethod__c, HeaderName__c, HeaderValue__c FROM CEP_ApiHttpHeader__mdt
                ]
            );

            httpHeaderMethodIdMap = new Map<Id,List<Id>>();

            for (CEP_ApiHttpHeader__mdt header : httpHeaderMap.values()) {
                if (!httpHeaderMethodIdMap.containsKey(header.ApiMethod__c)) {
                    httpHeaderMethodIdMap.put(header.ApiMethod__c, new List<Id>());
                }

                httpHeaderMethodIdMap.get(header.ApiMethod__c).add(header.Id);
            }

            apiSetting = CEP_ApiSetting__c.getInstance();
        }

        return repositoryInstance;
    }

    public CEP_ApiMethod__mdt getMethodByDeveloperName(String developerName) {
        Id methodId = methodDevNameMap.get(developerName);

        if (methodId != null) {
            return methodMap.get(methodId);
        } else {
            return null;
        }
    }

    public CEP_ApiLogicalEnvironment__mdt getLogicalEnvironmentByDeveloperName(String developerName) {
        Id logicalEnvironmentId = logicalEnvironmentDevNameMap.get(developerName);

        if (logicalEnvironmentId != null) {
            return logicalEnvironmentMap.get(logicalEnvironmentId);
        } else {
            return null;
        }
    }

    public CEP_ApiCredential__mdt getCredentialByEnvIdPathId(Id logicalEnvironmentId, Id pathId) {
        Id credentialId = credentialEnvIdPathIdMap.get(logicalEnvironmentId + ';' + pathId);

        if (credentialId != null) {
            return credentialMap.get(credentialId);
        } else {
            return null;
        }
    }

    public CEP_ApiPath__mdt getPathById(Id pathId) {
        return pathMap.get(pathId);
    }

    public List<CEP_ApiHttpHeader__mdt> getHttpHeaderByMethodId(Id methodId) {
        List<Id> httpHeaderIdList = httpHeaderMethodIdMap.get(methodId);
        List<CEP_ApiHttpHeader__mdt> resultList = new List<CEP_ApiHttpHeader__mdt>();

        if (httpHeaderIdList != null) {
            for (Id httpHeaderId : httpHeaderIdList) {
                resultList.add(httpHeaderMap.get(httpHeaderId));
            }

            return resultList;
        } else {
            return null;
        }
    }

    public CEP_ApiSetting__c getSetting() {
        return apiSetting;
    }
}