force-app/main/default/objects/Quote/fields/CompetitiveBandFuel__c.field-meta.xml
<CustomField>
    <fullName>CompetitiveBandFuel__c</fullName>
    <description>Competitive band chosen by the agent. This field will define the approval process needed.</description>
    <label>Competitive Band</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CO1</fullName>
            </value>
            <value>
                <fullName>CO2</fullName>
            </value>
            <value>
                <fullName>CO3</fullName>
            </value>
            <value>
                <fullName>CO4</fullName>
            </value>
            <value>
                <fullName>CO5</fullName>
            </value>
            <value>
                <fullName>CO6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/FuelVolumeBand__c.field-meta.xml
<CustomField>
    <fullName>FuelVolumeBand__c</fullName>
    <description>Defined based on the Total Potential Fuel Volume value</description>
    <inlineHelpText>Filled based on Total Potential Fuel Volume</inlineHelpText>
    <label>Fuel Volume Band</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>QuoteType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>V10</fullName>
            </value>
            <value>
                <fullName>V30</fullName>
            </value>
            <value>
                <fullName>V60</fullName>
            </value>
            <value>
                <fullName>V100</fullName>
            </value>
            <value>
                <fullName>V150</fullName>
            </value>
            <value>
                <fullName>V250</fullName>
            </value>
            <value>
                <fullName>V500</fullName>
            </value>
            <value>
                <fullName>V750</fullName>
            </value>
            <value>
                <fullName>V1000</fullName>
            </value>
            <value>
                <fullName>VM</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/QuoteType__c.field-meta.xml
<CustomField>
    <fullName>QuoteType__c</fullName>
    <description>This field presents the quote type that will define the mandatory product for each type and the price type associated</description>
    <label>Quote Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuoteTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/QuoteTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fleet PP</fullName>
        <default>true</default>
        <label>Fleet PP</label>
    </customValue>
    <customValue>
        <fullName>Fleet LP</fullName>
    </customValue>
    <customValue>
        <fullName>Int CRT LP</fullName>
    </customValue>
    <customValue>
        <fullName>Nat CRT LP</fullName>
    </customValue>
    <customValue>
        <fullName>Int Agents LP</fullName>
    </customValue>
    <customValue>
        <fullName>E-Mobility</fullName>
    </customValue>
    <customValue>
        <fullName>Smatrics</fullName>
        <isActive>false</isActive>
        <label>Smatrics</label>
    </customValue>
    <masterLabel>Quote Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/REP_QuoteLineItem.cls
/**
* @description   QuoteLineItem Repository
* @testClass     REP_QuoteLineItemTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro                29/07/2021          Created QuoteLineItem Repository
* ------------------------------------------------------------------------------------ 
*/
public class REP_QuoteLineItem extends FW_SobjectRep implements IREP_QuoteLineItem{
    public List<QuoteLineItem> getQuoteLineItemInfo(Set<Id> quoteLineItemsIdSet){
        return [SELECT Id, PricebookEntry.Product2Id, Quote.QuoteType__c, Quote.CompetitiveBandFuel__c, Quote.FuelVolumeBand__c 
                FROM QuoteLineItem 
                WHERE Quote.RecordTypeId = :DO_Quote.QUOTE_CARDS_RECORDTYPE_ID 
                AND Id IN :quoteLineItemsIdSet];
    }
}