force-app/main/default/objects/Quote/fields/FuelVolumeBand__c.field-meta.xml
<CustomField>
    <fullName>FuelVolumeBand__c</fullName>
    <description>Defined based on the Total Potential Fuel Volume value</description>
    <inlineHelpText>Filled based on Total Potential Fuel Volume</inlineHelpText>
    <label>Fuel Volume Band</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>QuoteType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>V10</fullName>
            </value>
            <value>
                <fullName>V30</fullName>
            </value>
            <value>
                <fullName>V60</fullName>
            </value>
            <value>
                <fullName>V100</fullName>
            </value>
            <value>
                <fullName>V150</fullName>
            </value>
            <value>
                <fullName>V250</fullName>
            </value>
            <value>
                <fullName>V500</fullName>
            </value>
            <value>
                <fullName>V750</fullName>
            </value>
            <value>
                <fullName>V1000</fullName>
            </value>
            <value>
                <fullName>VM</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/QuoteType__c.field-meta.xml
<CustomField>
    <fullName>QuoteType__c</fullName>
    <description>This field presents the quote type that will define the mandatory product for each type and the price type associated</description>
    <label>Quote Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuoteTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/TotalPotentialFuelVolume__c.field-meta.xml
<CustomField>
    <fullName>TotalPotentialFuelVolume__c</fullName>
    <description>Total quantity of diesel and gasoline based on quantity identified in the Opportunity</description>
    <label>Total Potential Fuel Volume [kL/y]</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/QuoteTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fleet PP</fullName>
        <default>true</default>
        <label>Fleet PP</label>
    </customValue>
    <customValue>
        <fullName>Fleet LP</fullName>
    </customValue>
    <customValue>
        <fullName>Int CRT LP</fullName>
    </customValue>
    <customValue>
        <fullName>Nat CRT LP</fullName>
    </customValue>
    <customValue>
        <fullName>Int Agents LP</fullName>
    </customValue>
    <customValue>
        <fullName>E-Mobility</fullName>
    </customValue>
    <customValue>
        <fullName>Smatrics</fullName>
        <isActive>false</isActive>
        <label>Smatrics</label>
    </customValue>
    <masterLabel>Quote Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TW_Quote_PerfilVolumeFuelBand.cls
/**
* @description   Based on the value of the field "Total Potential Fuel Volume" define the value of the field "Fuel Volume Band" 
* @testClass     TW_Quote_PerfilVolumeFuelBandTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                     Date                Description 
* Carolina Resende              27/08/2021          Created Perfil Volume Fuel Band
* João Alencar                  23/09/2021          added validation on the quote type E-Mobility to fix bug 38918 on US35933
* ------------------------------------------------------------------------------------ 
*/

public class TW_Quote_PerfilVolumeFuelBand {
    
    public TW_Quote_PerfilVolumeFuelBand(){}
    
    public void execute(List<Quote> quoteList, Map<Id,Quote> quoteOldMap){ 
        //check all Quotes in the List
        for(Quote quoteToUpdate : quoteList){
            if( quoteOldMap == null || (quoteOldMap.get(quoteToUpdate.Id).TotalPotentialFuelVolume__c != quoteToUpdate.TotalPotentialFuelVolume__c) ){
                populateFuelVolumeBand(quoteToUpdate);                  
            }     
        }
    }
    
    private void populateFuelVolumeBand(Quote quoteToUpdate){
        if(quoteToUpdate.QuoteType__c == DO_Quote.QUOTE_TYPE_EMOBILITY || string.isBlank(String.valueOf(quoteToUpdate.TotalPotentialFuelVolume__c))){
            quoteToUpdate.FuelVolumeBand__c = null;
        }
        else if(quoteToUpdate.TotalPotentialFuelVolume__c <= 10){
            quoteToUpdate.FuelVolumeBand__c = DO_Quote.QUOTE_VOLUMEFUELBAND_V10;
        }
        else if(quoteToUpdate.TotalPotentialFuelVolume__c > 10 && quoteToUpdate.TotalPotentialFuelVolume__c <=30){
            quoteToUpdate.FuelVolumeBand__c = DO_Quote.QUOTE_VOLUMEFUELBAND_V30;
        }
        else if(quoteToUpdate.TotalPotentialFuelVolume__c >30 && quoteToUpdate.TotalPotentialFuelVolume__c <=60){
            quoteToUpdate.FuelVolumeBand__c = DO_Quote.QUOTE_VOLUMEFUELBAND_V60;
        }
        else if(quoteToUpdate.TotalPotentialFuelVolume__c >60 && quoteToUpdate.TotalPotentialFuelVolume__c <=100){
            quoteToUpdate.FuelVolumeBand__c = DO_Quote.QUOTE_VOLUMEFUELBAND_V100;
        } 
        else if(quoteToUpdate.TotalPotentialFuelVolume__c >100 && quoteToUpdate.TotalPotentialFuelVolume__c <=150){
            quoteToUpdate.FuelVolumeBand__c = DO_Quote.QUOTE_VOLUMEFUELBAND_V150;
        }
        else if(quoteToUpdate.TotalPotentialFuelVolume__c >150 && quoteToUpdate.TotalPotentialFuelVolume__c <=250){
            quoteToUpdate.FuelVolumeBand__c = DO_Quote.QUOTE_VOLUMEFUELBAND_V250;
        }
        else if(quoteToUpdate.TotalPotentialFuelVolume__c >250 && quoteToUpdate.TotalPotentialFuelVolume__c <=500){
            quoteToUpdate.FuelVolumeBand__c = DO_Quote.QUOTE_VOLUMEFUELBAND_V500;
        }
        else if(quoteToUpdate.TotalPotentialFuelVolume__c >500 && quoteToUpdate.TotalPotentialFuelVolume__c <=750){
            quoteToUpdate.FuelVolumeBand__c = DO_Quote.QUOTE_VOLUMEFUELBAND_V750;
        }
        else if(quoteToUpdate.TotalPotentialFuelVolume__c >750 && quoteToUpdate.TotalPotentialFuelVolume__c <=1000){
            quoteToUpdate.FuelVolumeBand__c = DO_Quote.QUOTE_VOLUMEFUELBAND_V1000;
        }
        else{
            quoteToUpdate.FuelVolumeBand__c = DO_Quote.QUOTE_VOLUMEFUELBAND_VM;
        }
    }
}