force-app/main/default/objects/Quote/fields/PriceType__c.field-meta.xml
<CustomField>
    <fullName>PriceType__c</fullName>
    <description>Defined based on the Total Potential Fuel Volume value</description>
    <formula>IF(ISPICKVAL(QuoteType__c, &apos;Fleet PP&apos;) , &apos;Pump Price&apos;, IF(ISPICKVAL(QuoteType__c, &apos;E-Mobility&apos;) , &apos;N/A&apos;, &apos;List Price&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QuoteType__c.field-meta.xml
<CustomField>
    <fullName>QuoteType__c</fullName>
    <description>This field presents the quote type that will define the mandatory product for each type and the price type associated</description>
    <label>Quote Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuoteTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/QuoteTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fleet PP</fullName>
        <default>true</default>
        <label>Fleet PP</label>
    </customValue>
    <customValue>
        <fullName>Fleet LP</fullName>
    </customValue>
    <customValue>
        <fullName>Int CRT LP</fullName>
    </customValue>
    <customValue>
        <fullName>Nat CRT LP</fullName>
    </customValue>
    <customValue>
        <fullName>Int Agents LP</fullName>
    </customValue>
    <customValue>
        <fullName>E-Mobility</fullName>
    </customValue>
    <customValue>
        <fullName>Smatrics</fullName>
        <isActive>false</isActive>
        <label>Smatrics</label>
    </customValue>
    <masterLabel>Quote Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TW_Quote_PerfilDataFromQuoteType.cls
/**
* @description   worker class to change disccount on QuoteLineItems depending on discount criteria
* @testClass     TW_QuoteDiscountChangeTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                     Date                Description 
* Carolina Resende              27/08/2021          
* ------------------------------------------------------------------------------------ 
*/

public class TW_Quote_PerfilDataFromQuoteType {
    
    public TW_Quote_PerfilDataFromQuoteType(){
        
    }
    /*
* @TestVisible
private TW_Quote_PerfilDataFromQuoteType(){

}
*/
    public void execute(List<Quote> quoteList){
        //check all Quotes in the List
        /*for(Quote quoteToUpdate : quoteList){
            if(quoteToUpdate.QuoteType__c == 'Fleet PP'){
                quoteToUpdate.PriceType__c = 'Pump Price';
            }
            else if(quoteToUpdate.QuoteType__c == 'E-Mobility'){
                quoteToUpdate.PriceType__c = 'N/A';
            }
            else{
                quoteToUpdate.PriceType__c = 'List Price';
            }
            
        }*/
    }
    
}