force-app/main/default/objects/Quote/fields/QuoteType__c.field-meta.xml
<CustomField>
    <fullName>QuoteType__c</fullName>
    <description>This field presents the quote type that will define the mandatory product for each type and the price type associated</description>
    <label>Quote Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuoteTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DiscountValue__c.field-meta.xml
<CustomField>
    <fullName>DiscountValue__c</fullName>
    <description>Field to save the discount value of the Quote Line Item</description>
    <label>Discount Value</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/QuoteTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fleet PP</fullName>
        <default>true</default>
        <label>Fleet PP</label>
    </customValue>
    <customValue>
        <fullName>Fleet LP</fullName>
    </customValue>
    <customValue>
        <fullName>Int CRT LP</fullName>
    </customValue>
    <customValue>
        <fullName>Nat CRT LP</fullName>
    </customValue>
    <customValue>
        <fullName>Int Agents LP</fullName>
    </customValue>
    <customValue>
        <fullName>E-Mobility</fullName>
    </customValue>
    <customValue>
        <fullName>Smatrics</fullName>
        <isActive>false</isActive>
        <label>Smatrics</label>
    </customValue>
    <masterLabel>Quote Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TW_QuoteLineItemChangeRecordTypeTest.cls
@isTest
public with sharing class TW_QuoteLineItemChangeRecordTypeTest {
    static fflib_ApexMocks mocks = new fflib_ApexMocks();
    
    @isTest


    private static void TW_QuoteLineItemChangeRecordTypeTest() {

        IREP_Quote quoteRepository = (REP_Quote)mocks.mock(REP_Quote.class);
        
        List<Quote> listQuote = new List<Quote>();
        listQuote.add(
            new Quote(
                Id = fflib_IDGenerator.generate(Quote.sObjectType),
                QuoteType__c = 'Fleet PP',
                RecordTypeId = DO_Quote.QUOTE_CARDS_RECORDTYPE_ID
            )  
        );
        List<QuoteLineItem> listQuoteLineItem = new List<QuoteLineItem>();
        List<QuoteLineItem> listQuoteLineItemUpdated = new List<QuoteLineItem>();
        listQuoteLineItem.add(
            new QuoteLineItem(
                Id = fflib_IDGenerator.generate(QuoteLineItem.sObjectType),
                QuoteId = listQuote[0].Id

            )  
        ); 

        listQuoteLineItemUpdated.add(
            new QuoteLineItem(
                Id = listQuoteLineItem[0].Id,
                DiscountValue__c = 1
            )
        );
        
        List<Quote> newlistQuote = (List<Quote>)fflib_ApexMocksUtils.makeRelationship(
                List<Quote>.class,
                listQuote,
                QuoteLineItem.QuoteId,
            	new List<List<QuoteLineItem>> {listQuoteLineItem}
        );
        mocks.startStubbing();
        
        // mocks.when(quoteRepository.getQuoteByID((Set<Id>) fflib_match.anyObject())).thenReturn(listQuote);
        
        mocks.stopStubbing();

        TW_QuoteLineItemChangeRecordType jobExecutionWorker = new TW_QuoteLineItemChangeRecordType();
        jobExecutionWorker = new TW_QuoteLineItemChangeRecordType(quoteRepository);
        
        jobExecutionWorker.execute(listQuoteLineItemUpdated,new Map<ID,QuoteLineItem>(listQuoteLineItem));

        
        // ((IREP_Quote)mocks.verify(quoteRepository, 1)).getQuoteByID((Set<Id>) fflib_match.anyObject());
    }
}