force-app/main/default/objects/CEP_Configuration__c/CEP_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>custom setting for diverse configuration</description>
    <label>CEP Configuration</label>
</CustomObject>

force-app/main/default/objects/CEP_Configuration__c/fields/CardsPricebookId__c.field-meta.xml
<CustomField>
    <fullName>CardsPricebookId__c</fullName>
    <label>Cards Pricebook Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TW_Opportunity_FillPricebookTest.cls
@isTest
public with sharing class TW_Opportunity_FillPricebookTest {
    static fflib_ApexMocks mocks = new fflib_ApexMocks();
    
    @testSetup
    private static void makeData(){
        Pricebook2 pricebook = new Pricebook2();
        pricebook.Name = 'CARDS TESTE';
        insert pricebook;

        CEP_Configuration__c setting = new CEP_Configuration__c();
        setting.CardsPricebookId__c = pricebook.Id;
        insert setting;
    }
    
    @isTest
    private static void TW_Opportunity_FillPricebookTest() {
        Test.startTest();

        List<Opportunity> listOpportunity = new List<Opportunity>();
        listOpportunity.add(
            new Opportunity(
                Id = fflib_IDGenerator.generate(Opportunity.sObjectType),
                RecordTypeId = DO_Opportunity.OPPORTUNITY_CARDS_RECORDTYPE_ID
            )  
        );

        mocks.startStubbing();
        mocks.stopStubbing();

        TW_Opportunity_FillPricebook jobExecutionWorker = new TW_Opportunity_FillPricebook();
        jobExecutionWorker = new TW_Opportunity_FillPricebook();
        
        jobExecutionWorker.execute(listOpportunity);

        Test.stopTest();
    }
}