force-app/main/default/objects/CEP_Configuration__c/CEP_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>custom setting for diverse configuration</description>
    <label>CEP Configuration</label>
</CustomObject>

force-app/main/default/objects/CEP_Configuration__c/fields/CardsPricebookId__c.field-meta.xml
<CustomField>
    <fullName>CardsPricebookId__c</fullName>
    <label>Cards Pricebook Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TW_Opportunity_FillPricebook.cls
/**
@description    worker class to fill Cards pricebook on Opportunity
@testClass      TW_Opportunity_FillPricebookTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description  
* Guilherme Charro                21/07/2021          Created the class
* ------------------------------------------------------------------------------------        
*/
public with sharing class TW_Opportunity_FillPricebook {
    public void execute(List<Opportunity> opportunityList) {
        CEP_Configuration__c orgDefaults = CEP_Configuration__c.getOrgDefaults();
        Id pricebookId = orgDefaults.CardsPricebookId__c;
        for (Opportunity oppInserted : opportunityList) {
            if (oppInserted.RecordTypeId == DO_Opportunity.OPPORTUNITY_CARDS_RECORDTYPE_ID && !String.isBlank(pricebookId)) {
                oppInserted.Pricebook2Id = pricebookId;
            }
        }
    }
}