force-app/main/default/objects/CEPFPSEmailBranding__mdt/CEPFPSEmailBranding__mdt.object-meta.xml
<CustomObject>
    <description>Metadata that will control the branding layout of the emails sent by the fps portal.</description>
    <label>CEP FPS Email Branding</label>
    <pluralLabel>CEP FPS Email Brandings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CEPFPSEmailBranding__mdt/fields/BrandingPrimaryColor__c.field-meta.xml
<CustomField>
    <fullName>BrandingPrimaryColor__c</fullName>
    <defaultValue>&apos;#003366&apos;</defaultValue>
    <description>The color used in the whole branding as primary color</description>
    <label>Branding Primary Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEPFPSEmailBranding__mdt/fields/ButtonsColor__c.field-meta.xml
<CustomField>
    <fullName>ButtonsColor__c</fullName>
    <description>main color of the buttons used in the template</description>
    <label>Buttons Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEPFPSEmailBranding__mdt/fields/ButtonsTextColor__c.field-meta.xml
<CustomField>
    <fullName>ButtonsTextColor__c</fullName>
    <description>main color of the text inside the buttons used in the template</description>
    <label>Buttons Text Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEPFPSEmailBranding__mdt/fields/CopyrightText__c.field-meta.xml
<CustomField>
    <fullName>CopyrightText__c</fullName>
    <description>text containing the copyright displayed in the bottom of the email template</description>
    <label>Copyright Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEPFPSEmailBranding__mdt/fields/CountryIsoCode__c.field-meta.xml
<CustomField>
    <fullName>CountryIsoCode__c</fullName>
    <description>country to apply this branding</description>
    <label>Country Iso Code</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CEPFPSEmailBranding__mdt/fields/EnergyFlashColor__c.field-meta.xml
<CustomField>
    <fullName>EnergyFlashColor__c</fullName>
    <description>The color used in the energy line below the primary color top bar of the branding</description>
    <label>Energy Flash Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEPFPSEmailBranding__mdt/fields/FontFamily__c.field-meta.xml
<CustomField>
    <fullName>FontFamily__c</fullName>
    <description>font family that will be used in all the email template</description>
    <label>Font Family</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEPFPSEmailBranding__mdt/fields/FontSize__c.field-meta.xml
<CustomField>
    <fullName>FontSize__c</fullName>
    <description>This field will be used to define the font size for the button depending on the Country</description>
    <label>Font Size</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEPFPSEmailBranding__mdt/fields/FooterLogoImage__c.field-meta.xml
<CustomField>
    <fullName>FooterLogoImage__c</fullName>
    <description>The unique name of the document containing the logo that will be used in the Footer of the email message</description>
    <label>Footer Logo Image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEPFPSEmailBranding__mdt/fields/FooterURL__c.field-meta.xml
<CustomField>
    <fullName>FooterURL__c</fullName>
    <description>URL that is displayed in the footer of the template</description>
    <label>Footer URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEPFPSEmailBranding__mdt/fields/HeaderLogoImage__c.field-meta.xml
<CustomField>
    <fullName>HeaderLogoImage__c</fullName>
    <description>The unique name of the document containing the logo that will be used in the header of the email message</description>
    <label>Header Logo Image</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEPFPSEmailBranding__mdt/fields/ImprintText__c.field-meta.xml
<CustomField>
    <fullName>ImprintText__c</fullName>
    <description>Text that is displayed as imprint in the bottom of the email template</description>
    <label>Imprint Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEPFPSEmailBranding__mdt/fields/ImprintURL__c.field-meta.xml
<CustomField>
    <fullName>ImprintURL__c</fullName>
    <description>URL of the Imprint text</description>
    <label>Imprint URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEPFPSEmailBranding__mdt/fields/LogoHeight__c.field-meta.xml
<CustomField>
    <fullName>LogoHeight__c</fullName>
    <description>Field to define the Logo Height</description>
    <label>Logo Height</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEPFPSEmailBranding__mdt/fields/LogoWidth__c.field-meta.xml
<CustomField>
    <fullName>LogoWidth__c</fullName>
    <description>Field to define the Logo Width</description>
    <label>Logo Width</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEPFPSEmailBranding__mdt/fields/TelephoneContact__c.field-meta.xml
<CustomField>
    <fullName>TelephoneContact__c</fullName>
    <description>Telephone number that is displayed in the bottom of the email template</description>
    <label>Telephone Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/REP_CEPFPSEmailBranding.cls
/**
* @description   CEPFPSEmailBranding Repository
* @testClass     REP_CEPFPSEmailBrandingTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Hugo Rodrigues               15/11/2021         Created CEPFPSEmailBranding Repository
* ------------------------------------------------------------------------------------ 
*/
public with sharing class REP_CEPFPSEmailBranding extends FW_SobjectRep implements IREP_CEPFPSEmailBranding{
    public CEPFPSEmailBranding__mdt getCEPFPSEmailBranding(String CustomerCountry){
        return [SELECT Id, DeveloperName, MasterLabel, Language, NamespacePrefix, Label, QualifiedApiName, CountryIsoCode__c, LogoHeight__c, LogoWidth__c,
        HeaderLogoImage__c, BrandingPrimaryColor__c, EnergyFlashColor__c, FontFamily__c, ButtonsColor__c, ButtonsTextColor__c, FooterURL__c, CopyrightText__c,
        TelephoneContact__c, ImprintText__c, ImprintURL__c, FooterLogoImage__c, FontSize__c FROM CEPFPSEmailBranding__mdt Where CountryIsoCode__c=:CustomerCountry LIMIT 1];
    }
}