force-app/main/default/objects/Account/fields/BillingEmail__c.field-meta.xml
<CustomField>
    <fullName>BillingEmail__c</fullName>
    <description>Email that is associated to the SAP Account</description>
    <label>Billing Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>SAP Invoices related to orders or not</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Customer account related, updated via SAP</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingEmail__c.field-meta.xml
<CustomField>
    <fullName>BillingEmail__c</fullName>
    <description>Email that is associated to the SAP Account</description>
    <label>Billing Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/TW_Invoice_FillComplementaryFields.cls
/**
@description    worker class to automatically fill Invoice Source
@testClass      TW_Invoice_ComplementaryFieldsTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description  
* Carolina Resende              25/11/2021          Created the class
* ------------------------------------------------------------------------------------        
*/
public with sharing class TW_Invoice_FillComplementaryFields {

private IREP_Account accountRepository;

public TW_Invoice_FillComplementaryFields(){
    this.accountRepository = new REP_Account();
}

@TestVisible
private TW_Invoice_FillComplementaryFields(IREP_Account accountRepository){
    this.accountRepository = accountRepository;
}

public void execute(List<Invoice__c> invoiceList) {
    Set<Id> accountIdSet = new Set<Id>();
    Map<Id,Account> accountMapByID = new Map<Id,Account>();
    for (Invoice__c invoice : invoiceList) {
        accountIdSet.add(invoice.Account__c); 
    }
    if (!accountIdSet.isEmpty()) {
        accountMapByID = accountRepository.getAccountFromInvoice(accountIdSet);
    }
    for (Invoice__c invoice : invoiceList) {
        invoice.BillingEmail__c = accountMapByID.get(invoice.Account__c).BillingEmail__c;
    }
} 
}