force-app/main/default/objects/Account/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Displays the name of OMV entity related to the company code. Example OMV Downstream GmbH</description>
    <label>OMV Entity</label>
    <referenceTo>CompanyCode__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Default language for communication with the customer account</description>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerLanguage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CompanyCode__c/CompanyCode__c.object-meta.xml
<CustomObject>
    <description>This datatable is used for all business lines, to allow aggregating each Customer (Account) to the corresponding OMV subsidiary</description>
    <label>Company Code</label>
    <nameField>
        <label>Company Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyCode__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Identification of OMV subsidiary country</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerCountry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CompanyCode__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Identification of default language for the OMV subsidiary customers</description>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerLanguage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CustomerCountry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CZ</fullName>
        <label>Czech Republic</label>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
        <label>Hungary</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
        <label>Slovakia</label>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
        <label>Bulgaria</label>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
        <label>Austria</label>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
        <label>Moldova</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <label>Romania</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <label>Croatia</label>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
        <label>Bosnia</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Poland</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
        <label>Turkey</label>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
        <label>Russia</label>
    </customValue>
    <customValue>
        <fullName>SH</fullName>
        <label>Serbia</label>
    </customValue>
    <customValue>
        <fullName>SL</fullName>
        <label>Slovenia</label>
    </customValue>
    <customValue>
        <fullName>Hungarian</fullName>
        <isActive>false</isActive>
        <label>Hungarian</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
        <isActive>false</isActive>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>Slovak</fullName>
        <isActive>false</isActive>
        <label>Slovak</label>
    </customValue>
    <customValue>
        <fullName>Romanian</fullName>
        <isActive>false</isActive>
        <label>Romanian</label>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
        <isActive>false</isActive>
        <label>Bulgarian</label>
    </customValue>
    <customValue>
        <fullName>German</fullName>
        <isActive>false</isActive>
        <label>German</label>
    </customValue>
    <description>Global value set to store working languages for OMV CEP business lines. Available languages should match the activated languages in the Translation Language Settings.</description>
    <masterLabel>Customer Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CustomerLanguage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BG</fullName>
        <label>Bulgarian</label>
    </customValue>
    <customValue>
        <fullName>CS</fullName>
        <label>Czech</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <label>German</label>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
        <label>Hungarian</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <label>Romanian</label>
    </customValue>
    <customValue>
        <fullName>SR</fullName>
        <label>Serbian</label>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
        <label>Slovak</label>
    </customValue>
    <customValue>
        <fullName>SL</fullName>
        <label>Slovenian</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <label>Croatian</label>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
        <label>Bosnian</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Polish</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italian</label>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
        <label>Turkish</label>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
        <label>Russian</label>
    </customValue>
    <customValue>
        <fullName>ro_MD</fullName>
        <label>Moldovan</label>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
        <isActive>false</isActive>
        <label>Moldova</label>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
        <isActive>false</isActive>
        <label>Austria</label>
    </customValue>
    <masterLabel>Customer Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TW_Account_FillComplementaryFieldsTest.cls
/**
@author Guilherme Charro
@date   08/09/2021
@description Test class for TW_Account_FillComplementaryFields
@TestClass         
Modification Log:
----------------------------------------------------------------------------------------------------
Developer                       Date                Description                           Coverage
----------------------------------------------------------------------------------------------------
Guilherme Charro                08/09/2021         Original Version                         100
*/
@isTest
public with sharing class TW_Account_FillComplementaryFieldsTest {
    static fflib_ApexMocks mocks = new fflib_ApexMocks();

    @isTest
    static void TW_Account_FillComplementaryFieldsTest() {
        IREP_CompanyCode companyCodeRepository = (REP_CompanyCode)mocks.mock(REP_CompanyCode.class);

        List<CompanyCode__c> companyCodeList = new List<CompanyCode__c>{
            new CompanyCode__c(
                Id = fflib_IDGenerator.generate(CompanyCode__c.sObjectType),
                Country__c = 'RO',
                Language__c = 'Romanian',
                CurrencyIsoCode = 'USD'
            ),
            new CompanyCode__c(
                Id = fflib_IDGenerator.generate(CompanyCode__c.sObjectType),
                Country__c = 'AT',
                Language__c = 'German',
                CurrencyIsoCode = 'EUR'
            )
        };

        List<Account> accountList = new List<Account>{
            new Account(
                Id = fflib_IDGenerator.generate(Account.sObjectType),
                CompanyCode__c = companyCodeList[0].Id,
                CompanyCode__r = companyCodeList[0],
                CurrencyIsoCode = 'MDL',
                Phone = '123123123'
            ),
            new Account(
                Id = fflib_IDGenerator.generate(Account.sObjectType),
                CompanyCode__c = companyCodeList[1].Id,
                CompanyCode__r = companyCodeList[1],
                CurrencyIsoCode = 'MDL',
                Phone = '456456456'
            ),
            new Account(
                Id = fflib_IDGenerator.generate(Account.sObjectType)
            )    
        };

        accountList[0] = (Account)fflib_ApexMocksUtils.setReadOnlyFields(
            accountList[0],
            Account.class,
            new Map<SObjectField, Object> {Account.RecordTypeId => DO_Account.ACCOUNT_RECORDTYPEID_CEPCARDS}
        );

        accountList[1] = (Account)fflib_ApexMocksUtils.setReadOnlyFields(
            accountList[1],
            Account.class,
            new Map<SObjectField, Object> {Account.RecordTypeId => DO_Account.ACCOUNT_RECORDTYPEID_CEPCARDS}
        );
        
        accountList[2] = (Account)fflib_ApexMocksUtils.setReadOnlyFields(
            accountList[2],
            Account.class,
            new Map<SObjectField, Object> {Account.RecordTypeId => DO_Account.ACCOUNT_RECORDTYPEID_CEPCARDS}
        );

        mocks.startStubbing();
        mocks.when(companyCodeRepository.getCompanyCodeInfo((Set<Id>) fflib_match.anyObject())).thenReturn(companyCodeList);
        mocks.stopStubbing();

        TW_Account_FillComplementaryFields jobExecutionWorker = new TW_Account_FillComplementaryFields();
        jobExecutionWorker = new TW_Account_FillComplementaryFields(companyCodeRepository);
        
        jobExecutionWorker.execute(accountList, null);

        ((IREP_CompanyCode)mocks.verify(companyCodeRepository, 1)).getCompanyCodeInfo((Set<Id>) fflib_match.anyObject());
    }
}