force-app/main/default/objects/Account/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Displays the name of OMV entity related to the company code. Example OMV Downstream GmbH</description>
    <label>OMV Entity</label>
    <referenceTo>CompanyCode__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CTITechnicalPhone__c.field-meta.xml
<CustomField>
    <fullName>CTITechnicalPhone__c</fullName>
    <description>Technical field that stores the 7 digits of the (Field Name) so CTI can search the number in the Global Search</description>
    <label>Phone</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Default language for communication with the customer account</description>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerLanguage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CompanyCode__c/CompanyCode__c.object-meta.xml
<CustomObject>
    <description>This datatable is used for all business lines, to allow aggregating each Customer (Account) to the corresponding OMV subsidiary</description>
    <label>Company Code</label>
    <nameField>
        <label>Company Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyCode__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Identification of OMV subsidiary country</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerCountry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CompanyCode__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Identification of default language for the OMV subsidiary customers</description>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerLanguage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CustomerCountry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CZ</fullName>
        <label>Czech Republic</label>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
        <label>Hungary</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
        <label>Slovakia</label>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
        <label>Bulgaria</label>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
        <label>Austria</label>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
        <label>Moldova</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <label>Romania</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <label>Croatia</label>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
        <label>Bosnia</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Poland</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
        <label>Turkey</label>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
        <label>Russia</label>
    </customValue>
    <customValue>
        <fullName>SH</fullName>
        <label>Serbia</label>
    </customValue>
    <customValue>
        <fullName>SL</fullName>
        <label>Slovenia</label>
    </customValue>
    <customValue>
        <fullName>Hungarian</fullName>
        <isActive>false</isActive>
        <label>Hungarian</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
        <isActive>false</isActive>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>Slovak</fullName>
        <isActive>false</isActive>
        <label>Slovak</label>
    </customValue>
    <customValue>
        <fullName>Romanian</fullName>
        <isActive>false</isActive>
        <label>Romanian</label>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
        <isActive>false</isActive>
        <label>Bulgarian</label>
    </customValue>
    <customValue>
        <fullName>German</fullName>
        <isActive>false</isActive>
        <label>German</label>
    </customValue>
    <description>Global value set to store working languages for OMV CEP business lines. Available languages should match the activated languages in the Translation Language Settings.</description>
    <masterLabel>Customer Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CustomerLanguage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BG</fullName>
        <label>Bulgarian</label>
    </customValue>
    <customValue>
        <fullName>CS</fullName>
        <label>Czech</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <label>German</label>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
        <label>Hungarian</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <label>Romanian</label>
    </customValue>
    <customValue>
        <fullName>SR</fullName>
        <label>Serbian</label>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
        <label>Slovak</label>
    </customValue>
    <customValue>
        <fullName>SL</fullName>
        <label>Slovenian</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <label>Croatian</label>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
        <label>Bosnian</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Polish</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italian</label>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
        <label>Turkish</label>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
        <label>Russian</label>
    </customValue>
    <customValue>
        <fullName>ro_MD</fullName>
        <label>Moldovan</label>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
        <isActive>false</isActive>
        <label>Moldova</label>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
        <isActive>false</isActive>
        <label>Austria</label>
    </customValue>
    <masterLabel>Customer Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TW_Account_FillComplementaryFields.cls
/**
@description    worker class to automatically fill needed fields
@testClass      TW_Account_FillComplementaryFieldsTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description  
* Guilherme Charro                08/09/2021          Created the class
* David Favinha                   24/11/2021          Adding logic for CTI UserStory
* ------------------------------------------------------------------------------------        
*/
public with sharing class TW_Account_FillComplementaryFields {
    private IREP_CompanyCode companyCodeRepository;

    public TW_Account_FillComplementaryFields(){
        this.companyCodeRepository = new REP_CompanyCode();
    }
    
    @TestVisible
    private TW_Account_FillComplementaryFields(IREP_CompanyCode companyCodeRepository){
        this.companyCodeRepository = companyCodeRepository;
    }

    public void execute( List<Account> accountList, Map<Id,Account> oldAccountMap ) {
        Id accountCardsId = DO_Account.ACCOUNT_RECORDTYPEID_CEPCARDS;
        Set<Id> companyCodeIdsSet = new Set<Id>();
        List<Account> newAccountList = new List<Account>();
        for (Account accountInserted : accountList) {
            if (String.isBlank(accountInserted.CompanyCode__c) && accountInserted.RecordTypeId == accountCardsId) {
                accountInserted.CompanyCodeCountry__c = null;
            }else if( accountInserted.RecordTypeId == accountCardsId && !String.isBlank(accountInserted.CompanyCode__c) && accountInserted.CompanyCode__c!=null ){
                companyCodeIdsSet.add(accountInserted.CompanyCode__c);
                newAccountList.add( accountInserted );
            }
            
            if( oldAccountMap == null || oldAccountMap.get(accountInserted.Id).Phone != accountInserted.Phone ){
                accountInserted.CTITechnicalPhone__c = accountInserted.Phone?.right(7);
            }
        }

        Map<Id,CompanyCode__c> companyCodeMap = new Map<Id,CompanyCode__c>();

        if (!companyCodeIdsSet.isEmpty()) {
            companyCodeMap = new Map<Id,CompanyCode__c>(companyCodeRepository.getCompanyCodeInfo(companyCodeIdsSet));
        }

        for ( Account accountInserted : newAccountList ) {
            if ( companyCodeMap.containsKey(accountInserted.CompanyCode__c)
                && ( oldAccountMap == null ||(oldAccountMap !=null && accountInserted.CompanyCode__c != oldAccountMap.get(accountInserted.Id).CompanyCode__c))){
                accountInserted.CompanyCodeCountry__c = companyCodeMap.get(accountInserted.CompanyCode__c).Country__c;

                if (accountInserted.CurrencyIsoCode != companyCodeMap.get(accountInserted.CompanyCode__c).CurrencyIsoCode) {
                    accountInserted.CurrencyIsoCode = companyCodeMap.get(accountInserted.CompanyCode__c).CurrencyIsoCode;
                }

                if (String.isBlank(accountInserted.Language__c)) {
                    accountInserted.Language__c = companyCodeMap.get(accountInserted.CompanyCode__c).Language__c;
                } 
            }          
        }  
    }
}