force-app/main/default/objects/Account/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Displays the name of OMV entity related to the company code. Example OMV Downstream GmbH</description>
    <label>OMV Entity</label>
    <referenceTo>CompanyCode__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Default language for communication with the customer account</description>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerLanguage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountCountryRelatedSetting__mdt/AccountCountryRelatedSetting__mdt.object-meta.xml
<CustomObject>
    <description>this metadata shows what are the objects with dependency with the account country sharing model</description>
    <label>Account Country Related Setting</label>
    <pluralLabel>Account Country Related Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/AccountCountryRelatedSetting__mdt/fields/AccountLookupAPIName__c.field-meta.xml
<CustomField>
    <fullName>AccountLookupAPIName__c</fullName>
    <description>used to identify the name of the field used as account lookup</description>
    <label>Account Lookup API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountCountryRelatedSetting__mdt/fields/AccountRelationshipName__c.field-meta.xml
<CustomField>
    <fullName>AccountRelationshipName__c</fullName>
    <description>field to store the Account relationship  name</description>
    <label>Account Relationship Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountCountryRelatedSetting__mdt/fields/CountryAPIName__c.field-meta.xml
<CustomField>
    <fullName>CountryAPIName__c</fullName>
    <description>field to identify the field which is gonna be populated</description>
    <label>Country API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountCountryRelatedSetting__mdt/fields/ObjectFilter__c.field-meta.xml
<CustomField>
    <fullName>ObjectFilter__c</fullName>
    <description>field to store a condition in which this object will be queried</description>
    <label>Object Filter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Batch Definition</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Definition__c/fields/Batch_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Name__c</fullName>
    <description>It has the execution batch name, this is the value that will drive a specific execution of a batch (for example: TestBatch-Morning, TestBatch-Night or just TestBatch)</description>
    <externalId>true</externalId>
    <label>Batch Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Batch_Definition__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>It has the exact name of the dynamic batchable apex class</description>
    <label>Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Definition__c/fields/Job_Size__c.field-meta.xml
<CustomField>
    <fullName>Job_Size__c</fullName>
    <defaultValue>200</defaultValue>
    <description>To set the size of the batch. limit between 1 and 2000</description>
    <label>Job Size</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Definition__c/fields/SObject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_API_Name__c</fullName>
    <description>This represents SObject API name of the scope of the batch.</description>
    <label>SObject API Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CompanyCodeCountry__c.field-meta.xml
<CustomField>
    <fullName>CompanyCodeCountry__c</fullName>
    <description>field used for sharing rules</description>
    <label>Company Code Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerCountry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Field that reflects the country of the account associated to the Case</description>
    <formula>Account.BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Field to show the Language</description>
    <formula>IF( OR( ISBLANK(AccountId),ISBLANK(TEXT(Account.Language__c) ) ),TEXT(Case_Language__c), TEXT(Account.Language__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Language</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Case.recordType-meta.xml
<RecordType>
    <fullName>Case</fullName>
    <active>true</active>
    <businessProcess>Case Support Process</businessProcess>
    <label>CEP Cards Case</label>
</RecordType>

force-app/main/default/objects/CompanyCode__c/CompanyCode__c.object-meta.xml
<CustomObject>
    <description>This datatable is used for all business lines, to allow aggregating each Customer (Account) to the corresponding OMV subsidiary</description>
    <label>Company Code</label>
    <nameField>
        <label>Company Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyCode__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Identification of OMV subsidiary country</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerCountry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CompanyCode__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Identification of default language for the OMV subsidiary customers</description>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerLanguage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Execution__c/Job_Execution__c.object-meta.xml
<CustomObject>
    <description>This object represents a new batch execution.</description>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000000000}</displayFormat>
        <label>Job Execution</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the batch which is required to be executed</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Size__c.field-meta.xml
<CustomField>
    <fullName>Job_Size__c</fullName>
    <defaultValue>200</defaultValue>
    <description>To set the size of the batch. Limit is between 1 and 2000</description>
    <label>Job Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Run_With_Defaults__c.field-meta.xml
<CustomField>
    <fullName>Run_With_Defaults__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this field is true the batch filter condition will be the same that we have on the batch definition object for the same Job name, this will call a trigger that will copy the filter logic and the filter condition records
Others: Default True</description>
    <label>Run With Defaults</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CompanyCodeCountry__c.field-meta.xml
<CustomField>
    <fullName>CompanyCodeCountry__c</fullName>
    <description>field to store the country for sharing rules</description>
    <label>Company Code Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerCountry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parameters__c/Parameters__c.object-meta.xml
<CustomObject>
    <description>This object represents parameters that can be used by the batch to set default values, change filter conditions, actions etc.</description>
    <label>Parameter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parameters__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Batch link for which this parameter is valid</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to the Job Execution Object</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/CustomerCountry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CZ</fullName>
        <label>Czech Republic</label>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
        <label>Hungary</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
        <label>Slovakia</label>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
        <label>Bulgaria</label>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
        <label>Austria</label>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
        <label>Moldova</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <label>Romania</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <label>Croatia</label>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
        <label>Bosnia</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Poland</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
        <label>Turkey</label>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
        <label>Russia</label>
    </customValue>
    <customValue>
        <fullName>SH</fullName>
        <label>Serbia</label>
    </customValue>
    <customValue>
        <fullName>SL</fullName>
        <label>Slovenia</label>
    </customValue>
    <customValue>
        <fullName>Hungarian</fullName>
        <isActive>false</isActive>
        <label>Hungarian</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
        <isActive>false</isActive>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>Slovak</fullName>
        <isActive>false</isActive>
        <label>Slovak</label>
    </customValue>
    <customValue>
        <fullName>Romanian</fullName>
        <isActive>false</isActive>
        <label>Romanian</label>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
        <isActive>false</isActive>
        <label>Bulgarian</label>
    </customValue>
    <customValue>
        <fullName>German</fullName>
        <isActive>false</isActive>
        <label>German</label>
    </customValue>
    <description>Global value set to store working languages for OMV CEP business lines. Available languages should match the activated languages in the Translation Language Settings.</description>
    <masterLabel>Customer Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CustomerLanguage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BG</fullName>
        <label>Bulgarian</label>
    </customValue>
    <customValue>
        <fullName>CS</fullName>
        <label>Czech</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <label>German</label>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
        <label>Hungarian</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <label>Romanian</label>
    </customValue>
    <customValue>
        <fullName>SR</fullName>
        <label>Serbian</label>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
        <label>Slovak</label>
    </customValue>
    <customValue>
        <fullName>SL</fullName>
        <label>Slovenian</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <label>Croatian</label>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
        <label>Bosnian</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Polish</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italian</label>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
        <label>Turkish</label>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
        <label>Russian</label>
    </customValue>
    <customValue>
        <fullName>ro_MD</fullName>
        <label>Moldovan</label>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
        <isActive>false</isActive>
        <label>Moldova</label>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
        <isActive>false</isActive>
        <label>Austria</label>
    </customValue>
    <masterLabel>Customer Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Async_UpdateAccCompanyCodeTest.cls
@isTest
private class Async_UpdateAccCompanyCodeTest {
    static fflib_ApexMocks mocks = new fflib_ApexMocks();

    @isTest
    static void Async_UpdateAccCompanyCodeTest() {
        IREP_AccountCountryRelatedSetting accountCountryRelatedRepository = (REP_AccountCountryRelatedSetting)mocks.mock(REP_AccountCountryRelatedSetting.class);
        FW_IREP_JobExecution jobExecutionRep = (FW_REP_JobExecution)mocks.mock(FW_REP_JobExecution.class);
        FW_IREP_Parameters parameterRep = (FW_REP_Parameters)mocks.mock(FW_REP_Parameters.class);
        
        //Create Batch_Definition
        List<Batch_Definition__c> batchDefinitionList = new List<Batch_Definition__c>{
            new Batch_Definition__c(
                Id = fflib_IDGenerator.generate(Batch_Definition__c.sObjectType),
                Batch_Name__c = 'BatchTest',
                Class_Name__c = 'Async_UpdateAccCompanyCode',
                Job_Size__c = 200,
                SObject_API_Name__c = 'Case'
            )
        };
            
        //Create Parameters
        List<Parameters__c> parametersList = new List<Parameters__c>{
            new Parameters__c(
                Id = fflib_IDGenerator.generate(Parameters__c.sObjectType),
                Name = FW_AsyncHandler.DEFAULT_PARAMETER
            )   
        };

        //Create JobExecution
        List<Job_Execution__c> jobExecutionList = new List<Job_Execution__c>{
            new Job_Execution__c(
                Id = fflib_IDGenerator.generate(Job_Execution__c.sObjectType),
                Batch_Definition__c = batchDefinitionList.get(0).id,
                Run_With_Defaults__c = true              
            )
        };

        List<CompanyCode__c> companyCodeList = new List<CompanyCode__c>{
            new CompanyCode__c(
                Id = fflib_IDGenerator.generate(CompanyCode__c.sObjectType),
                Country__c = 'RO',
                Language__c = 'EN'
            )
        };

        //insert companyCodeList;

        List<Account> accountList = new List<Account>{
            new Account(
                Id = fflib_IDGenerator.generate(Account.sObjectType),
                Name = 'teste',
                CompanyCode__c = companyCodeList[0].Id,
                CompanyCode__r = companyCodeList
            )
        };

        //insert accountList;

        List<Case> caseList = new List<Case>{
            new Case(
                Id = fflib_IDGenerator.generate(Case.sObjectType),
                Subject = 'teste',
                AccountId = accountList[0].Id,
                Account = accountList[0],
                CompanyCodeCountry__c = 'teste'
            )
        };


        List<AccountCountryRelatedSetting__mdt> metadataList = new List<AccountCountryRelatedSetting__mdt>{
            new AccountCountryRelatedSetting__mdt(
                MasterLabel = 'Case',
                AccountLookupAPIName__c = 'AccountId',
                CountryAPIName__c = 'CompanyCodeCountry__c',
                AccountRelationshipName__c = 'Account',
                Objectfilter__c = 'Subject LIKE \'teste\''
            ),
            new AccountCountryRelatedSetting__mdt(
                MasterLabel = 'Opportunity',
                AccountLookupAPIName__c = 'AccountId',
                CountryAPIName__c = 'CompanyCodeCountry__c',
                AccountRelationshipName__c = 'Account'
            )
        };
            
        List<SObject> sobjectList = new List<SObject>{
            caseList[0]
        };

        mocks.startStubbing();
        mocks.when(accountCountryRelatedRepository.getAllAccountCountryRelated()).thenReturn(metadataList);
        mocks.when(jobExecutionRep.getJobExecWithBatchDefinitionsByIdSet((Set<Id>)fflib_match.anyObject())).thenReturn(jobExecutionList);
        mocks.when(jobExecutionRep.getJobExecutionByAsyncApexJobIdSet((Id)fflib_match.anyObject())).thenReturn(jobExecutionList);
        mocks.when(parameterRep.getParametersByParentId((Set<Id>)fflib_match.anyObject())).thenReturn(parametersList);
        mocks.stopStubbing();

        Map<String, AccountCountryRelatedSetting__mdt> relatedObjectsToUpdateMap = new Map<String, AccountCountryRelatedSetting__mdt>();
        for(AccountCountryRelatedSetting__mdt metadataRecord : accountCountryRelatedRepository.getAllAccountCountryRelated()) {
            relatedObjectsToUpdateMap.put(metadataRecord.MasterLabel, metadataRecord);
        }
        
        Async_UpdateAccCompanyCode newBatchRun = new Async_UpdateAccCompanyCode();
        newBatchRun = new Async_UpdateAccCompanyCode(accountCountryRelatedRepository, jobExecutionRep, parameterRep);
        newBatchRun.accountIdsSet = new Set<Id>{accountList[0].Id};
 
        
        Database.executeBatch(newBatchRun);
        newBatchRun.setAsyncApexJobId(null);
        newBatchRun.keyList = new List<String>{'Case', 'Account', 'Opportunity'};
        newBatchRun.relatedObjectsToUpdateMap = relatedObjectsToUpdateMap;
        newBatchRun.execute(null, sobjectList);

        ((FW_IREP_JobExecution)mocks.verify(jobExecutionRep, 1)).getJobExecWithBatchDefinitionsByIdSet((Set<Id>)fflib_match.anyObject());
        ((FW_IREP_Parameters)mocks.verify(parameterRep, 1)).getParametersByParentId((Set<Id>)fflib_match.anyObject());
        ((IREP_AccountCountryRelatedSetting)mocks.verify(accountCountryRelatedRepository, 1)).getAllAccountCountryRelated();
    }
}