force-app/main/default/objects/Account/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Displays the name of OMV entity related to the company code. Example OMV Downstream GmbH</description>
    <label>OMV Entity</label>
    <referenceTo>CompanyCode__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountCountryRelatedSetting__mdt/AccountCountryRelatedSetting__mdt.object-meta.xml
<CustomObject>
    <description>this metadata shows what are the objects with dependency with the account country sharing model</description>
    <label>Account Country Related Setting</label>
    <pluralLabel>Account Country Related Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/AccountCountryRelatedSetting__mdt/fields/AccountLookupAPIName__c.field-meta.xml
<CustomField>
    <fullName>AccountLookupAPIName__c</fullName>
    <description>used to identify the name of the field used as account lookup</description>
    <label>Account Lookup API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountCountryRelatedSetting__mdt/fields/AccountRelationshipName__c.field-meta.xml
<CustomField>
    <fullName>AccountRelationshipName__c</fullName>
    <description>field to store the Account relationship  name</description>
    <label>Account Relationship Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountCountryRelatedSetting__mdt/fields/CountryAPIName__c.field-meta.xml
<CustomField>
    <fullName>CountryAPIName__c</fullName>
    <description>field to identify the field which is gonna be populated</description>
    <label>Country API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountCountryRelatedSetting__mdt/fields/ObjectFilter__c.field-meta.xml
<CustomField>
    <fullName>ObjectFilter__c</fullName>
    <description>field to store a condition in which this object will be queried</description>
    <label>Object Filter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CompanyCode__c/CompanyCode__c.object-meta.xml
<CustomObject>
    <description>This datatable is used for all business lines, to allow aggregating each Customer (Account) to the corresponding OMV subsidiary</description>
    <label>Company Code</label>
    <nameField>
        <label>Company Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyCode__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Identification of OMV subsidiary country</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CustomerCountry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CustomerCountry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CZ</fullName>
        <label>Czech Republic</label>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
        <label>Hungary</label>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
        <label>Slovakia</label>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
        <label>Bulgaria</label>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
        <label>Austria</label>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
        <label>Moldova</label>
    </customValue>
    <customValue>
        <fullName>RO</fullName>
        <label>Romania</label>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
        <label>Croatia</label>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
        <label>Bosnia</label>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
        <label>Poland</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>TR</fullName>
        <label>Turkey</label>
    </customValue>
    <customValue>
        <fullName>RU</fullName>
        <label>Russia</label>
    </customValue>
    <customValue>
        <fullName>SH</fullName>
        <label>Serbia</label>
    </customValue>
    <customValue>
        <fullName>SL</fullName>
        <label>Slovenia</label>
    </customValue>
    <customValue>
        <fullName>Hungarian</fullName>
        <isActive>false</isActive>
        <label>Hungarian</label>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
        <isActive>false</isActive>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>Slovak</fullName>
        <isActive>false</isActive>
        <label>Slovak</label>
    </customValue>
    <customValue>
        <fullName>Romanian</fullName>
        <isActive>false</isActive>
        <label>Romanian</label>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
        <isActive>false</isActive>
        <label>Bulgarian</label>
    </customValue>
    <customValue>
        <fullName>German</fullName>
        <isActive>false</isActive>
        <label>German</label>
    </customValue>
    <description>Global value set to store working languages for OMV CEP business lines. Available languages should match the activated languages in the Translation Language Settings.</description>
    <masterLabel>Customer Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Async_UpdateAccCompanyCode.cls
/**
* @description   BatchJob to update account company code
* @testClass     Async_UpdateAccCompanyCodeTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro               02/09/2021          created class
* ------------------------------------------------------------------------------------ 
*/
global class Async_UpdateAccCompanyCode extends FW_AsyncHandler implements Database.Batchable<sObject>, Database.stateful{
    private IREP_AccountCountryRelatedSetting accountCountryRelatedRepository;
    public Map<String, AccountCountryRelatedSetting__mdt> relatedObjectsToUpdateMap = new Map<String, AccountCountryRelatedSetting__mdt>();
    public Set<Id> accountIdsSet;
    public List<String> keyList = new List<String>();

    global Async_UpdateAccCompanyCode(){
        accountCountryRelatedRepository = new REP_AccountCountryRelatedSetting();
    }

    @testVisible
    private Async_UpdateAccCompanyCode(IREP_AccountCountryRelatedSetting accountCountryRelatedRepository,FW_IREP_JobExecution jobExecutionRep, FW_IREP_Parameters parameterRep){
        this.accountCountryRelatedRepository = accountCountryRelatedRepository;
        this.jobExecutionRep = jobExecutionRep;
        this.parameterRep = parameterRep;
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        if (relatedObjectsToUpdateMap.isEmpty()) {
            for(AccountCountryRelatedSetting__mdt metadataRecord : accountCountryRelatedRepository.getAllAccountCountryRelated()) {
                relatedObjectsToUpdateMap.put(metadataRecord.MasterLabel, metadataRecord);
            }
        }
		
        keyList = new List<String>(relatedObjectsToUpdateMap.keySet());
        String query = '';

        if (!String.isBlank(relatedObjectsToUpdateMap.get(keyList[0]).Objectfilter__c)) {
            query = 'SELECT Id, '+relatedObjectsToUpdateMap.get(keyList[0]).CountryAPIName__c+' , '+
            +relatedObjectsToUpdateMap.get(keyList[0]).AccountLookupAPIName__c+' , '+relatedObjectsToUpdateMap.get(keyList[0]).AccountRelationshipName__c+'.CompanyCode__r.Country__c'+
            +' FROM '+relatedObjectsToUpdateMap.get(keyList[0]).MasterLabel+
            +' WHERE '+relatedObjectsToUpdateMap.get(keyList[0]).AccountLookupAPIName__c+' IN :accountIdsSet'+
            +' AND '+relatedObjectsToUpdateMap.get(keyList[0]).Objectfilter__c;
        }else{
            query = 'SELECT Id, '+relatedObjectsToUpdateMap.get(keyList[0]).CountryAPIName__c+' , '+
            +relatedObjectsToUpdateMap.get(keyList[0]).AccountLookupAPIName__c+' , '+relatedObjectsToUpdateMap.get(keyList[0]).AccountRelationshipName__c+'.CompanyCode__r.Country__c'+
            +' FROM '+relatedObjectsToUpdateMap.get(keyList[0]).MasterLabel +
            +' WHERE '+relatedObjectsToUpdateMap.get(keyList[0]).AccountLookupAPIName__c+' IN :accountIdsSet';
        }
        
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<SObject> sobjectList) {
        List<SObject> objectsToUpdateList = new List<SObject>();
        for (SObject objectProvided : sobjectList) { 
            if (objectProvided.get((String)relatedObjectsToUpdateMap.get(keyList[0]).CountryAPIName__c) != (String)objectProvided.getSobject('Account').getSobject('CompanyCode__r').get('Country__c')) {
                objectProvided.put(relatedObjectsToUpdateMap.get(keyList[0]).CountryAPIName__c, (String)objectProvided.getSobject('Account').getSobject('CompanyCode__r').get('Country__c'));
                objectsToUpdateList.add(objectProvided);
            }
        }

        if(!objectsToUpdateList.isEmpty()){
            Database.update(objectsToUpdateList, false);
        }
    }

    global void finish(Database.BatchableContext bc) {
        relatedObjectsToUpdateMap.remove(keyList[0]);

        if (!relatedObjectsToUpdateMap.isEmpty()) {
            Async_UpdateAccCompanyCode updateOtherObjects = new Async_UpdateAccCompanyCode();
            updateOtherObjects.relatedObjectsToUpdateMap = relatedObjectsToUpdateMap;
            updateOtherObjects.accountIdsSet = accountIdsSet;
            Database.executeBatch(updateOtherObjects, 200);
        }
    }
}