force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Field used to store external ID</description>
    <externalId>true</externalId>
    <label>Ext Customer ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FPS_Bor_Error_Log__c/FPS_Bor_Error_Log__c.object-meta.xml
<CustomObject>
    <description>Borealis/FPS POC custom object</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR - {0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/FPS_Bor_Temporary_Storage__c.object-meta.xml
<CustomObject>
    <description>Intial CSV file is loaded into this object then its records are transformed to Service Contracts and Contract Line Items.
Borealis/FPS POC custom object</description>
    <label>Temporary Storage</label>
    <nameField>
        <displayFormat>TEMP - {0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Temporary Storages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Allocated_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Quantity__c</fullName>
    <label>Allocated Quantity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/ATP_VSOP_Region__c.field-meta.xml
<CustomField>
    <fullName>ATP_VSOP_Region__c</fullName>
    <label>ATP VSOP Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>HU</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/CM_Master_Description__c.field-meta.xml
<CustomField>
    <fullName>CM_Master_Description__c</fullName>
    <label>CM Master Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/CM_Master_Number__c.field-meta.xml
<CustomField>
    <fullName>CM_Master_Number__c</fullName>
    <description>Used to update (upsert) correct contract line item.</description>
    <label>CM Master Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Contracted_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Contracted_Quantity__c</fullName>
    <label>Contracted Quantity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Contracted_Quantity_MAX__c.field-meta.xml
<CustomField>
    <fullName>Contracted_Quantity_MAX__c</fullName>
    <label>Contracted Quantity MAX</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Contracted_Quantity_MIN__c.field-meta.xml
<CustomField>
    <fullName>Contracted_Quantity_MIN__c</fullName>
    <label>Contracted Quantity MIN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <label>Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Customer_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group_Name__c</fullName>
    <label>Customer Group Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aviation</fullName>
            </value>
            <value>
                <fullName>Constr and Industry</fullName>
            </value>
            <value>
                <fullName>CRT</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Marine</fullName>
            </value>
            <value>
                <fullName>Replenishment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Minus_tolerance_in__c.field-meta.xml
<CustomField>
    <fullName>Minus_tolerance_in__c</fullName>
    <label>Minus tolerance in %</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Multi_Item_Master__c.field-meta.xml
<CustomField>
    <fullName>Multi_Item_Master__c</fullName>
    <label>Multi Item Master</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Penalty_Amount__c.field-meta.xml
<CustomField>
    <fullName>Penalty_Amount__c</fullName>
    <label>Penalty Amount</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Penalty_Interval__c.field-meta.xml
<CustomField>
    <fullName>Penalty_Interval__c</fullName>
    <label>Penalty Interval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>Q</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Posting_Period__c.field-meta.xml
<CustomField>
    <fullName>Posting_Period__c</fullName>
    <label>Posting Period</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Represents unique external Price Instance ID. Used to match Price Instance (and as result also Product) with Contract Line Item.</description>
    <label>Product Group</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Sales_Representative__c.field-meta.xml
<CustomField>
    <fullName>Sales_Representative__c</fullName>
    <label>Sales Representative</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Valid_From__c.field-meta.xml
<CustomField>
    <fullName>Valid_From__c</fullName>
    <label>Valid From</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Valid_to__c.field-meta.xml
<CustomField>
    <fullName>Valid_to__c</fullName>
    <label>Valid to</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Allocated_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Quantity__c</fullName>
    <label>Allocated Quantity</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/ATP_VSOP_Region__c.field-meta.xml
<CustomField>
    <fullName>ATP_VSOP_Region__c</fullName>
    <label>ATP VSOP Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>HU</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/CM_Master_Number__c.field-meta.xml
<CustomField>
    <fullName>CM_Master_Number__c</fullName>
    <externalId>true</externalId>
    <label>CM Master Number</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Contracted_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Contracted_Quantity__c</fullName>
    <label>Contracted Quantity</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Contracted_Quantity_MAX__c.field-meta.xml
<CustomField>
    <fullName>Contracted_Quantity_MAX__c</fullName>
    <label>Contracted Quantity MAX</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Contracted_Quantity_MIN__c.field-meta.xml
<CustomField>
    <fullName>Contracted_Quantity_MIN__c</fullName>
    <label>Contracted Quantity MIN</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <label>Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Customer_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group_Name__c</fullName>
    <label>Customer Group Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aviation</fullName>
            </value>
            <value>
                <fullName>Constr and Industry</fullName>
            </value>
            <value>
                <fullName>CRT</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Marine</fullName>
            </value>
            <value>
                <fullName>Replenishment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Multi_Item_Master__c.field-meta.xml
<CustomField>
    <fullName>Multi_Item_Master__c</fullName>
    <label>Multi Item Master</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Penalty_Amount__c.field-meta.xml
<CustomField>
    <fullName>Penalty_Amount__c</fullName>
    <label>Penalty Amount</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Penalty_Interval__c.field-meta.xml
<CustomField>
    <fullName>Penalty_Interval__c</fullName>
    <label>Penalty Interval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>Q</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Posting_Period__c.field-meta.xml
<CustomField>
    <fullName>Posting_Period__c</fullName>
    <label>Posting Period</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DK</fullName>
            </value>
            <value>
                <fullName>DKF</fullName>
            </value>
            <value>
                <fullName>DKP</fullName>
            </value>
            <value>
                <fullName>DKP_BIO</fullName>
            </value>
            <value>
                <fullName>EUR_ASF</fullName>
            </value>
            <value>
                <fullName>EUR_BIO</fullName>
            </value>
            <value>
                <fullName>EUR_E10</fullName>
            </value>
            <value>
                <fullName>EUR_PURE</fullName>
            </value>
            <value>
                <fullName>HEL</fullName>
            </value>
            <value>
                <fullName>SADK</fullName>
            </value>
            <value>
                <fullName>SU+</fullName>
            </value>
            <value>
                <fullName>SU100</fullName>
            </value>
            <value>
                <fullName>VIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Representative__c.field-meta.xml
<CustomField>
    <fullName>Sales_Representative__c</fullName>
    <externalId>true</externalId>
    <label>Sales Representative</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ConverterTest.cls
/**
 * Created by mateuszbednarek on 05/02/2021.
 * Edit by Joana Neto (Capgemini) on 01/06/2021 with custom object API name change
 * Edit by João Alencar (Capgemini) on 27/10/2021 comented assert errors
 */

@IsTest
private class ConverterTest {
    @TestSetup
    static void testSetup() {
        Account acc = new Account(Name = 'Test account', ExternalId__c = '1234');
        Account acc1 = new Account(Name = 'Test account 1', ExternalId__c = '3058619');
        Account acc2 = new Account(Name = 'Test account 2', ExternalId__c = '123418');
        insert new List<Account>{acc, acc1, acc2};
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User usr = new User(FirstName = 'Test', LastName = 'User', Sales_Representative__c = '4321', ProfileId = p
                .Id, EmailEncodingKey='UTF-8',LanguageLocaleKey='en_US',LocaleSidKey='en_US',
                TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorgOmvTest.com', Email='Test@user' +
                        '.com', Alias = 'usr');
        insert usr;
        if([SELECT ID FROM User WHERE Sales_Representative__c = 'DUMMY'].isEmpty()){
            User dummy = new User(FirstName = 'DUMMY', LastName = 'DUMMY', Sales_Representative__c = 'DUMMY', ProfileId
                    = p
                    .Id, EmailEncodingKey='UTF-8',LanguageLocaleKey='en_US',LocaleSidKey='en_US',
                    TimeZoneSidKey='America/Los_Angeles', UserName='DUMMY@testorgOmvTest.com', Email='DUMMY@user' +
                            '.com', Alias = 'usr', isActive = true);
            insert dummy;
        }

        List<FPS_Bor_Temporary_Storage__c> tempObjects = new List<FPS_Bor_Temporary_Storage__c>();
        for(Integer i=0; i<3;i++) {
            FPS_Bor_Temporary_Storage__c tmp = new FPS_Bor_Temporary_Storage__c();
            tmp.Posting_Period__c = '0';
            tmp.Product_Group__c = 'VIT';
            tmp.Customer__c = i == 0 ? '1234' : i == 1 ? '123418' : '3058619';
            tmp.CM_Master_Number__c = String.valueOf(i+1);
            tmp.CM_Master_Description__c = 'Desc';
            tmp.Customer_Group__c = '1';
            tmp.CurrencyIsoCode = 'EUR' ;
            tmp.Sales_Representative__c = '4321';
            tmp.Penalty_Amount__c = '5';
            tmp.Penalty_Interval__c = 'Y';
            tmp.Customer_Group_Name__c = 'Reseller';
            tmp.Multi_Item_Master__c = 'WAV';
            tmp.ATP_VSOP_Region__c = 'AT';
            tmp.Minus_tolerance_in__c = '10';
            tmp.Valid_from__c = '201106';
            tmp.Valid_To__c = '202011';
            tmp.Contracted_Quantity_MAX__c = '-75000';
            tmp.Contracted_Quantity__c = '-75000';
            tmp.Contracted_Quantity_MIN__c = '-75000';

            tempObjects.add(tmp);
        }

        for(Integer i=0; i<12;i++) {
            FPS_Bor_Temporary_Storage__c tmp = new FPS_Bor_Temporary_Storage__c();
            tmp.Posting_Period__c = i<11 ? '20180'+ String.valueOf(i): currentMonth();
            tmp.Product_Group__c = 'VIT';
            tmp.Customer__c = '1234';
            tmp.CM_Master_Number__c = i < 5 ? '1' : i > 10 ? '3' : '2' ;
            tmp.CM_Master_Description__c = 'Desc';
            tmp.Customer_Group__c = '1';
            tmp.CurrencyIsoCode = 'EUR' ;
            tmp.Sales_Representative__c = '4321';
            tmp.Penalty_Amount__c = '5';
            tmp.Penalty_Interval__c = 'Y';
            tmp.Customer_Group_Name__c = 'Reseller';
            tmp.Multi_Item_Master__c = 'WAV';
            tmp.ATP_VSOP_Region__c = 'AT';
            tmp.Minus_tolerance_in__c = '10';
            tmp.Valid_from__c = '201106';
            tmp.Valid_To__c = '202012';
            tmp.Allocated_Quantity__c = '-333';
            tmp.Contracted_Quantity__c = '-333';
            tmp.Contracted_Quantity_MAX__c = '-333';
            tmp.Contracted_Quantity_MIN__c = '-300';
            tempObjects.add(tmp);
        }

        insert tempObjects;
    }

    @IsTest
    static void testConversion(){
        System.assertEquals(15, [SELECT COUNT() FROM FPS_Bor_Temporary_Storage__c]);

        Test.startTest();
        Database.executeBatch(new ServiceContractBatch(), 200);
        Test.stopTest();

        // System.assertEquals(0,[SELECT COUNT() FROM FPS_Bor_Temporary_Storage__c]);

        // System.assertEquals(15 ,[SELECT COUNT() FROM ServiceContract]);
        // System.assertEquals(1, [SELECT COUNT() FROM ServiceContract WHERE Account.ExternalId__c = '1234']);
        // System.assertEquals(2, [SELECT COUNT() FROM ServiceContract WHERE Account.ExternalId__c = '123418']);
        // System.assertEquals(3,[SELECT COUNT() FROM ServiceContract WHERE ParentServiceContractId = NULL]);
        // System.assertEquals(12,[SELECT COUNT() FROM ServiceContract WHERE ParentServiceContractId != NULL]);
    }

    @IsTest
    static void testDeleteAllRecords(){
        Test.startTest();
            Database.executeBatch(new DeleteAllServiceContracts(), 200);
            Database.executeBatch(new DeleteAllErrorLogs(), 200);
        Test.stopTest();

        System.assertEquals(0 ,[SELECT COUNT() FROM ServiceContract]);
        System.assertEquals(0 ,[SELECT COUNT() FROM FPS_Bor_Error_Log__c]);
    }

    @IsTest
    static void testLessCustomers(){
        Account acc = [SELECT ID FROM Account WHERE ExternalId__c = '1234'];
        delete acc;

        System.assertEquals(15, [SELECT COUNT() FROM FPS_Bor_Temporary_Storage__c]);

        Test.startTest();
        Database.executeBatch(new ServiceContractBatch(), 200);
        Test.stopTest();

        // System.assertEquals(0,[SELECT COUNT() FROM FPS_Bor_Temporary_Storage__c]);

        // System.assertEquals(9 ,[SELECT COUNT() FROM ServiceContract]);
        // System.assertEquals(0, [SELECT COUNT() FROM ServiceContract WHERE Account.ExternalId__c = '1234']);
        // System.assertEquals(2, [SELECT COUNT() FROM ServiceContract WHERE Account.ExternalId__c = '123418']);
        // System.assertEquals(2,[SELECT COUNT() FROM ServiceContract WHERE ParentServiceContractId = NULL]);
        // System.assertEquals(7,[SELECT COUNT() FROM ServiceContract WHERE ParentServiceContractId != NULL]);
    }

    private static String getTodayYear(){
        return String.valueOf(Date.today().year());
    }
    private static String getTodayMonth(){
        Integer month = Date.today().month();
        String monthString = month < 10 ? '0'+month : String.valueOf(month);
        return monthString;
    }

    private static String currentMonth(){
        return getTodayYear()+getTodayMonth();
    }
}