force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Field used to store external ID</description>
    <externalId>true</externalId>
    <label>Ext Customer ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/FPS_Bor_Temporary_Storage__c.object-meta.xml
<CustomObject>
    <description>Intial CSV file is loaded into this object then its records are transformed to Service Contracts and Contract Line Items.
Borealis/FPS POC custom object</description>
    <label>Temporary Storage</label>
    <nameField>
        <displayFormat>TEMP - {0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Temporary Storages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/CM_Master_Description__c.field-meta.xml
<CustomField>
    <fullName>CM_Master_Description__c</fullName>
    <label>CM Master Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/CM_Master_Number__c.field-meta.xml
<CustomField>
    <fullName>CM_Master_Number__c</fullName>
    <description>Used to update (upsert) correct contract line item.</description>
    <label>CM Master Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Minus_tolerance_in__c.field-meta.xml
<CustomField>
    <fullName>Minus_tolerance_in__c</fullName>
    <label>Minus tolerance in %</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <label>Plant</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Plus_tolerance_in__c.field-meta.xml
<CustomField>
    <fullName>Plus_tolerance_in__c</fullName>
    <label>Plus tolerance in %</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Represents unique external Price Instance ID. Used to match Price Instance (and as result also Product) with Contract Line Item.</description>
    <label>Product Group</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Sales_Representative__c.field-meta.xml
<CustomField>
    <fullName>Sales_Representative__c</fullName>
    <label>Sales Representative</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Valid_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Valid_From_Date__c</fullName>
    <formula>DATE(VALUE(LEFT(Valid_From__c, 4)), VALUE(RIGHT(Valid_From__c, 2)), 1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valid From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Valid_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Valid_To_Date__c</fullName>
    <formula>IF(VALUE(RIGHT(Valid_to__c, 2)) = 12, 
					DATE(VALUE(LEFT(Valid_to__c, 4)), VALUE(RIGHT(Valid_to__c, 2)), 31),
			DATE(VALUE(LEFT(Valid_to__c, 4)), VALUE(RIGHT(Valid_to__c, 2))+1, 1)-1
			)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valid To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/CM_Master_Number__c.field-meta.xml
<CustomField>
    <fullName>CM_Master_Number__c</fullName>
    <externalId>true</externalId>
    <label>CM Master Number</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <description>Customer Name</description>
    <externalId>true</externalId>
    <inlineHelpText>Customer Name, defined as external id to speed up reporting via index</inlineHelpText>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Is_Master_Contract__c.field-meta.xml
<CustomField>
    <fullName>Is_Master_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Master Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Minus_Tolerance__c.field-meta.xml
<CustomField>
    <fullName>Minus_Tolerance__c</fullName>
    <label>Minus Tolerance in %</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <label>Plant</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AD01</fullName>
            </value>
            <value>
                <fullName>AD02</fullName>
            </value>
            <value>
                <fullName>AD03</fullName>
            </value>
            <value>
                <fullName>AD04</fullName>
            </value>
            <value>
                <fullName>AD05</fullName>
            </value>
            <value>
                <fullName>AD06</fullName>
            </value>
            <value>
                <fullName>AD07</fullName>
            </value>
            <value>
                <fullName>AD10</fullName>
            </value>
            <value>
                <fullName>AD11</fullName>
            </value>
            <value>
                <fullName>AD12</fullName>
            </value>
            <value>
                <fullName>AD18</fullName>
            </value>
            <value>
                <fullName>AD20</fullName>
            </value>
            <value>
                <fullName>AD38</fullName>
            </value>
            <value>
                <fullName>AD50</fullName>
            </value>
            <value>
                <fullName>AD51</fullName>
            </value>
            <value>
                <fullName>AD52</fullName>
            </value>
            <value>
                <fullName>AD58</fullName>
            </value>
            <value>
                <fullName>AD61</fullName>
            </value>
            <value>
                <fullName>ADA1</fullName>
            </value>
            <value>
                <fullName>ADA7</fullName>
            </value>
            <value>
                <fullName>ADB3</fullName>
            </value>
            <value>
                <fullName>ADB5</fullName>
            </value>
            <value>
                <fullName>ADB6</fullName>
            </value>
            <value>
                <fullName>ADB7</fullName>
            </value>
            <value>
                <fullName>ADB9</fullName>
            </value>
            <value>
                <fullName>ADH2</fullName>
            </value>
            <value>
                <fullName>ADH3</fullName>
            </value>
            <value>
                <fullName>CD01</fullName>
            </value>
            <value>
                <fullName>CD02</fullName>
            </value>
            <value>
                <fullName>CD05</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Plus_Tolerance__c.field-meta.xml
<CustomField>
    <fullName>Plus_Tolerance__c</fullName>
    <label>Plus Tolerance in %</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DK</fullName>
            </value>
            <value>
                <fullName>DKF</fullName>
            </value>
            <value>
                <fullName>DKP</fullName>
            </value>
            <value>
                <fullName>DKP_BIO</fullName>
            </value>
            <value>
                <fullName>EUR_ASF</fullName>
            </value>
            <value>
                <fullName>EUR_BIO</fullName>
            </value>
            <value>
                <fullName>EUR_E10</fullName>
            </value>
            <value>
                <fullName>EUR_PURE</fullName>
            </value>
            <value>
                <fullName>HEL</fullName>
            </value>
            <value>
                <fullName>SADK</fullName>
            </value>
            <value>
                <fullName>SU+</fullName>
            </value>
            <value>
                <fullName>SU100</fullName>
            </value>
            <value>
                <fullName>VIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Representative__c.field-meta.xml
<CustomField>
    <fullName>Sales_Representative__c</fullName>
    <externalId>true</externalId>
    <label>Sales Representative</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ServiceContractConverter.cls
/**
 * Created by mateuszbednarek on 20/01/2021.
 * Edit by Joana Neto (Capgemini) on 01/06/2021 with custom object API name change
*/

public with sharing class ServiceContractConverter {

    static List<ServiceContract> contractsToUpsert = new List<ServiceContract>();
    static Schema.sObjectField externalIdField = ServiceContract.CM_Master_Number__c.getDescribe().getSObjectField();
    static Id standardPricebookId = getPricebookId();
    static List<FPS_Bor_Temporary_Storage__c> contractsList;
    static List<Schema.FieldSetMember>  lineItemFields = Util.readFieldSet('Contract_Line_Item',
            'FPS_Bor_Temporary_Storage__c');
    static Set<Schema.FieldSetMember>  fieldToConvertToNumber = new Set<Schema.FieldSetMember>(Util.readFieldSet
            ('Number_type_fields',
                    'FPS_Bor_Temporary_Storage__c'));
    static Map<String, User> externalIdToInternalUser = getInternalUsersMap();
    static Map<String, User> accountExternalIdToExternalUser = getExternalUsersMap();
    static Map<String, Account> externalIdToAccount = getAccountsMap();

    public static void convert(List<FPS_Bor_Temporary_Storage__c> contracts) {
        contractsList = contracts;
        createServiceContracts();

        Util.upsertRecords(contractsToUpsert,externalIdField, ServiceContractConverter.class,'convert');
    }

    private static void createServiceContracts() {
        for (FPS_Bor_Temporary_Storage__c contract : contractsList) {
            if(customerExists(contract)){
                contractsToUpsert.add(createContract(contract));
            }

        }
    }

    private static ServiceContract createContract(FPS_Bor_Temporary_Storage__c temp){
        validateCustomer(temp);
        ServiceContract contract =  new ServiceContract(
                Is_Master_Contract__c = true,
                Account = getAccount(temp.Customer__c),
                CM_Master_Number__c = temp.CM_Master_Number__c,
                Pricebook2Id = standardPricebookId,
                OwnerId = getUser(temp),
                Customer_Name__c = getAccountName(temp.Customer__c),
                Name = temp.Customer__c+'_'+temp.Product_Group__c,
                Plus_Tolerance__c = temp.Plus_tolerance_in__c == null ? 0 : Decimal.valueOf(String.valueOf(temp
                        .Plus_tolerance_in__c).replaceAll(' ','').replaceAll(',','.')),
                Minus_Tolerance__c = temp.Minus_tolerance_in__c == null ? 0 : Decimal.valueOf(String.valueOf(temp
                        .Minus_tolerance_in__c).replaceAll(' ','')
                        .replaceAll(',','.')),
                Description = temp.CM_Master_Description__c,
                StartDate = temp.Valid_From_Date__c,
                EndDate = temp.Valid_To_Date__c,
                Plant__c = temp.Plant__c
        );

        for(Schema.FieldSetMember field: lineItemFields){
            String fieldPath = field.getFieldPath();
            Object fieldValue = temp.get(fieldPath);
            if(fieldShouldBeConvertedToNumber(fieldPath)){
                fieldValue = convertFieldToNumericValue(fieldValue);
            }
            contract.put(fieldPath, fieldValue);
        }

        return contract;
    }

    //Items related to 3058619 Customer should be actually linked to 123418
    private static void validateCustomer(FPS_Bor_Temporary_Storage__c tmp){
        if(tmp.Customer__c == '3058619'){
            tmp.Customer__c = '123418';
        }
    }

    private static Boolean fieldShouldBeConvertedToNumber(String pathName){
        for(Schema.FieldSetMember field: fieldToConvertToNumber){
            if(field.getFieldPath() == pathName) return true;
        }
        return false;
    }

    private static Object convertFieldToNumericValue(Object textValue){
        if(textValue == null){
            return null;
        }
        Decimal value = Decimal.valueOf(String.valueOf(textValue).replaceAll(' ','').replaceAll(',','' +
                '.'));
        return value < 0 ? value * -1 : value;
    }

    private static Account getAccount(String extId) {
        return new Account(ExternalId__c = extId);
    }
    private static String getAccountName(String extId){
        if(externalIdToAccount.containsKey(extId)){
            return externalIdToAccount.get(extId).Name;
        }else{
            return null;
        }

    }
    private static Id getUser(FPS_Bor_Temporary_Storage__c contract){
        if(isActiveContract(contract)){
            if(accountExternalIdToExternalUser.containsKey(contract.Customer__c)){
                return accountExternalIdToExternalUser.get(contract.Customer__c).Id;
            }
        }else{
            if(externalIdToInternalUser.containsKey(contract.Sales_Representative__c)){
                return externalIdToInternalUser.get(contract.Sales_Representative__c).Id;
            }
        }
        return externalIdToInternalUser.get('DUMMY').Id;
    }
    private static Boolean isActiveContract(FPS_Bor_Temporary_Storage__c contract){
        return Date.today().year() - contract.Valid_To_Date__c.year() <= 1;
    }
    private static Id getPricebookId(){
        if(Test.isRunningTest()){
            return Test.getStandardPricebookId();
        }
        if(standardPricebookId == null){
            return[SELECT Id FROM Pricebook2 WHERE IsStandard = true].Id;
        }else{
            return standardPricebookId;
        }
    }
    private static Map<String, Account> getAccountsMap(){
        if(externalIdToAccount == null){
            externalIdToAccount = new Map<String, Account>();
            for(Account acc: [SELECT Id, Name,ExternalId__c FROM Account WHERE ExternalId__c != null]){
                externalIdToAccount.put(acc.ExternalId__c, acc);
            }
        }
        return externalIdToAccount;
    }
    private static Map<String, User> getInternalUsersMap(){
        if(externalIdToInternalUser == null){
            externalIdToInternalUser = new Map<String, User>();
            for(User usr: [SELECT Id, Sales_Representative__c FROM User WHERE Sales_Representative__c != null]){
                externalIdToInternalUser.put(usr.Sales_Representative__c, usr);
            }

        }
        return externalIdToInternalUser;
    }

    private static Map<String, User> getExternalUsersMap(){
        if(accountExternalIdToExternalUser == null){
            accountExternalIdToExternalUser = new Map<String, User>();
            for(User usr: [SELECT Account.ExternalId__c,Account.Name,Account.Id,Id,Username,Email,UserRole.Name,
                    UserRole.PortalRole,UserRole.PortalType FROM User WHERE UserRole.Name LIKE '%Customer User' AND Account.ExternalId__c != null]){
                accountExternalIdToExternalUser.put(usr.Account.ExternalId__c, usr);
            }
        }
        return accountExternalIdToExternalUser;
    }

    private static Boolean customerExists(FPS_Bor_Temporary_Storage__c contract){
        return externalIdToAccount.containsKey(contract.Customer__c);
    }
}