force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Field used to store external ID</description>
    <externalId>true</externalId>
    <label>Ext Customer ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Batch_Definition__c/Batch_Definition__c.object-meta.xml
<CustomObject>
    <description>This object is to store all the batch definitions to be scheduled dynamically. There should be one record (only one record) per batch class with it’s definition</description>
    <label>Batch Definition</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Batch Definition</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Definition__c/fields/Batch_Name__c.field-meta.xml
<CustomField>
    <fullName>Batch_Name__c</fullName>
    <description>It has the execution batch name, this is the value that will drive a specific execution of a batch (for example: TestBatch-Morning, TestBatch-Night or just TestBatch)</description>
    <externalId>true</externalId>
    <label>Batch Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Batch_Definition__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>It has the exact name of the dynamic batchable apex class</description>
    <label>Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Definition__c/fields/Job_Size__c.field-meta.xml
<CustomField>
    <fullName>Job_Size__c</fullName>
    <defaultValue>200</defaultValue>
    <description>To set the size of the batch. limit between 1 and 2000</description>
    <label>Job Size</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Definition__c/fields/SObject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_API_Name__c</fullName>
    <description>This represents SObject API name of the scope of the batch.</description>
    <label>SObject API Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/Job_Execution__c.object-meta.xml
<CustomObject>
    <description>This object represents a new batch execution.</description>
    <label>Job Execution</label>
    <nameField>
        <displayFormat>JE-{000000000}</displayFormat>
        <label>Job Execution</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Execution__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the batch which is required to be executed</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Job Executions</relationshipLabel>
    <relationshipName>Job_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Job_Size__c.field-meta.xml
<CustomField>
    <fullName>Job_Size__c</fullName>
    <defaultValue>200</defaultValue>
    <description>To set the size of the batch. Limit is between 1 and 2000</description>
    <label>Job Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Execution__c/fields/Run_With_Defaults__c.field-meta.xml
<CustomField>
    <fullName>Run_With_Defaults__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If this field is true the batch filter condition will be the same that we have on the batch definition object for the same Job name, this will call a trigger that will copy the filter logic and the filter condition records
Others: Default True</description>
    <label>Run With Defaults</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityCategory__c.field-meta.xml
<CustomField>
    <fullName>OpportunityCategory__c</fullName>
    <description>Choose between opportunity for bulk or cards</description>
    <label>Opportunity Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>Cards</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parameters__c/Parameters__c.object-meta.xml
<CustomObject>
    <description>This object represents parameters that can be used by the batch to set default values, change filter conditions, actions etc.</description>
    <label>Parameter</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parameters__c/fields/Batch_Definition__c.field-meta.xml
<CustomField>
    <fullName>Batch_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Batch link for which this parameter is valid</description>
    <label>Batch Definition</label>
    <referenceTo>Batch_Definition__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Job_Execution__c.field-meta.xml
<CustomField>
    <fullName>Job_Execution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>link to the Job Execution Object</description>
    <label>Job Execution</label>
    <referenceTo>Job_Execution__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parameters__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Defines the value of the parameter, can be a set of Ids, a status value, a constant etc</description>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ClosedDate__c.field-meta.xml
<CustomField>
    <fullName>ClosedDate__c</fullName>
    <description>Date that the Quote was closed</description>
    <label>Closed date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Async_OppNotClosedNotificationTest.cls
/**
@author Hugo Rodrigues
@date   23/06/2021
@description Test class for Async_OppNotClosedNotification
@TestClass         
Modification Log:
----------------------------------------------------------------------------------------------------
Developer                  Date                Description                                  Coverage
----------------------------------------------------------------------------------------------------
Hugo Rodrigues           23/06/2021            Original Version                                 100
Hugo Rodrigues           23/09/2021   added RecordType and 2 updates because validation rule    100
Guilherme Charro         26/11/2021            edited to use framework                           95
*/
@isTest
public class Async_OppNotClosedNotificationTest {
    static fflib_ApexMocks mocks = new fflib_ApexMocks();
    @isTest
    static void Async_OpportunityNotClosedNotificationExecute() {
        IREP_Opportunity opportunityRepository = (REP_Opportunity)mocks.mock(REP_Opportunity.class);
        ISL_ChatterNotifications opportunityChatterNotification = (SL_ChatterNotifications)mocks.mock(SL_ChatterNotifications.class);
        FW_IREP_JobExecution jobExecutionRep = (FW_REP_JobExecution)mocks.mock(FW_REP_JobExecution.class);
        FW_IREP_Parameters parameterRep = (FW_REP_Parameters)mocks.mock(FW_REP_Parameters.class);

        List<Account> objListAccount = new List<Account>{
            new Account(
                Id = fflib_IDGenerator.generate(Account.sObjectType),
                Name = Do_Account.ACCOUNT_NAME_FOR_TEST,
                ExternalId__c = Do_Account.ACCOUNT_EXT_CUSTOMER_ID_FOR_TEST
            )
        };

        List<Opportunity> opportunitiesList = new List<Opportunity>{
            new Opportunity(
                Id = fflib_IDGenerator.generate(Opportunity.sObjectType),
                Name = Do_Opportunity.OPPORTUNITY_NAME_FOR_TEST,
                AccountId=objListAccount[0].Id,
                CloseDate=System.today().addMonths(1),
                StageName=Do_Opportunity.OPPORTUNITY_STAGENAME_QUALIFICATION,
                OpportunityCategory__c=Do_Opportunity.OPPORTUNITY_CATEGORY_CARDS
            )
        };
            
        opportunitiesList[0] = (Opportunity)fflib_ApexMocksUtils.setReadOnlyFields(
            opportunitiesList[0],
            Opportunity.class,
            new Map<SObjectField, Object> {Opportunity.CreatedDate => System.today().addDays(-1)}
        );
        
        List<Quote> objListQuote = new List<Quote>{
            new Quote(
                Id = fflib_IDGenerator.generate(Quote.sObjectType),
                Name = DO_Quote.QUOTE_NAME_FOR_TEST,
                OpportunityID =opportunitiesList[0].Id,
                ClosedDate__c = date.Today(),
                RecordTypeID=DO_Quote.QUOTE_CARDS_RECORDTYPE_ID,
                Status=DO_Quote.QUOTE_STATUS_ACCEPTED
            ),
            new Quote(
                Id = fflib_IDGenerator.generate(Quote.sObjectType),
                Name = DO_Quote.QUOTE_NAME_FOR_TEST,
                OpportunityID =opportunitiesList[0].Id,
                ClosedDate__c = date.Today(),
                Status = DO_Quote.QUOTE_STATUS_DRAFT,
                RecordTypeID=DO_Quote.QUOTE_CARDS_RECORDTYPE_ID
            )
            
        };
        
        List<Opportunity> newOpportunitiesList = (List<Opportunity>)fflib_ApexMocksUtils.makeRelationship(
            List<Opportunity>.class,
            opportunitiesList,
            Quote.OpportunityId,
            new List<List<Quote>> {objListQuote}
        );
        
        // Initialize framework        
        //Create Batch_Definition
        List<Batch_Definition__c> batchDefinitionList = new List<Batch_Definition__c>{
            new Batch_Definition__c(
                Id = fflib_IDGenerator.generate(Batch_Definition__c.sObjectType),
                Batch_Name__c = 'BatchTest',
                Class_Name__c = 'Async_OpportunityNotClosedNotification',
                Job_Size__c = 200,
                SObject_API_Name__c = 'Opportunity'
                )
        };
        //Create Parameters
        List<Parameters__c> parametersList = new List<Parameters__c>{
            new Parameters__c(
                Id = fflib_IDGenerator.generate(Parameters__c.sObjectType),
                Name = FW_AsyncHandler.DEFAULT_PARAMETER
                ),
            new Parameters__c(
                Id = fflib_IDGenerator.generate(Parameters__c.sObjectType),
                Name = 'daysInactiveOpportunity',
                Value__c='7'
                )    
        };

        //Create JobExecution
        List<Job_Execution__c> jobExecutionList = new List<Job_Execution__c>{
            new Job_Execution__c(
                Id = fflib_IDGenerator.generate(Job_Execution__c.sObjectType),
                Batch_Definition__c = batchDefinitionList.get(0).id,
                Run_With_Defaults__c = true              
                )
        };

        mocks.startStubbing();
        mocks.when(opportunityRepository.getQuoteByOpportunityID((Set<Id>)fflib_match.anyObject())).thenReturn( newOpportunitiesList );
        mocks.when(opportunityRepository.getOpportunityByID((Set<Id>)fflib_match.anyObject())).thenReturn( opportunitiesList );
        ((ISL_ChatterNotifications) mocks.doAnswer( new VoidAnswer(),opportunityChatterNotification)).persistChatterPosts();
        mocks.when(jobExecutionRep.getJobExecWithBatchDefinitionsByIdSet((Set<Id>)fflib_match.anyObject())).thenReturn(jobExecutionList);
        mocks.when(jobExecutionRep.getJobExecutionByAsyncApexJobIdSet((Id)fflib_match.anyObject())).thenReturn(jobExecutionList);
        mocks.when(parameterRep.getParametersByParentId((Set<Id>)fflib_match.anyObject())).thenReturn(parametersList);
        mocks.stopStubbing();
        

        Async_OpportunityNotClosedNotification newBatchRun = new Async_OpportunityNotClosedNotification();
        newBatchRun =new Async_OpportunityNotClosedNotification(opportunityRepository, jobExecutionRep, parameterRep, opportunityChatterNotification);

        Database.executeBatch(newBatchRun);
        newBatchRun.setAsyncApexJobId(null);
        newBatchRun.execute(null, opportunitiesList);
        
        ((IREP_Opportunity)mocks.verify(opportunityRepository, 1)).getQuoteByOpportunityID((Set<Id>)fflib_match.anyObject());
        ((IREP_Opportunity)mocks.verify(opportunityRepository, 1)).getOpportunityByID((Set<Id>)fflib_match.anyObject());
        ((FW_IREP_JobExecution)mocks.verify(jobExecutionRep, 1)).getJobExecWithBatchDefinitionsByIdSet((Set<Id>)fflib_match.anyObject());
        ((FW_IREP_Parameters)mocks.verify(parameterRep, 1)).getParametersByParentId((Set<Id>)fflib_match.anyObject());
    }

    class VoidAnswer implements fflib_Answer {
        public Object answer (fflib_InvocationOnMock invocation) {
            return null;
        }
    }
}