force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>SAP Invoices related to orders or not</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Customer account related, updated via SAP</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <description>Due Date, updated via SAP</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SendRemainder__c.field-meta.xml
<CustomField>
    <fullName>SendRemainder__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Technical field used to send the email and chatter notification about the due date of the invoice.</description>
    <label>Send Remainder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/REP_Invoice.cls
/**
* @description   Invoice Repository
* @testClass     REP_InvoiceTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Carolina Resende               28/11/2021          Created Invoice Repository
* ------------------------------------------------------------------------------------ 
*/
public  class REP_Invoice extends FW_SobjectRep implements IREP_Invoice{  
    public static final List<SObjectField> INVOICE_FIELDS = new SObjectField[] {
        Invoice__c.Id,
        Invoice__c.SendRemainder__c,
        Invoice__c.DueDate__c,
        Invoice__c.Account__c
    };
}