force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/FPS_Bor_Temporary_Storage__c.object-meta.xml
<CustomObject>
    <description>Intial CSV file is loaded into this object then its records are transformed to Service Contracts and Contract Line Items.
Borealis/FPS POC custom object</description>
    <label>Temporary Storage</label>
    <nameField>
        <displayFormat>TEMP - {0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Temporary Storages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Adjusted_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Adjusted_Quantity__c</fullName>
    <formula>IF(VALUE(SUBSTITUTE(SUBSTITUTE(Shifted_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)) &lt; 0, -1* VALUE(SUBSTITUTE(SUBSTITUTE(Shifted_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)),VALUE(SUBSTITUTE(SUBSTITUTE(Shifted_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;))) -
IF(VALUE(SUBSTITUTE(SUBSTITUTE(Allocated_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)) &lt; 0, -1* VALUE(SUBSTITUTE(SUBSTITUTE(Allocated_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)), VALUE(SUBSTITUTE(SUBSTITUTE(Allocated_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adjusted Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/CM_Master_Description__c.field-meta.xml
<CustomField>
    <fullName>CM_Master_Description__c</fullName>
    <label>CM Master Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/CM_Master_Number__c.field-meta.xml
<CustomField>
    <fullName>CM_Master_Number__c</fullName>
    <description>Used to update (upsert) correct contract line item.</description>
    <label>CM Master Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Open_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Open_Quantity__c</fullName>
    <formula>IF(VALUE(SUBSTITUTE(SUBSTITUTE(Shifted_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)) &lt; 0, -1* VALUE(SUBSTITUTE(SUBSTITUTE(Shifted_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)), VALUE(SUBSTITUTE(SUBSTITUTE(Shifted_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;))) -
IF(VALUE(SUBSTITUTE(SUBSTITUTE(Lifted_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)) &lt; 0, -1 * VALUE(SUBSTITUTE(SUBSTITUTE(Lifted_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)), VALUE(SUBSTITUTE(SUBSTITUTE(Lifted_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Open Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Posting_Period__c.field-meta.xml
<CustomField>
    <fullName>Posting_Period__c</fullName>
    <label>Posting Period</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Posting_Period_Date__c.field-meta.xml
<CustomField>
    <fullName>Posting_Period_Date__c</fullName>
    <formula>IF(
				Is_Service_Contract__c,
				null,
				DATE(VALUE(LEFT(Posting_Period__c, 4)), VALUE(RIGHT(Posting_Period__c, 2)), 1) 
				)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Posting Period Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Valid_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Valid_From_Date__c</fullName>
    <formula>DATE(VALUE(LEFT(Valid_From__c, 4)), VALUE(RIGHT(Valid_From__c, 2)), 1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valid From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Valid_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Valid_To_Date__c</fullName>
    <formula>IF(VALUE(RIGHT(Valid_to__c, 2)) = 12, 
					DATE(VALUE(LEFT(Valid_to__c, 4)), VALUE(RIGHT(Valid_to__c, 2)), 31),
			DATE(VALUE(LEFT(Valid_to__c, 4)), VALUE(RIGHT(Valid_to__c, 2))+1, 1)-1
			)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valid To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Adjusted_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Adjusted_Quantity__c</fullName>
    <label>Adjusted Quantity</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/CM_Master_Number__c.field-meta.xml
<CustomField>
    <fullName>CM_Master_Number__c</fullName>
    <externalId>true</externalId>
    <label>CM Master Number</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <description>Customer Name</description>
    <externalId>true</externalId>
    <inlineHelpText>Customer Name, defined as external id to speed up reporting via index</inlineHelpText>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Is_Master_Contract__c.field-meta.xml
<CustomField>
    <fullName>Is_Master_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Master Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Line_Item_Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Unique_Identifier__c</fullName>
    <externalId>true</externalId>
    <label>Line Item Unique Identifier</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Open_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Open_Quantity__c</fullName>
    <label>Open Quantity</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Posting_Period__c.field-meta.xml
<CustomField>
    <fullName>Posting_Period__c</fullName>
    <label>Posting Period</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ContractLineItemConverter.cls
/**
 * Created by mateuszbednarek on 20/01/2021.
 * Edit by Joana Neto (Capgemini) on 01/06/2021 with custom object API name change
 */

public with sharing class ContractLineItemConverter {

    static List<ServiceContract> lineItemsToUpsert = new List<ServiceContract>();
    static Schema.sObjectField externalIdField = ServiceContract.Line_Item_Unique_Identifier__c.getDescribe().getSObjectField();
    static List<Schema.FieldSetMember>  lineItemFields = Util.readFieldSet('Contract_Line_Item',
            'FPS_Bor_Temporary_Storage__c');
    static Set<Schema.FieldSetMember>  fieldToConvertToNumber = new Set<Schema.FieldSetMember>(Util.readFieldSet
            ('Number_type_fields',
                    'FPS_Bor_Temporary_Storage__c'));

    static List<FPS_Bor_Temporary_Storage__c> contractsList;
    static Map<String, ServiceContract> extIdToContract = getContracts();
    public static void convert(List<FPS_Bor_Temporary_Storage__c> lineItems) {
        contractsList = lineItems;
        createLineItems();

        Util.upsertRecords(lineItemsToUpsert, externalIdField, ContractLineItemConverter.class,'convert');
    }

    private static void createLineItems() {
        for (FPS_Bor_Temporary_Storage__c contract : contractsList) {
            if(serviceContractExists(contract)){
                lineItemsToUpsert.add(createLineItem(contract));
            }

        }
    }

    private static ServiceContract createLineItem(FPS_Bor_Temporary_Storage__c temp){
        ServiceContract lineItem =  new ServiceContract(
                ParentServiceContract = getServiceContract(temp.CM_Master_Number__c),
                Line_Item_Unique_Identifier__c = temp.CM_Master_Number__c + '_' + temp.Posting_Period__c,
                Name = temp.CM_Master_Number__c + '_' + temp.Posting_Period__c,
                Description = temp.CM_Master_Description__c,
                Posting_Period__c = temp.Posting_Period_Date__c,
                OwnerId = getOwnerId(temp.CM_Master_Number__c),
                Customer_Name__c = getCustomerName(temp.CM_Master_Number__c),
                StartDate = temp.Valid_From_Date__c,
                EndDate = temp.Valid_To_Date__c
        );


        for(Schema.FieldSetMember field: lineItemFields){
            String fieldPath = field.getFieldPath();
            Object fieldValue = temp.get(fieldPath);
            Boolean onlyPositive = fieldPath != 'Adjusted_Quantity__c' && fieldPath != 'Open_Quantity__c' ;
            if(fieldShouldBeConvertedToNumber(fieldPath)){
                fieldValue = convertFieldToNumericValue(fieldValue,onlyPositive);
            }
            lineItem.put(fieldPath, fieldValue);
        }

        return lineItem;
    }
    private static Boolean fieldShouldBeConvertedToNumber(String pathName){
        for(Schema.FieldSetMember field: fieldToConvertToNumber){
            if(field.getFieldPath() == pathName) return true;
        }
        return false;
    }
    private static Object convertFieldToNumericValue(Object textValue, Boolean onlyPositive){
        if(textValue == null){
            return null;
        }
        Decimal value = Decimal.valueOf(String.valueOf(textValue).replaceAll(' ','').replaceAll(',','' +
                '.'));
        return value < 0 && onlyPositive ? value * -1 : value;
    }

    private static ServiceContract getServiceContract(String extId) {
        return new ServiceContract(CM_Master_Number__c = extId);
    }
    private static Id getOwnerId(String extId) {
        if(extIdToContract.containsKey(extId)){
            return extIdToContract.get(extId).OwnerId;
        }
        return null;
    }

    private static String getCustomerName(String extId) {
        if(extIdToContract.containsKey(extId)){
            return extIdToContract.get(extId).Customer_Name__c;
        }
        return null;
    }

    private static Map<String, ServiceContract> getContracts(){
        if(extIdToContract == null){
            extIdToContract = new Map<String, ServiceContract>();
            for(ServiceContract ctr: [SELECT Id, CM_Master_Number__c,OwnerId, Customer_Name__c FROM ServiceContract
            WHERE
                    Is_Master_Contract__c = TRUE]){
                extIdToContract.put(ctr.CM_Master_Number__c, ctr);
            }

        }
        return extIdToContract;
    }

    private static Boolean serviceContractExists(FPS_Bor_Temporary_Storage__c contract){
        return extIdToContract.containsKey(contract.CM_Master_Number__c);
    }
}