force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/FPS_Bor_Temporary_Storage__c.object-meta.xml
<CustomObject>
    <description>Intial CSV file is loaded into this object then its records are transformed to Service Contracts and Contract Line Items.
Borealis/FPS POC custom object</description>
    <label>Temporary Storage</label>
    <nameField>
        <displayFormat>TEMP - {0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Temporary Storages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Adjusted_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Adjusted_Quantity__c</fullName>
    <formula>IF(VALUE(SUBSTITUTE(SUBSTITUTE(Shifted_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)) &lt; 0, -1* VALUE(SUBSTITUTE(SUBSTITUTE(Shifted_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)),VALUE(SUBSTITUTE(SUBSTITUTE(Shifted_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;))) -
IF(VALUE(SUBSTITUTE(SUBSTITUTE(Allocated_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)) &lt; 0, -1* VALUE(SUBSTITUTE(SUBSTITUTE(Allocated_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)), VALUE(SUBSTITUTE(SUBSTITUTE(Allocated_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adjusted Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Allocated_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Allocated_Quantity__c</fullName>
    <label>Allocated Quantity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/ATP_VSOP_Region__c.field-meta.xml
<CustomField>
    <fullName>ATP_VSOP_Region__c</fullName>
    <label>ATP VSOP Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>HU</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/CM_Master_Description__c.field-meta.xml
<CustomField>
    <fullName>CM_Master_Description__c</fullName>
    <label>CM Master Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/CM_Master_Number__c.field-meta.xml
<CustomField>
    <fullName>CM_Master_Number__c</fullName>
    <description>Used to update (upsert) correct contract line item.</description>
    <label>CM Master Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Contract_Line_Item_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Contract_Line_Item_Unique_Id__c</fullName>
    <formula>CM_Master_Number__c +&apos;_&apos;+Posting_Period__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Line Item Unique Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Contracted_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Contracted_Quantity__c</fullName>
    <label>Contracted Quantity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Contracted_Quantity_MAX__c.field-meta.xml
<CustomField>
    <fullName>Contracted_Quantity_MAX__c</fullName>
    <label>Contracted Quantity MAX</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Contracted_Quantity_MIN__c.field-meta.xml
<CustomField>
    <fullName>Contracted_Quantity_MIN__c</fullName>
    <label>Contracted Quantity MIN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Contracted_Quantity_UoM__c.field-meta.xml
<CustomField>
    <fullName>Contracted_Quantity_UoM__c</fullName>
    <label>Contracted Quantity UoM</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>L15</fullName>
            </value>
            <value>
                <fullName>M15</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <label>Customer Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Customer_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group_Name__c</fullName>
    <label>Customer Group Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aviation</fullName>
            </value>
            <value>
                <fullName>Constr and Industry</fullName>
            </value>
            <value>
                <fullName>CRT</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Marine</fullName>
            </value>
            <value>
                <fullName>Replenishment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Is_Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Is_Service_Contract__c</fullName>
    <formula>AND(
				NOT(ISBLANK(Posting_Period__c)),
				Posting_Period__c = &apos;0&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Service Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Lifted_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Lifted_Quantity__c</fullName>
    <label>Lifted Quantity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Minus_tolerance_in__c.field-meta.xml
<CustomField>
    <fullName>Minus_tolerance_in__c</fullName>
    <label>Minus tolerance in %</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Multi_Item_Master__c.field-meta.xml
<CustomField>
    <fullName>Multi_Item_Master__c</fullName>
    <label>Multi Item Master</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Open_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Open_Quantity__c</fullName>
    <formula>IF(VALUE(SUBSTITUTE(SUBSTITUTE(Shifted_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)) &lt; 0, -1* VALUE(SUBSTITUTE(SUBSTITUTE(Shifted_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)), VALUE(SUBSTITUTE(SUBSTITUTE(Shifted_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;))) -
IF(VALUE(SUBSTITUTE(SUBSTITUTE(Lifted_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)) &lt; 0, -1 * VALUE(SUBSTITUTE(SUBSTITUTE(Lifted_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)), VALUE(SUBSTITUTE(SUBSTITUTE(Lifted_Quantity__c,&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;.&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Open Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Penalty_Amount__c.field-meta.xml
<CustomField>
    <fullName>Penalty_Amount__c</fullName>
    <label>Penalty Amount</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Penalty_Interval__c.field-meta.xml
<CustomField>
    <fullName>Penalty_Interval__c</fullName>
    <label>Penalty Interval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>Q</fullName>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Penalty_UoM__c.field-meta.xml
<CustomField>
    <fullName>Penalty_UoM__c</fullName>
    <label>Penalty UoM</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>KGV</fullName>
            </value>
            <value>
                <fullName>L15</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
            <value>
                <fullName>M15</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Plus_tolerance_in__c.field-meta.xml
<CustomField>
    <fullName>Plus_tolerance_in__c</fullName>
    <label>Plus tolerance in %</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Posting_Period__c.field-meta.xml
<CustomField>
    <fullName>Posting_Period__c</fullName>
    <label>Posting Period</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Posting_Period_Date__c.field-meta.xml
<CustomField>
    <fullName>Posting_Period_Date__c</fullName>
    <formula>IF(
				Is_Service_Contract__c,
				null,
				DATE(VALUE(LEFT(Posting_Period__c, 4)), VALUE(RIGHT(Posting_Period__c, 2)), 1) 
				)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Posting Period Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Product_Category_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Category_Group__c</fullName>
    <formula>CASE(Product_Group__c, 
						&quot;DK&quot;, &quot;Diesel&quot;, 
						&quot;DKF&quot;, &quot;Diesel&quot;, 
						&quot;DKP&quot;, &quot;Diesel&quot;, 
						&quot;DKP_BIO&quot;, &quot;Diesel&quot;,
						&quot;EUR_ASF&quot;, &quot;Gasoline&quot;, 
						&quot;EUR_BIO&quot;, &quot;Gasoline&quot;, 
						&quot;EUR_E10&quot;, &quot;Gasoline&quot;, 
						&quot;EUR_PURE&quot;, &quot;Gasoline&quot;, 
						&quot;HEL&quot;, &quot;HEL&quot;, 
						&quot;SADK&quot;, &quot;Diesel&quot;, 
						&quot;SU+&quot;, &quot;Gasoline&quot;, 
						&quot;SU100&quot;, &quot;Gasoline&quot;, 
						&quot;VIT&quot;, &quot;HEL&quot;, 
						&quot;N/A&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Category Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <description>Represents unique external Price Instance ID. Used to match Price Instance (and as result also Product) with Contract Line Item.</description>
    <label>Product Group</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Product_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Group_Name__c</fullName>
    <label>Product Group Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Jet</fullName>
            </value>
            <value>
                <fullName>Mitteldestilate</fullName>
            </value>
            <value>
                <fullName>Ottokraftstoffe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Sales_Representative__c.field-meta.xml
<CustomField>
    <fullName>Sales_Representative__c</fullName>
    <label>Sales Representative</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Service_Contract_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract_Name__c</fullName>
    <formula>Customer__c +&apos;_&apos;+Product_Group__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Contract Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Shifted_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Shifted_Quantity__c</fullName>
    <label>Shifted Quantity</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Storage__c.field-meta.xml
<CustomField>
    <fullName>Storage__c</fullName>
    <label>Storage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CPL</fullName>
            </value>
            <value>
                <fullName>ETLB</fullName>
            </value>
            <value>
                <fullName>LOB</fullName>
            </value>
            <value>
                <fullName>LUS</fullName>
            </value>
            <value>
                <fullName>MOL_S</fullName>
            </value>
            <value>
                <fullName>RIED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Valid_From__c.field-meta.xml
<CustomField>
    <fullName>Valid_From__c</fullName>
    <label>Valid From</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FPS_Bor_Temporary_Storage__c/fields/Valid_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Valid_From_Date__c</fullName>
    <formula>DATE(VALUE(LEFT(Valid_From__c, 4)), VALUE(RIGHT(Valid_From__c, 2)), 1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valid From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ContractLineItemBatch.cls
/**
 * Created by mateuszbednarek on 21/01/2021.
 * Edit by Joana Neto (Capgemini) on 01/06/2021 with custom object API name change
 */

public with sharing class ContractLineItemBatch implements Database.Batchable<sObject>{
    String query = 'SELECT\n' +
            '        Adjusted_Quantity__c,\n' +
            '        Allocated_Quantity__c,\n' +
            '        ATP_VSOP_Region__c,\n' +
            '        CM_Master_Description__c,\n' +
            '        CM_Master_Number__c,\n' +
            '        Contract_Line_Item_Unique_Id__c,\n' +
            '        Contracted_Quantity__c,\n' +
            '        Contracted_Quantity_MAX__c,\n' +
            '        Contracted_Quantity_MIN__c,\n' +
            '        Contracted_Quantity_UoM__c,\n' +
            '        CreatedById,\n' +
            '        CreatedDate,\n' +
            '        CurrencyIsoCode,\n' +
            '        Customer__c,\n' +
            '        Customer_Group__c,\n' +
            '        Customer_Group_Name__c,\n' +
            '        Id,\n' +
            '        Is_Service_Contract__c,\n' +
            '        IsDeleted,\n' +
            '        LastModifiedById,\n' +
            '        LastModifiedDate,\n' +
            '        LastReferencedDate,\n' +
            '        LastViewedDate,\n' +
            '        Lifted_Quantity__c,\n' +
            '        Minus_tolerance_in__c,\n' +
            '        Multi_Item_Master__c,\n' +
            '        Name,\n' +
            '        Open_Quantity__c,\n' +
            '        OwnerId,\n' +
            '        Penalty_Amount__c,\n' +
            '        Penalty_Interval__c,\n' +
            '        Penalty_UoM__c,\n' +
            '        Plus_tolerance_in__c,\n' +
            '        Posting_Period__c,\n' +
            '        Posting_Period_Date__c,\n' +
            '        Product_Category_Group__c,\n' +
            '        Product_Group__c,\n' +
            '        Product_Group_Name__c,\n' +
            '        Sales_Representative__c,\n' +
            '        Service_Contract_Name__c,\n' +
            '        Shifted_Quantity__c,\n' +
            '        Storage__c,\n' +
            '        SystemModstamp,\n' +
            '        Valid_From__c,\n' +
            '        Valid_From_Date__c,\n' +
            '        Valid_to__c,Plant__c,\n' +
            '        Valid_To_Date__c\n' +
            'FROM FPS_Bor_Temporary_Storage__c\n' +
            'WHERE Is_Service_Contract__c = false';
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext bc, List<FPS_Bor_Temporary_Storage__c> scope){
        system.debug('Scope size line items ===> '+scope.size());
        ContractLineItemConverter.convert(scope);
    }
    public void finish(Database.BatchableContext bc){
        if(Test.isRunningTest()){
            Database.executeBatch(new ClearTemporaryStorageBatch(), 200);
        }else{
            Database.executeBatch(new ClearTemporaryStorageBatch(), 200);
        }
    }
}