force-app/main/default/objects/ProductDiscountCriteria__c/ProductDiscountCriteria__c.object-meta.xml
<CustomObject>
    <description>Datatable used to allow several different matching criteria for each applicable Product Discount</description>
    <label>Product Discount Criteria</label>
    <nameField>
        <label>Field API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Discount Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductDiscountCriteria__c/fields/FieldValue__c.field-meta.xml
<CustomField>
    <fullName>FieldValue__c</fullName>
    <description>Value that needs to be equal on the quote field</description>
    <label>Field Value</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DO_QuoteLineItem.cls
/**
* @description   QuoteLineItem domain object class
* @testClass     DO_QuoteLineItemTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro                03/08/2021          Created QuoteLineItem domain
* ------------------------------------------------------------------------------------ 
*/
public class DO_QuoteLineItem implements IDO_QuoteLineItem{
    /*
    * @author      Guilherme Charro
    * @description    method to check if the discounts criterias all match up with quote info
    */
    public Boolean isToApplyDiscountToQuoteItem(Quote quoteInfo, List<ProductDiscountCriteria__c> criteriasList, Integer quantityOfCriterias){
        Boolean returnValue = false;
        Integer criteriasMet = 0;
        for (ProductDiscountCriteria__c criteria : criteriasList) {
            String quoteFieldValue = (String)quoteInfo.get(criteria.Name);
            if (criteria.FieldValue__c == quoteFieldValue) {
                criteriasMet++;
            }
        }
        if (criteriasMet == quantityOfCriterias && quantityOfCriterias!=0 ) {
            returnValue = true;
        }
        
        return returnValue;
    }
}