force-app/main/default/objects/OMVPortalMenuItem__c/OMVPortalMenuItem__c.object-meta.xml
<CustomObject>
    <description>Custom object used to define top menu options for the OMV portal</description>
    <label>OMV Portal Menu Item</label>
    <nameField>
        <label>Menu Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OMV Portal Menu Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OMVPortalMenuItem__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <description>Order in which this item will be presented in the menu</description>
    <label>Order Item</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OMVPortalMenuItem__c/fields/PortalLayout__c.field-meta.xml
<CustomField>
    <fullName>PortalLayout__c</fullName>
    <description>OMV Portal layout that will use this menu option</description>
    <label>Portal Layout</label>
    <referenceTo>OMVPortalLayoutConfiguration__c</referenceTo>
    <relationshipLabel>OMV Portal Menu Items</relationshipLabel>
    <relationshipName>OMVPortalMenuItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/REP_OMVPortalMenuItem.cls
/**
* @description   OMV Portal Menu Item Repository
* @testClass     REP_OMVPortalMenuItemTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Hugo Rodrigues               24/11/2021         Created OMV Portal Menu Item Repository
* ------------------------------------------------------------------------------------ 
*/
public with sharing class REP_OMVPortalMenuItem  extends FW_SobjectRep implements IREP_OMVPortalMenuItem{
    public list<OMVPortalMenuItem__c> getOMVPortalMenubyLayout(Set<ID> omvPortalLayout) {
        return [SELECT Id, Name, PortalLayout__c,ItemType__c, OrderItem__c FROM OMVPortalMenuItem__c Where PortalLayout__c IN: omvPortalLayout Order By OrderItem__c];

    }
}