force-app/main/default/objects/Opportunity/fields/TotalPotentialFuelVolume__c.field-meta.xml
<CustomField>
    <fullName>TotalPotentialFuelVolume__c</fullName>
    <description>This filed is either mapped from the lead or manual input based on the Potential Diesel volume [kL/y] and Potential Gasoline volume [kL/y] . The value is a sum of potential diesel and gasoline volumes.</description>
    <formula>PotentialDieselvolumekLy__c +  PotentialGasolinevolumekLy__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Potential Fuel Volume [kL/Y]</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/REP_Opportunity.cls
/**
* @description   Opportunity Repository
* @testClass     REP_OpportunityTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Hugo Rodrigues               23/06/2021          Created Opportunity Repository
* ------------------------------------------------------------------------------------ 
*/
public class REP_Opportunity extends FW_SobjectRep implements IREP_Opportunity{
    public static final List<SObjectField> OPPORTUNITY_FIELDS = new SObjectField[] {
        Opportunity.Id,
        Opportunity.Name,
        Opportunity.CreatedDate,
        Opportunity.IsClosed,
        Opportunity.OwnerId,
        Opportunity.TotalPotentialFuelVolume__c
        
    };
    
    public List<Opportunity> getOpportunityByID(Set<ID> opportunityIdSet) {
        
		
        return [SELECT iD,OwnerId, Name, CreatedDate,IsClosed,TotalPotentialFuelVolume__c From Opportunity Where Id=:opportunityIdSet];
        

    }
    public List<Opportunity> getQuoteByOpportunityID(Set<ID> opportunityIdSet) {
        return [SELECT ID,CreatedDate,OwnerId, Name,(SELECT Id, ClosedDate__c,Status FROM Quotes ORDER BY ClosedDate__c DESC LIMIT 1) FROM Opportunity WHERE Id IN :opportunityIdSet ];
    }
    
}