force-app/main/default/objects/Contact/fields/CTITechnicalMobilePhone__c.field-meta.xml
<CustomField>
    <fullName>CTITechnicalMobilePhone__c</fullName>
    <description>Technical field that stores the 7 digits of the (Mobile Phone) so CTI can search the number in the Global Search</description>
    <label>Mobile</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CTITechnicalOtherPhone__c.field-meta.xml
<CustomField>
    <fullName>CTITechnicalOtherPhone__c</fullName>
    <description>Technical field that stores the 7 digits of the (Business Phone) so CTI can search the number in the Global Search</description>
    <label>Business Phone</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CTITechnicalPhone__c.field-meta.xml
<CustomField>
    <fullName>CTITechnicalPhone__c</fullName>
    <description>Technical field that stores the 7 digits of the (Phone) so CTI can search the number in the Global Search</description>
    <label>Phone</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TW_Contact_FillComplementaryFields.cls
/**
@description    worker class to automatically fill needed fields
@testClass      TW_Contact_FillComplementaryFieldsTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description  
* David Favinha                23/11/2021          Created the class
* ------------------------------------------------------------------------------------        
*/
public with sharing class TW_Contact_FillComplementaryFields {
    public void execute(List<Contact> newContactList, Map<Id,Contact> oldContactMap) {
        for (Contact contactRecord : newContactList) {
            if(oldContactMap == null || oldContactMap.get(contactRecord.Id).Phone != contactRecord.Phone ||
                    oldContactMap.get(contactRecord.Id).OtherPhone != contactRecord.OtherPhone ||
                    oldContactMap.get(contactRecord.Id).MobilePhone != contactRecord.MobilePhone ){
                contactRecord.CTITechnicalPhone__c = contactRecord.Phone?.right(7);
                contactRecord.CTITechnicalOtherPhone__c = contactRecord.OtherPhone?.right(7);
                contactRecord.CTITechnicalMobilePhone__c = contactRecord.MobilePhone?.right(7);
            }
        }
    }
}