force-app/main/default/objects/AccountCountryRelatedSetting__mdt/AccountCountryRelatedSetting__mdt.object-meta.xml
<CustomObject>
    <description>this metadata shows what are the objects with dependency with the account country sharing model</description>
    <label>Account Country Related Setting</label>
    <pluralLabel>Account Country Related Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/AccountCountryRelatedSetting__mdt/fields/AccountLookupAPIName__c.field-meta.xml
<CustomField>
    <fullName>AccountLookupAPIName__c</fullName>
    <description>used to identify the name of the field used as account lookup</description>
    <label>Account Lookup API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountCountryRelatedSetting__mdt/fields/AccountRelationshipName__c.field-meta.xml
<CustomField>
    <fullName>AccountRelationshipName__c</fullName>
    <description>field to store the Account relationship  name</description>
    <label>Account Relationship Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountCountryRelatedSetting__mdt/fields/CountryAPIName__c.field-meta.xml
<CustomField>
    <fullName>CountryAPIName__c</fullName>
    <description>field to identify the field which is gonna be populated</description>
    <label>Country API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountCountryRelatedSetting__mdt/fields/ObjectFilter__c.field-meta.xml
<CustomField>
    <fullName>ObjectFilter__c</fullName>
    <description>field to store a condition in which this object will be queried</description>
    <label>Object Filter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/REP_AccountCountryRelatedSetting.cls
/**
* @description   AccountCountryRelatedSetting Repository
* @testClass     REP_AccountCountryRelatedSettingTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro               02/09/2021          AccountCountryRelatedSetting Repository
* ------------------------------------------------------------------------------------ 
*/
public class REP_AccountCountryRelatedSetting extends FW_SobjectRep implements IREP_AccountCountryRelatedSetting{
    public static final List<SObjectField> ACCOUNTCOUNTRYRELATEDSETTING_FIELDS = new SObjectField[] {
        AccountCountryRelatedSetting__mdt.MasterLabel,
        AccountCountryRelatedSetting__mdt.AccountLookupAPIName__c,
        AccountCountryRelatedSetting__mdt.CountryAPIName__c,
        AccountCountryRelatedSetting__mdt.ObjectFilter__c
    };

    public List<AccountCountryRelatedSetting__mdt> getAllAccountCountryRelated(){
        return [SELECT MasterLabel,AccountLookupAPIName__c,CountryAPIName__c,ObjectFilter__c,AccountRelationshipName__c FROM AccountCountryRelatedSetting__mdt];
    }
}