force-app/main/default/objects/CEPEncrypt__c/CEPEncrypt__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting used for storing necessary data for encryption</description>
    <label>CEP Encrypt</label>
</CustomObject>

force-app/main/default/objects/CEPEncrypt__c/fields/AlgorithmName__c.field-meta.xml
<CustomField>
    <fullName>AlgorithmName__c</fullName>
    <description>name of the algorithm to use in encryption</description>
    <label>Algorithm Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEPEncrypt__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>key used for encryption</description>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEPEncrypt__c/fields/Vector__c.field-meta.xml
<CustomField>
    <fullName>Vector__c</fullName>
    <description>vector used for encrypting</description>
    <label>Vector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EncryptedDataGDPR__c/EncryptedDataGDPR__c.object-meta.xml
<CustomObject>
    <description>Object used to encrypt data for the GDPR</description>
    <label>Encrypted Data GDPR</label>
    <nameField>
        <displayFormat>Encrypted Data-{00000}</displayFormat>
        <label>Encrypted Data GDPR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encrypted Datas GDPR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EncryptedDataGDPR__c/fields/EmailEncrypted__c.field-meta.xml
<CustomField>
    <fullName>EmailEncrypted__c</fullName>
    <description>Email from lead or Contact encrypted</description>
    <label>Email Encrypted</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EncryptedDataGDPR__c/fields/MobilePhoneEncrypted__c.field-meta.xml
<CustomField>
    <fullName>MobilePhoneEncrypted__c</fullName>
    <description>Mobile phone from lead or Contact encrypted</description>
    <label>Mobile Phone Encrypted</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TW_Contact_CheckDataEncryptedTest.cls
/**
@author Guilherme Charro
@date    08/10/2021
@description Test class for TW_Contact_CheckDataEncrypted
@TestClass         
Modification Log:
----------------------------------------------------------------------------------------------------
Developer                       Date                Description                           Coverage
----------------------------------------------------------------------------------------------------
Guilherme Charro                08/10/2021         Original Version                         100
Hugo Rodrigues                28/10/2021          Updated to work with RecordType of Cards   100
*/
@isTest
private class TW_Contact_CheckDataEncryptedTest {
    static fflib_ApexMocks mocks = new fflib_ApexMocks();

    @testSetup
    private static void makeData(){
        String key = EncodingUtil.base64Encode(Crypto.generateAesKey(128));
        String vector = key.substring(0, 16);
        String algorithm = 'AES128';
        insert new CEPEncrypt__c(
            SetupOwnerId=UserInfo.getOrganizationId(),
            Key__c = key,
            AlgorithmName__c = algorithm,
            Vector__c = vector
        );
    }

    @isTest
    static void TW_Contact_CheckDataEncryptedTest() {
        IREP_EncryptedDataGDPR encryptedDataRepository = (REP_EncryptedDataGDPR)mocks.mock(REP_EncryptedDataGDPR.class);

        List<Contact> contactList = new List<Contact>{
            new Contact(
                Id = fflib_IDGenerator.generate(Contact.sObjectType),
                Email = 'teste@teste.com',
                GeneralGDPR__c = DO_Contact.Contact_GDPR_NO,
                RecordTypeID= Do_Contact.CONTACT_RECORDTYPEID_CEPCARDS
            ),
            new Contact(
                Id = fflib_IDGenerator.generate(Contact.sObjectType),
                MobilePhone = '999999999',
                GeneralGDPR__c = DO_Contact.Contact_GDPR_YES,
                RecordTypeID= Do_Contact.CONTACT_RECORDTYPEID_CEPCARDS
            )
        };

        List<EncryptedDataGDPR__c> encryptedDataList = new List<EncryptedDataGDPR__c>{
            new EncryptedDataGDPR__c(
                Id = fflib_IDGenerator.generate(EncryptedDataGDPR__c.sObjectType),
                EmailEncrypted__c = DO_EncryptedDataGDPR.encryptData('teste@teste.com')
            ),
            new EncryptedDataGDPR__c(
                Id = fflib_IDGenerator.generate(EncryptedDataGDPR__c.sObjectType),
                MobilePhoneEncrypted__c = DO_EncryptedDataGDPR.encryptData(String.valueOf(999999999))
            )
        };

        mocks.startStubbing();
        mocks.when(encryptedDataRepository.getEncryptedData((List<String>)  fflib_match.anyList())).thenReturn(encryptedDataList);
        mocks.when(encryptedDataRepository.deleteSObjects((List<EncryptedDataGDPR__c>)  fflib_match.anyList())).thenReturn(new List<Database.DeleteResult>());
        mocks.stopStubbing();

        TW_Contact_CheckDataEncrypted jobExecutionWorker = new TW_Contact_CheckDataEncrypted();
        jobExecutionWorker = new TW_Contact_CheckDataEncrypted(encryptedDataRepository);
        
        jobExecutionWorker.execute(contactList);

        ((IREP_EncryptedDataGDPR)mocks.verify(encryptedDataRepository, 2)).getEncryptedData((List<String>) fflib_match.anyList());
        ((IREP_EncryptedDataGDPR)mocks.verify(encryptedDataRepository, 1)).deleteSObjects((List<EncryptedDataGDPR__c>) fflib_match.anyList());
    }
}