force-app/main/default/objects/CEPEncrypt__c/CEPEncrypt__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting used for storing necessary data for encryption</description>
    <label>CEP Encrypt</label>
</CustomObject>

force-app/main/default/objects/CEPEncrypt__c/fields/AlgorithmName__c.field-meta.xml
<CustomField>
    <fullName>AlgorithmName__c</fullName>
    <description>name of the algorithm to use in encryption</description>
    <label>Algorithm Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEPEncrypt__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>key used for encryption</description>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEPEncrypt__c/fields/Vector__c.field-meta.xml
<CustomField>
    <fullName>Vector__c</fullName>
    <description>vector used for encrypting</description>
    <label>Vector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EncryptedDataGDPR__c/EncryptedDataGDPR__c.object-meta.xml
<CustomObject>
    <description>Object used to encrypt data for the GDPR</description>
    <label>Encrypted Data GDPR</label>
    <nameField>
        <displayFormat>Encrypted Data-{00000}</displayFormat>
        <label>Encrypted Data GDPR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encrypted Datas GDPR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EncryptedDataGDPR__c/fields/BusinessPhoneEncrypted__c.field-meta.xml
<CustomField>
    <fullName>BusinessPhoneEncrypted__c</fullName>
    <description>Business phone from lead or Contact encrypted</description>
    <label>Business Phone Encrypted</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EncryptedDataGDPR__c/fields/EmailEncrypted__c.field-meta.xml
<CustomField>
    <fullName>EmailEncrypted__c</fullName>
    <description>Email from lead or Contact encrypted</description>
    <label>Email Encrypted</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EncryptedDataGDPR__c/fields/MobilePhoneEncrypted__c.field-meta.xml
<CustomField>
    <fullName>MobilePhoneEncrypted__c</fullName>
    <description>Mobile phone from lead or Contact encrypted</description>
    <label>Mobile Phone Encrypted</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DO_EncryptedDataGDPR.cls
/**
* @description   EncryptedDataGDPR__c domain object class
* @testClass     N/A
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Guilherme Charro                29/09/2021          Created EncryptedDataGDPR__c domain
* ------------------------------------------------------------------------------------ 
*/
public class DO_EncryptedDataGDPR implements IDO_EncryptedDataGDPR{
    public final static CEPEncrypt__c orgDefaults = CEPEncrypt__c.getOrgDefaults();

    /**
    * @description method to encrypt data
    * @author Guilherme Charro | 29-09-2021 
    * @param data data to be encrypted 
    * @return String this string is the encrypted value of the data 
    **/
    public static String encryptData(String data){
        String returned = null;
        if (data != null) {
            returned = EncodingUtil.base64Encode(Crypto.encrypt(orgDefaults.AlgorithmName__c, EncodingUtil.base64Decode(orgDefaults.Key__c), Blob.valueOf(orgDefaults.Vector__c), Blob.valueOf(data)));
        }
        return returned;
    }

    /**
    * @description method to create a new EncryptedDataGDPR__c record
    * @author Guilherme Charro | 29-09-2021 
    * @param mobile encrypted mobile data to be assigned to the record
    * @param business encrypted business phone data to be assigned to the record
    * @param email encrypted email data to be assigned to the record
    * @return EncryptedDataGDPR__c record that was created 
    **/
    public static EncryptedDataGDPR__c createEncryptedData(String mobile, String business, String email){
        EncryptedDataGDPR__c encrypedDataRecord = null;

        if (mobile != null || business != null || email != null) {
            encrypedDataRecord = new EncryptedDataGDPR__c(
                MobilePhoneEncrypted__c = mobile,
                BusinessPhoneEncrypted__c = business,
                EmailEncrypted__c = email
            );
        }

        return encrypedDataRecord;
    }
}