force-app/main/default/objects/OMVPortalLayoutConfiguration__c/OMVPortalLayoutConfiguration__c.object-meta.xml
<CustomObject>
    <description>Custom object used to define the layout of certain components of the OMV Portal according to the Customer Country</description>
    <label>OMV Portal Layout Configuration</label>
    <nameField>
        <displayFormat>OPLN-{00000}</displayFormat>
        <label>OMV Portal Layout Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OMV Portal Layouts Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OMVPortalLayoutConfiguration__c/fields/CustomerCountryISOCode__c.field-meta.xml
<CustomField>
    <fullName>CustomerCountryISOCode__c</fullName>
    <description>ISO country of the customer, that will use this layout configuration,</description>
    <label>Customer Country ISO Code</label>
    <length>5</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OMVPortalLayoutConfiguration__c/fields/FooterLogo__c.field-meta.xml
<CustomField>
    <fullName>FooterLogo__c</fullName>
    <description>Unique name of the document that contains the logo used in the bottom of the OMV portal pages</description>
    <label>Footer Logo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OMVPortalLayoutConfiguration__c/fields/HeaderLogo__c.field-meta.xml
<CustomField>
    <fullName>HeaderLogo__c</fullName>
    <description>Unique name of the document that contains the logo used in the top of the OMV portal pages</description>
    <label>Header Logo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OMVPortalLayoutConfiguration__c/fields/HeaderText__c.field-meta.xml
<CustomField>
    <fullName>HeaderText__c</fullName>
    <description>Text that is presented on top of the main menu</description>
    <label>Header Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OMVPortalLayoutConfiguration__c/fields/HeroText__c.field-meta.xml
<CustomField>
    <fullName>HeroText__c</fullName>
    <description>Text that is presented on the &quot;hero&quot; component in the home page.</description>
    <label>Hero Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OMVPortalLayoutConfiguration__c/fields/MenuEnergyLineColor__c.field-meta.xml
<CustomField>
    <fullName>MenuEnergyLineColor__c</fullName>
    <description>hexadecimal color code to be used in the menu of the OMV Portal.</description>
    <label>Menu Energy Line Color</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OMVPortalMenuItem__c/OMVPortalMenuItem__c.object-meta.xml
<CustomObject>
    <description>Custom object used to define top menu options for the OMV portal</description>
    <label>OMV Portal Menu Item</label>
    <nameField>
        <label>Menu Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OMV Portal Menu Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OMVPortalMenuItem__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <description>Order in which this item will be presented in the menu</description>
    <label>Order Item</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OMVPortalMenuItem__c/fields/PortalLayout__c.field-meta.xml
<CustomField>
    <fullName>PortalLayout__c</fullName>
    <description>OMV Portal layout that will use this menu option</description>
    <label>Portal Layout</label>
    <referenceTo>OMVPortalLayoutConfiguration__c</referenceTo>
    <relationshipLabel>OMV Portal Menu Items</relationshipLabel>
    <relationshipName>OMVPortalMenuItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/REP_OMVPortalLayoutConfiguration.cls
/**
* @description   OMV Portal Layout Configuration Repository
* @testClass     REP_OMVPortalLayoutConfigurationTest
* Modification Log 
* ------------------------------------------------------------------------------------  
* Developer                       Date                Description 
* Hugo Rodrigues               24/11/2021         Created OMV Portal Layout Configuration Repository
* ------------------------------------------------------------------------------------ 
*/
public with sharing class REP_OMVPortalLayoutConfiguration extends FW_SobjectRep implements IREP_OMVPortalLayoutConfiguration{
    public OMVPortalLayoutConfiguration__c getOMVPortalLayoutbyCountry(String country) {
        return [SELECT Id, OwnerId, Name, CurrencyIsoCode, CustomerCountryISOCode__c, MenuEnergyLineColor__c, 
        HeaderLogo__c, FooterLogo__c, HeaderText__c, HeroText__c,(SELECT Id,Name, PortalLayout__c,ItemType__c, OrderItem__c FROM OMVPortalMenuItems__r ORDER BY OrderItem__c) FROM OMVPortalLayoutConfiguration__c Where CustomerCountryISOCode__c =: country];

    }
}