force-app/main/default/objects/OMVPortalLayoutConfiguration__c/OMVPortalLayoutConfiguration__c.object-meta.xml
<CustomObject>
    <description>Custom object used to define the layout of certain components of the OMV Portal according to the Customer Country</description>
    <label>OMV Portal Layout Configuration</label>
    <nameField>
        <displayFormat>OPLN-{00000}</displayFormat>
        <label>OMV Portal Layout Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OMV Portal Layouts Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OMVPortalLayoutConfiguration__c/fields/CustomerCountryISOCode__c.field-meta.xml
<CustomField>
    <fullName>CustomerCountryISOCode__c</fullName>
    <description>ISO country of the customer, that will use this layout configuration,</description>
    <label>Customer Country ISO Code</label>
    <length>5</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/REP_OMVPortalLayoutConfigurationTest.cls
/**
@author Hugo Rodrigues  
@date   24/11/2021 
@description Test class for REP_OMVPortalLayoutConfiguration
@TestClass         
Modification Log:
----------------------------------------------------------------------------------------------------
Developer                       Date                Description                           Coverage
----------------------------------------------------------------------------------------------------
Hugo Rodrigues               24/11/2021           Original Version                         100
*/
@isTest
public class REP_OMVPortalLayoutConfigurationTest {
    @isTest
    static void OMVPortalLayoutConfigurationTest() {
        User runningUser = FW_TestDataFactory.createUsers(1, true, 'System Administrator', null).get(0);
        System.runAs(runningUser){  
            List<OMVPortalLayoutConfiguration__c> listOMVPortalLayout =new  List<OMVPortalLayoutConfiguration__c>{
                new OMVPortalLayoutConfiguration__c(
                    CustomerCountryISOCode__c='TE'
                ) };
                insert listOMVPortalLayout;
            test.startTest();
            REP_OMVPortalLayoutConfiguration omvPortalLayoutRepository = new REP_OMVPortalLayoutConfiguration();
            List<OMVPortalLayoutConfiguration__c> omvPortalLayoutList = omvPortalLayoutRepository.getOMVPortalLayoutbyCountry('TE');
            test.stopTest();
            System.assertEquals(1, omvPortalLayoutList.size());
           
        }
    }
}