force-app/main/default/objects/OMVPortalLayoutConfiguration__c/OMVPortalLayoutConfiguration__c.object-meta.xml
<CustomObject>
    <description>Custom object used to define the layout of certain components of the OMV Portal according to the Customer Country</description>
    <label>OMV Portal Layout Configuration</label>
    <nameField>
        <displayFormat>OPLN-{00000}</displayFormat>
        <label>OMV Portal Layout Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OMV Portal Layouts Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OMVPortalLayoutConfiguration__c/fields/HeaderLogo__c.field-meta.xml
<CustomField>
    <fullName>HeaderLogo__c</fullName>
    <description>Unique name of the document that contains the logo used in the top of the OMV portal pages</description>
    <label>Header Logo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/oMVPortalMainMenuControler.cls
public with sharing class oMVPortalMainMenuControler {

    public class OmvUserLayout {
        @AuraEnabled
        public User userInfo { get; set; }

        @AuraEnabled
        public OMVPortalLayoutConfiguration__c layoutConfiguration { get; set; }

        @AuraEnabled
        public String imageUrlString { get; set; }
    }

    @AuraEnabled(cacheable=true)
    //public static sObject getOMVPortalLayout() {
    public static OmvUserLayout getOMVPortalLayout() {
        REP_User userRepository = new REP_User();
        REP_StaticResource stacticResourceRepository = new REP_StaticResource();
        User userRecord = new User();
        String userCountry;
        REP_OMVPortalLayoutConfiguration portalRepository = new REP_OMVPortalLayoutConfiguration();
        OMVPortalLayoutConfiguration__c portalObject= new  OMVPortalLayoutConfiguration__c();
        OmvUserLayout userLayout = new OmvUserLayout();
        Set<String> imageSet = new Set<String>();
        userRecord=userRepository.getPortalUserAndCompanyCode(new Set<Id>{UserInfo.getUserId()}).get(0);

        if(userRecord!=null){
            userCountry=userRecord.Contact.Account.CompanyCodeCountry__c;
        }

        if (String.isBlank(userCountry)) {
            userCountry = 'AT';
        }

        if(userCountry !=null){
            portalObject = portalRepository.getOMVPortalLayoutbyCountry(userCountry);
        }
        imageSet.add(portalObject.HeaderLogo__c);
        userLayout.userInfo = userRecord;
        userLayout.layoutConfiguration = portalObject;
        
        Map<String,String> iconUrlMap = stacticResourceRepository.getStaticResourceBySet(imageSet);
        userLayout.imageUrlString=iconUrlMap.get(portalObject.HeaderLogo__c);
        return userLayout;
        
    }
}