force-app/main/default/objects/OMVPortalLayoutConfiguration__c/OMVPortalLayoutConfiguration__c.object-meta.xml
<CustomObject>
    <description>Custom object used to define the layout of certain components of the OMV Portal according to the Customer Country</description>
    <label>OMV Portal Layout Configuration</label>
    <nameField>
        <displayFormat>OPLN-{00000}</displayFormat>
        <label>OMV Portal Layout Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OMV Portal Layouts Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OMVPortalLayoutConfiguration__c/fields/CustomerCountryISOCode__c.field-meta.xml
<CustomField>
    <fullName>CustomerCountryISOCode__c</fullName>
    <description>ISO country of the customer, that will use this layout configuration,</description>
    <label>Customer Country ISO Code</label>
    <length>5</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OMVPortalMenuItem__c/OMVPortalMenuItem__c.object-meta.xml
<CustomObject>
    <description>Custom object used to define top menu options for the OMV portal</description>
    <label>OMV Portal Menu Item</label>
    <nameField>
        <label>Menu Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OMV Portal Menu Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OMVPortalMenuItem__c/fields/PortalLayout__c.field-meta.xml
<CustomField>
    <fullName>PortalLayout__c</fullName>
    <description>OMV Portal layout that will use this menu option</description>
    <label>Portal Layout</label>
    <referenceTo>OMVPortalLayoutConfiguration__c</referenceTo>
    <relationshipLabel>OMV Portal Menu Items</relationshipLabel>
    <relationshipName>OMVPortalMenuItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/REP_OMVPortalMenuItemTest.cls
/**
@author Hugo Rodrigues  
@date   24/11/2021 
@description Test class for REP_OMVPortalMenuItem
@TestClass         
Modification Log:
----------------------------------------------------------------------------------------------------
Developer                       Date                Description                           Coverage
----------------------------------------------------------------------------------------------------
Hugo Rodrigues               24/11/2021           Original Version                         100
*/
@isTest
public class REP_OMVPortalMenuItemTest {
    @isTest
    static void REP_OMVPortalMenuItemTest() {
        User runningUser = FW_TestDataFactory.createUsers(1, true, 'System Administrator', null).get(0);
        System.runAs(runningUser){  
            List<OMVPortalLayoutConfiguration__c> listOMVPortalLayout =new  List<OMVPortalLayoutConfiguration__c>{
                new OMVPortalLayoutConfiguration__c(
                    CustomerCountryISOCode__c='TE'
                ) };
                insert listOMVPortalLayout;
            List<OMVPortalMenuItem__c> listOMVPortalMenu =new  List<OMVPortalMenuItem__c>{
                new OMVPortalMenuItem__c(
                    PortalLayout__c=listOMVPortalLayout[0].id
                ) };
                insert listOMVPortalMenu;
            test.startTest();
            REP_OMVPortalMenuItem omvPortalMenuRepository = new REP_OMVPortalMenuItem();
            List<OMVPortalMenuItem__c> omvPortalMenuList = omvPortalMenuRepository.getOMVPortalMenubyLayout(new Set<Id> {listOMVPortalLayout[0].id});
            test.stopTest();
            System.assertEquals(1, omvPortalMenuList.size());
           
        }
    }
}